#!/usr/bin/env python3
"""Add all missing translation keys for Home.tsx, SellerDashboard.tsx, Contact.tsx, etc."""
import json

LOCALES_DIR = "/home/ubuntu/boxium-ptcg/client/src/locales"

# All new keys to add across all 3 languages
NEW_KEYS = {
    "zh-TW": {
        "home": {
            "cardDatabase": "張卡牌資料庫",
            "globalTransactions": "萬+ 全球成交記錄",
            "cardSearch": "卡牌搜尋",
            "priceComparison": "市場格價",
            "psaGrading": "PSA 鑑定",
            "marketplace": "市集",
            "gradingDesc": "專業代客鑑定服務",
            "marketplaceDesc2": "安全交易平台",
            "realtimeDataTitle": "即時數據",
            "realtimeDataDesc": "每 12 小時自動更新，整合 SNKRDUNK 及全球市場的真實成交記錄。",
            "safeTrading": "安全交易",
            "safeTradingDesc": "市集採用 Stripe 支付保障，買賣雙方均受平台條款保護。",
            "playerCommunity": "玩家社群",
            "playerCommunityDesc": "為 TCG 愛好者打造的專屬平台，追蹤卡牌動態、交流收藏樂趣。",
            "aboutBoxium": "關於 BOXIUM",
            "aboutBoxiumDesc": "BOXIUM 是專為 TCG 集換式卡牌愛好者打造的綜合平台，整合全球市場數據，提供即時、準確的卡牌價格資訊，並設有安全可靠的二手交易市集。",
            "ourStory": "我們的故事",
            "ourStoryDesc1": "BOXIUM 由一群熱愛 TCG 的玩家創立，深知卡牌市場資訊分散、價格難以追蹤的痛點。我們致力於整合 SNKRDUNK 等全球交易平台的真實成交數據，讓每位玩家都能輕鬆掌握市場行情。",
            "ourStoryDesc2": "從 Pokémon 到 One Piece、遊戲王，我們覆蓋多款主流 TCG，並持續擴展數據來源，為收藏家和投資者提供最可靠的參考依據。",
            "contactUs": "聯絡我們",
            "contactUsDesc": "有任何問題或建議？歡迎與我們聯繫。",
            "contact": "聯絡",
            "learnMoreAboutBoxium": "了解更多關於 BOXIUM",
            "usdPrice": "美元價格",
            "cardImageAlt": "卡牌圖像",
        },
        "contact": {
            "title": "聯絡我們",
            "subtitle": "有任何問題或建議？歡迎與我們聯繫",
            "name": "姓名",
            "namePlaceholder": "請輸入您的姓名",
            "email": "電子郵件",
            "emailPlaceholder": "請輸入您的電子郵件",
            "subject": "主旨",
            "subjectPlaceholder": "請輸入主旨",
            "message": "訊息內容",
            "messagePlaceholder": "請輸入您的訊息",
            "send": "送出",
            "sending": "送出中...",
            "successTitle": "訊息已送出",
            "successDesc": "感謝您的來信，我們將盡快回覆您。",
            "errorTitle": "送出失敗",
            "errorDesc": "請稍後再試或直接發送電子郵件至我們的信箱。",
            "required": "必填",
            "followUs": "追蹤我們",
            "emailUs": "電子郵件",
            "faq": "常見問題",
            "faqDesc": "查看常見問題解答",
        },
        "seller": {
            "dashboard": "賣家中心",
            "totalRevenue": "總收入",
            "totalOrders": "總訂單數",
            "pendingOrders": "待處理訂單",
            "activeListings": "上架中商品",
            "recentOrders": "最近訂單",
            "myListings": "我的商品",
            "addListing": "新增商品",
            "editListing": "編輯商品",
            "deleteListing": "刪除商品",
            "delistItem": "下架商品",
            "relistItem": "重新上架",
            "uploadImage": "上傳圖片",
            "uploadImageDesc": "點擊或拖曳圖片至此處上傳",
            "imageFormats": "支援 JPG、PNG、WebP 格式",
            "maxFileSize": "最大檔案大小：5MB",
            "noListings": "尚無商品",
            "noListingsDesc": "點擊「新增商品」開始上架您的卡牌",
            "orderStatus": "訂單狀態",
            "statusPending": "待付款",
            "statusPaid": "已付款",
            "statusShipped": "已出貨",
            "statusDelivered": "已送達",
            "statusCancelled": "已取消",
            "statusRefunded": "已退款",
            "statusCompleted": "已完成",
            "markAsShipped": "標記為已出貨",
            "trackingNumber": "追蹤號碼",
            "enterTrackingNumber": "請輸入追蹤號碼",
            "confirmShipment": "確認出貨",
            "buyerInfo": "買家資訊",
            "shippingAddress": "收件地址",
            "orderTotal": "訂單金額",
            "platformFee": "平台服務費",
            "netRevenue": "實收金額",
            "selectAll": "全選",
            "bulkDelist": "批量下架",
            "bulkActions": "批量操作",
            "listingTitle": "商品名稱",
            "listingPrice": "售價",
            "listingCondition": "品相",
            "listingQuantity": "數量",
            "listingDescription": "商品描述",
            "listingImages": "商品圖片",
            "saveChanges": "儲存變更",
            "cancelEdit": "取消編輯",
            "confirmDelete": "確認刪除",
            "confirmDeleteDesc": "確定要刪除此商品嗎？此操作無法復原。",
            "applyToSell": "申請成為賣家",
            "pendingApproval": "審核中",
            "approved": "已核准",
            "rejected": "已拒絕",
        },
        "orders": {
            "title": "我的訂單",
            "allOrders": "全部訂單",
            "noOrders": "尚無訂單",
            "noOrdersDesc": "您目前沒有任何訂單記錄",
            "orderNumber": "訂單編號",
            "orderDate": "訂單日期",
            "orderStatus": "訂單狀態",
            "orderTotal": "訂單金額",
            "viewDetail": "查看詳情",
            "statusPending": "待付款",
            "statusPaid": "已付款",
            "statusShipped": "已出貨",
            "statusDelivered": "已送達",
            "statusCancelled": "已取消",
            "statusRefunded": "已退款",
            "statusCompleted": "已完成",
            "buyerOrders": "買家訂單",
            "sellerOrders": "賣家訂單",
            "payNow": "立即付款",
            "cancelOrder": "取消訂單",
            "confirmCancel": "確認取消",
            "confirmCancelDesc": "確定要取消此訂單嗎？",
        },
        "cart": {
            "title": "購物車",
            "empty": "購物車是空的",
            "emptyDesc": "前往市集探索卡牌",
            "goToMarketplace": "前往市集",
            "removeItem": "移除商品",
            "quantity": "數量",
            "subtotal": "小計",
            "total": "總計",
            "checkout": "結帳",
            "continueShopping": "繼續購物",
            "itemCount": "件商品",
            "shippingFee": "運費",
            "freeShipping": "免運費",
            "proceedToCheckout": "前往結帳",
            "clearCart": "清空購物車",
            "confirmClear": "確認清空",
            "confirmClearDesc": "確定要清空購物車嗎？",
        },
    },
    "en": {
        "home": {
            "cardDatabase": "card database",
            "globalTransactions": "M+ global transactions",
            "cardSearch": "Card Search",
            "priceComparison": "Price Comparison",
            "psaGrading": "PSA Grading",
            "marketplace": "Marketplace",
            "gradingDesc": "Professional grading service",
            "marketplaceDesc2": "Safe trading platform",
            "realtimeDataTitle": "Real-time Data",
            "realtimeDataDesc": "Auto-updated every 12 hours, integrating real transaction records from SNKRDUNK and global markets.",
            "safeTrading": "Safe Trading",
            "safeTradingDesc": "Marketplace uses Stripe payment protection, both buyers and sellers are protected by platform terms.",
            "playerCommunity": "Player Community",
            "playerCommunityDesc": "A dedicated platform for TCG enthusiasts to track card trends and share collection experiences.",
            "aboutBoxium": "About BOXIUM",
            "aboutBoxiumDesc": "BOXIUM is a comprehensive platform built for TCG card enthusiasts, integrating global market data to provide real-time, accurate card price information and a safe second-hand trading marketplace.",
            "ourStory": "Our Story",
            "ourStoryDesc1": "BOXIUM was founded by a group of TCG players who understood the pain of scattered card market information and hard-to-track prices. We are dedicated to integrating real transaction data from global trading platforms like SNKRDUNK, so every player can easily grasp market trends.",
            "ourStoryDesc2": "From Pokémon to One Piece and Yu-Gi-Oh!, we cover multiple mainstream TCGs and continuously expand our data sources to provide collectors and investors with the most reliable reference.",
            "contactUs": "Contact Us",
            "contactUsDesc": "Have any questions or suggestions? Feel free to reach out.",
            "contact": "Contact",
            "learnMoreAboutBoxium": "Learn more about BOXIUM",
            "usdPrice": "USD price",
            "cardImageAlt": "card image",
        },
        "contact": {
            "title": "Contact Us",
            "subtitle": "Have any questions or suggestions? Feel free to reach out",
            "name": "Name",
            "namePlaceholder": "Enter your name",
            "email": "Email",
            "emailPlaceholder": "Enter your email",
            "subject": "Subject",
            "subjectPlaceholder": "Enter subject",
            "message": "Message",
            "messagePlaceholder": "Enter your message",
            "send": "Send",
            "sending": "Sending...",
            "successTitle": "Message Sent",
            "successDesc": "Thank you for your message. We will reply as soon as possible.",
            "errorTitle": "Send Failed",
            "errorDesc": "Please try again later or email us directly.",
            "required": "Required",
            "followUs": "Follow Us",
            "emailUs": "Email",
            "faq": "FAQ",
            "faqDesc": "View frequently asked questions",
        },
        "seller": {
            "dashboard": "Seller Dashboard",
            "totalRevenue": "Total Revenue",
            "totalOrders": "Total Orders",
            "pendingOrders": "Pending Orders",
            "activeListings": "Active Listings",
            "recentOrders": "Recent Orders",
            "myListings": "My Listings",
            "addListing": "Add Listing",
            "editListing": "Edit Listing",
            "deleteListing": "Delete Listing",
            "delistItem": "Delist Item",
            "relistItem": "Relist Item",
            "uploadImage": "Upload Image",
            "uploadImageDesc": "Click or drag image here to upload",
            "imageFormats": "Supports JPG, PNG, WebP formats",
            "maxFileSize": "Max file size: 5MB",
            "noListings": "No Listings",
            "noListingsDesc": "Click 'Add Listing' to start listing your cards",
            "orderStatus": "Order Status",
            "statusPending": "Pending",
            "statusPaid": "Paid",
            "statusShipped": "Shipped",
            "statusDelivered": "Delivered",
            "statusCancelled": "Cancelled",
            "statusRefunded": "Refunded",
            "statusCompleted": "Completed",
            "markAsShipped": "Mark as Shipped",
            "trackingNumber": "Tracking Number",
            "enterTrackingNumber": "Enter tracking number",
            "confirmShipment": "Confirm Shipment",
            "buyerInfo": "Buyer Info",
            "shippingAddress": "Shipping Address",
            "orderTotal": "Order Total",
            "platformFee": "Platform Fee",
            "netRevenue": "Net Revenue",
            "selectAll": "Select All",
            "bulkDelist": "Bulk Delist",
            "bulkActions": "Bulk Actions",
            "listingTitle": "Listing Title",
            "listingPrice": "Price",
            "listingCondition": "Condition",
            "listingQuantity": "Quantity",
            "listingDescription": "Description",
            "listingImages": "Images",
            "saveChanges": "Save Changes",
            "cancelEdit": "Cancel Edit",
            "confirmDelete": "Confirm Delete",
            "confirmDeleteDesc": "Are you sure you want to delete this listing? This action cannot be undone.",
            "applyToSell": "Apply to Sell",
            "pendingApproval": "Pending Approval",
            "approved": "Approved",
            "rejected": "Rejected",
        },
        "orders": {
            "title": "My Orders",
            "allOrders": "All Orders",
            "noOrders": "No Orders",
            "noOrdersDesc": "You have no order records yet",
            "orderNumber": "Order Number",
            "orderDate": "Order Date",
            "orderStatus": "Order Status",
            "orderTotal": "Order Total",
            "viewDetail": "View Details",
            "statusPending": "Pending",
            "statusPaid": "Paid",
            "statusShipped": "Shipped",
            "statusDelivered": "Delivered",
            "statusCancelled": "Cancelled",
            "statusRefunded": "Refunded",
            "statusCompleted": "Completed",
            "buyerOrders": "Buyer Orders",
            "sellerOrders": "Seller Orders",
            "payNow": "Pay Now",
            "cancelOrder": "Cancel Order",
            "confirmCancel": "Confirm Cancel",
            "confirmCancelDesc": "Are you sure you want to cancel this order?",
        },
        "cart": {
            "title": "Shopping Cart",
            "empty": "Your cart is empty",
            "emptyDesc": "Go to the marketplace to explore cards",
            "goToMarketplace": "Go to Marketplace",
            "removeItem": "Remove Item",
            "quantity": "Quantity",
            "subtotal": "Subtotal",
            "total": "Total",
            "checkout": "Checkout",
            "continueShopping": "Continue Shopping",
            "itemCount": "items",
            "shippingFee": "Shipping Fee",
            "freeShipping": "Free Shipping",
            "proceedToCheckout": "Proceed to Checkout",
            "clearCart": "Clear Cart",
            "confirmClear": "Confirm Clear",
            "confirmClearDesc": "Are you sure you want to clear your cart?",
        },
    },
    "ja": {
        "home": {
            "cardDatabase": "枚のカードデータベース",
            "globalTransactions": "万件以上のグローバル取引",
            "cardSearch": "カード検索",
            "priceComparison": "市場価格",
            "psaGrading": "PSA グレーディング",
            "marketplace": "マーケットプレイス",
            "gradingDesc": "プロによる代行グレーディングサービス",
            "marketplaceDesc2": "安全な取引プラットフォーム",
            "realtimeDataTitle": "リアルタイムデータ",
            "realtimeDataDesc": "12時間ごとに自動更新、SNKRDUNKとグローバル市場の実際の取引記録を統合。",
            "safeTrading": "安全な取引",
            "safeTradingDesc": "マーケットプレイスはStripe決済保護を使用し、買い手と売り手の両方がプラットフォームの規約で保護されています。",
            "playerCommunity": "プレイヤーコミュニティ",
            "playerCommunityDesc": "TCG愛好家のための専用プラットフォーム、カードのトレンドを追跡し、コレクションの楽しさを共有。",
            "aboutBoxium": "BOXIUMについて",
            "aboutBoxiumDesc": "BOXIUMはTCGカード愛好家のために構築された総合プラットフォームで、グローバル市場データを統合し、リアルタイムで正確なカード価格情報と安全な中古取引マーケットプレイスを提供します。",
            "ourStory": "私たちのストーリー",
            "ourStoryDesc1": "BOXIUMは、カード市場情報が分散していて価格を追跡しにくいという悩みを理解したTCGプレイヤーのグループによって設立されました。SNKRDUNKなどのグローバル取引プラットフォームからの実際の取引データを統合することに専念し、すべてのプレイヤーが市場動向を簡単に把握できるようにしています。",
            "ourStoryDesc2": "ポケモンからワンピース、遊戯王まで、複数の主流TCGをカバーし、コレクターや投資家に最も信頼性の高い参考情報を提供するためにデータソースを継続的に拡大しています。",
            "contactUs": "お問い合わせ",
            "contactUsDesc": "ご質問やご提案がございましたら、お気軽にご連絡ください。",
            "contact": "連絡",
            "learnMoreAboutBoxium": "BOXIUMについてもっと知る",
            "usdPrice": "米ドル価格",
            "cardImageAlt": "カード画像",
        },
        "contact": {
            "title": "お問い合わせ",
            "subtitle": "ご質問やご提案がございましたら、お気軽にご連絡ください",
            "name": "お名前",
            "namePlaceholder": "お名前を入力してください",
            "email": "メールアドレス",
            "emailPlaceholder": "メールアドレスを入力してください",
            "subject": "件名",
            "subjectPlaceholder": "件名を入力してください",
            "message": "メッセージ",
            "messagePlaceholder": "メッセージを入力してください",
            "send": "送信",
            "sending": "送信中...",
            "successTitle": "送信完了",
            "successDesc": "お問い合わせありがとうございます。できるだけ早くご返信いたします。",
            "errorTitle": "送信失敗",
            "errorDesc": "後でもう一度お試しいただくか、直接メールをお送りください。",
            "required": "必須",
            "followUs": "フォローする",
            "emailUs": "メール",
            "faq": "よくある質問",
            "faqDesc": "よくある質問を見る",
        },
        "seller": {
            "dashboard": "セラーダッシュボード",
            "totalRevenue": "総収益",
            "totalOrders": "総注文数",
            "pendingOrders": "保留中の注文",
            "activeListings": "出品中の商品",
            "recentOrders": "最近の注文",
            "myListings": "私の出品",
            "addListing": "出品を追加",
            "editListing": "出品を編集",
            "deleteListing": "出品を削除",
            "delistItem": "出品を取り下げ",
            "relistItem": "再出品",
            "uploadImage": "画像をアップロード",
            "uploadImageDesc": "ここをクリックまたは画像をドラッグしてアップロード",
            "imageFormats": "JPG、PNG、WebP形式に対応",
            "maxFileSize": "最大ファイルサイズ：5MB",
            "noListings": "出品なし",
            "noListingsDesc": "「出品を追加」をクリックしてカードの出品を開始",
            "orderStatus": "注文ステータス",
            "statusPending": "支払い待ち",
            "statusPaid": "支払い済み",
            "statusShipped": "発送済み",
            "statusDelivered": "配達済み",
            "statusCancelled": "キャンセル済み",
            "statusRefunded": "返金済み",
            "statusCompleted": "完了",
            "markAsShipped": "発送済みとしてマーク",
            "trackingNumber": "追跡番号",
            "enterTrackingNumber": "追跡番号を入力",
            "confirmShipment": "発送を確認",
            "buyerInfo": "購入者情報",
            "shippingAddress": "配送先住所",
            "orderTotal": "注文合計",
            "platformFee": "プラットフォーム手数料",
            "netRevenue": "純収益",
            "selectAll": "すべて選択",
            "bulkDelist": "一括取り下げ",
            "bulkActions": "一括操作",
            "listingTitle": "出品タイトル",
            "listingPrice": "価格",
            "listingCondition": "状態",
            "listingQuantity": "数量",
            "listingDescription": "説明",
            "listingImages": "画像",
            "saveChanges": "変更を保存",
            "cancelEdit": "編集をキャンセル",
            "confirmDelete": "削除を確認",
            "confirmDeleteDesc": "この出品を削除してもよろしいですか？この操作は元に戻せません。",
            "applyToSell": "セラー申請",
            "pendingApproval": "審査中",
            "approved": "承認済み",
            "rejected": "拒否",
        },
        "orders": {
            "title": "注文一覧",
            "allOrders": "すべての注文",
            "noOrders": "注文なし",
            "noOrdersDesc": "まだ注文記録がありません",
            "orderNumber": "注文番号",
            "orderDate": "注文日",
            "orderStatus": "注文ステータス",
            "orderTotal": "注文合計",
            "viewDetail": "詳細を見る",
            "statusPending": "支払い待ち",
            "statusPaid": "支払い済み",
            "statusShipped": "発送済み",
            "statusDelivered": "配達済み",
            "statusCancelled": "キャンセル済み",
            "statusRefunded": "返金済み",
            "statusCompleted": "完了",
            "buyerOrders": "購入者の注文",
            "sellerOrders": "販売者の注文",
            "payNow": "今すぐ支払う",
            "cancelOrder": "注文をキャンセル",
            "confirmCancel": "キャンセルを確認",
            "confirmCancelDesc": "この注文をキャンセルしてもよろしいですか？",
        },
        "cart": {
            "title": "ショッピングカート",
            "empty": "カートは空です",
            "emptyDesc": "マーケットプレイスでカードを探す",
            "goToMarketplace": "マーケットプレイスへ",
            "removeItem": "商品を削除",
            "quantity": "数量",
            "subtotal": "小計",
            "total": "合計",
            "checkout": "チェックアウト",
            "continueShopping": "買い物を続ける",
            "itemCount": "点",
            "shippingFee": "送料",
            "freeShipping": "送料無料",
            "proceedToCheckout": "チェックアウトへ進む",
            "clearCart": "カートを空にする",
            "confirmClear": "空にすることを確認",
            "confirmClearDesc": "カートを空にしてもよろしいですか？",
        },
    },
}


def deep_merge(base, updates, path=""):
    """Merge updates into base dict recursively, only adding missing keys."""
    added = 0
    for key, value in updates.items():
        current_path = f"{path}.{key}" if path else key
        if key in base and isinstance(base[key], dict) and isinstance(value, dict):
            added += deep_merge(base[key], value, current_path)
        elif key not in base:
            base[key] = value
            print(f"  + {current_path} = {str(value)[:60]!r}")
            added += 1
        # else: skip existing keys
    return added


total_added = 0
for lang, updates in NEW_KEYS.items():
    path = f"{LOCALES_DIR}/{lang}.json"
    print(f"\n{'='*50}")
    print(f"Processing {lang}.json...")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    added = deep_merge(data, updates)
    total_added += added
    
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"  => Added {added} new keys to {lang}.json")

print(f"\n{'='*50}")
print(f"Total: Added {total_added} keys across all locale files")
