#!/usr/bin/env python3
"""Add missing cart i18n keys to all locale files."""
import json
import os

BASE = "/home/ubuntu/boxium-ptcg/client/src/locales"

new_keys = {
    "zh-TW": {
        "cart": {
            "removedUnavailable": "已移除 {{count}} 件無效商品",
            "removalFailed": "移除失敗，請重試",
            "paymentSuccess": "付款成功！",
            "stripePaymentConfirmed": "Stripe 信用卡付款已確認",
            "ordersCreated": "已建立 {{count}} 個訂單：",
            "orderNo": "訂單編號",
            "waitingShipment": "等待出貨",
            "viewOrderStatus": "查看訂單狀態",
            "sellerWillShip": "賣家將於確認後安排出貨，你可在訂單詳情頁查看物流追蹤號碼。",
            "orderCreatedGoToOrders": "訂單已建立，請前往「我的訂單」查看詳情",
            "goToOrders": "前往我的訂單",
            "continueShopping": "繼續購物",
            "backToMarketplace": "返回市集",
            "itemCount": "件商品",
            "empty": {
                "title": "購物車是空的",
                "message": "去市集逛逛，找到喜歡的卡牌加入購物車吧！",
                "goToMarketplace": "前往市集"
            },
            "unavailableWarning": "{{count}} 件商品已下架或售出，請移除後再結算",
            "clearUnavailable": "一鍵清理",
            "availableItems": "可購買商品（{{count}}）",
            "clearCart": "清空購物車",
            "soonExpiring": "{{count}} 件商品即將到期：",
            "daysLeft": "剩餘 {{count}} 天",
            "auctionWon": "拍賣得標待付款（{{count}}）",
            "payInTime": "請在時限內完成付款",
            "unavailableItems": "已下架商品（{{count}}）",
            "orderInfo": "訂單資訊",
            "marketplaceItems": "市集商品（{{count}} 件）",
            "auctionWonItems": "拍賣得標（{{count}} 件）",
            "checkout": "前往結算",
            "unavailableExcluded": "已下架商品不會納入結算",
            "paymentTimeLeft": "付款時限剩餘",
            "paymentExpired": "付款時限已到，訂單即將自動取消",
            "auctionWonBadge": "拍賣得標",
            "orderLabel": "訂單",
            "alipayHK": "支付寶 HK",
            "alipayHKPayment": "支付寶 HK 付款",
            "alipayHKScanAndUpload": "掃描 QR code 付款，付款後請截圖上傳付款證明",
            "goToOrderUploadProof": "前往訂單上傳付款證明",
            "offerAccepted": "賣家已接受你的出價！請在 <1>{{timeLeft}}</1> 內完成付款",
            "offerExpiredOriginalPrice": "出價已過期，將以原價 HK${{price}} 購買",
            "pendingPayment": "待付款",
            "loginPrompt": {
                "browseMarketplace": "繼續瀏覽市集"
            },
            "summary": "訂單摘要",
            "back": "返回",
            "offerPrice": "出價價",
            "paymentMethod": "付款方式",
            "sellerItemsAlipayRestriction": "購物車包含個人賣家商品，僅支援信用卡付款。支付寶 HK 僅適用於全部為本公司自營商品的訂單。",
            "alipayHKSellerRestriction": "包含個人賣家商品，不可使用此付款方式",
            "alipayHKScanQR": "掃描二維碼完成付款",
            "creditCard": "信用卡",
            "creditCardDesc": "支援 Visa、Mastercard 等主要信用卡",
            "stripeMultiOrderHint": "將為 {{marketItems}} 件市集商品及 {{auctionItems}} 件拍賣得標建立訂單，並合併為一筆 HK${{total}} 的 Stripe 付款，一次完成所有訂單的支付。",
            "alipayMultiOrderHint": "將為 {{count}} 件商品建立 {{count}} 個訂單，確認後顯示支付寶 HK 收款 QR 碼，掃碼支付合計 HK${{total}}，完成後上傳截圖確認。",
            "agreeTermsPart1": "我已閱讀並同意平台的",
            "termsLink": "買賣條款",
            "agreeTermsPart2": "，包括退款政策（收貨後 48 小時內申請）及平台規則。",
            "creatingOrders": "正在建立訂單...",
            "totalPayment": "合計付款金額",
            "totalWithShipping": "合計（含運費）",
            "totalExcludingShipping": "合計（不含運費）",
            "validatingStock": "驗證庫存中...",
            "creatingProgress": "建立中 {{done}}/{{total}}...",
            "confirmCheckoutMultiple": "確認結算（{{count}} 件）",
            "confirmCheckout": "確認結算",
            "backConfirm": {
                "title": "返回上一步？",
                "message": "已填寫的送貨資料將不會保留，確定要返回送貨方式選擇頁面嗎？",
                "continueFilling": "繼續填寫",
                "confirm": "確定返回"
            },
            "nextStepAddress": "下一步：填寫地址",
            "nextStepPayment": "下一步：確認付款",
            "stripeRedirecting": "已建立 {{count}} 個訂單，正在跳轉至 Stripe 付款頁面...",
            "shipping": {
                "selectHint": "請選擇送貨方式，然後在下一步填寫送貨地址。",
                "sfExpress": "順豐速運",
                "sfCOD": "運費到付",
                "sfDesc": "運費由順豐速運收取，取件時支付，金額視重量及地址而定",
                "hkPost": "香港郵政（平郵）",
                "hkPostDesc": "本地平郵寄送，運費 HK$10 將自動計入訂單總額",
                "sfExpressDisplay": "順豐速運（運費到付）",
                "hkPostDisplay": "香港郵政（平郵）",
                "sfPoint": "順豐點",
                "sfPickup": "順豐自提",
                "hkPostFee": "香港郵政運費",
                "sfTermsTitle": "順豐速運條款",
                "hkPostTitle": "香港郵政 - 平郵",
                "hkPostFeeDesc": "運費 HK$10 將自動加入訂單總額，以平郵方式寄出。"
            },
            "address": {
                "savedAddresses": "已儲存地址",
                "defaultBadge": "預設",
                "noSavedAddresses": "尚未儲存地址",
                "manualEntry": "手動填寫其他地址",
                "goToProfile": "前往個人中心新增地址",
                "recipientName": "收件人姓名",
                "recipientNamePlaceholder": "收件人全名",
                "phone": "聯絡電話",
                "deliveryMode": "收件地址方式",
                "sfStation": "順豐點 / 智能櫃",
                "manualInput": "手動輸入地址",
                "sfDistrict": "順豐地區",
                "selectDistrict": "選擇地區",
                "stations": "個",
                "selectSfStation": "選擇順豐點 / 智能櫃",
                "detailedAddress": "詳細地址",
                "addressPlaceholder": "例：新界東涌達東路1號東薈城2樓201室",
                "sfDoorDeliveryHint": "順豐上門派送，請填寫完整地址（包括大廈名稱、樓層及室號）",
                "deliveryAddress": "送貨地址",
                "fullAddressHint": "請填寫完整地址（包括大廈名稱、樓層及室號）",
                "address": "地址"
            },
            "alipay": {
                "orderCreatedPayNow": "訂單已建立，請完成支付寶 HK 付款",
                "scanQRInstruction": "請用 AlipayHK App 掃描以下 QR 碼付款",
                "openOnPhone": "在手機上開啟支付寶 HK",
                "paymentRefNote": "付款備注請填寫訂單編號：",
                "andMoreOrders": "等 {{count}} 個訂單",
                "copiedOrderNo": "訂單編號已複製！請貼上到支付寶備注欄位",
                "mustFillRef": "請務必在支付寶備注欄填寫以上編號，方便核對付款",
                "afterPaymentHint": "完成支付寶 HK 付款後，請點擊下方按鈕進入下一步上傳截圖。管理員審核後訂單即生效。",
                "doneUploadScreenshot": "我已完成付款 → 上傳截圖",
                "confirmOrderNoFilled": "訂單編號（請確認已在備注填寫）："
            },
            "proof": {
                "invalidFormat": "請上傳圖片格式的截圖（JPG、PNG 等）",
                "tooLarge": "截圖大小不能超過 10MB",
                "uploaded": "截圖已成功上傳！",
                "reviewTime": "管理員將在 1 個工作天內審核你的付款截圖，審核通過後訂單即生效。",
                "pendingReview": "訂單已建立，截圖待審核",
                "checkOrderStatus": "你可以在「我的訂單」頁面查看訂單狀態。",
                "uploadTitle": "上傳支付寶 HK 付款截圖",
                "uploadDesc": "請上傳支付寶 HK 付款成功的截圖，截圖需清晰顯示：",
                "recipient": "收款方：零度有限公司",
                "amount": "付款金額",
                "status": "付款狀態：成功",
                "previewAlt": "付款截圖預覽",
                "clickToReplace": "點擊更換截圖",
                "clickToUpload": "點擊上傳付款截圖",
                "supportedFormats": "支援 JPG、PNG，最大 10MB",
                "selected": "已選擇：{{name}}（{{size}} KB）"
            },
            "checkoutDialog": {
                "title": "結算",
                "step1": "送貨方式",
                "step2": "送貨地址",
                "step3": "確認付款",
                "step4": "掃碼付款",
                "step5": "上傳截圖"
            }
        }
    },
    "en": {
        "cart": {
            "removedUnavailable": "Removed {{count}} unavailable item(s)",
            "removalFailed": "Removal failed, please try again",
            "paymentSuccess": "Payment Successful!",
            "stripePaymentConfirmed": "Stripe credit card payment confirmed",
            "ordersCreated": "{{count}} order(s) created:",
            "orderNo": "Order No.",
            "waitingShipment": "Awaiting Shipment",
            "viewOrderStatus": "View Order Status",
            "sellerWillShip": "Seller will arrange shipment after confirmation. You can track the shipment on the order details page.",
            "orderCreatedGoToOrders": "Order created. Please go to \"My Orders\" to view details.",
            "goToOrders": "Go to My Orders",
            "continueShopping": "Continue Shopping",
            "backToMarketplace": "Back to Marketplace",
            "itemCount": "item(s)",
            "empty": {
                "title": "Your cart is empty",
                "message": "Browse the marketplace and add your favorite cards to cart!",
                "goToMarketplace": "Go to Marketplace"
            },
            "unavailableWarning": "{{count}} item(s) are no longer available. Please remove them before checkout.",
            "clearUnavailable": "Clear Unavailable",
            "availableItems": "Available Items ({{count}})",
            "clearCart": "Clear Cart",
            "soonExpiring": "{{count}} item(s) expiring soon:",
            "daysLeft": "{{count}} day(s) left",
            "auctionWon": "Auction Won - Pending Payment ({{count}})",
            "payInTime": "Please complete payment within the time limit",
            "unavailableItems": "Unavailable Items ({{count}})",
            "orderInfo": "Order Summary",
            "marketplaceItems": "Marketplace Items ({{count}})",
            "auctionWonItems": "Auction Won ({{count}})",
            "checkout": "Proceed to Checkout",
            "unavailableExcluded": "Unavailable items will not be included in checkout",
            "paymentTimeLeft": "Payment time remaining",
            "paymentExpired": "Payment time expired. Order will be automatically cancelled.",
            "auctionWonBadge": "Auction Won",
            "orderLabel": "Order",
            "alipayHK": "AlipayHK",
            "alipayHKPayment": "AlipayHK Payment",
            "alipayHKScanAndUpload": "Scan QR code to pay, then upload payment screenshot",
            "goToOrderUploadProof": "Go to order to upload payment proof",
            "offerAccepted": "Seller accepted your offer! Please complete payment within {{timeLeft}}",
            "offerExpiredOriginalPrice": "Offer expired. Will purchase at original price HK${{price}}",
            "pendingPayment": "Pending Payment",
            "loginPrompt": {
                "browseMarketplace": "Continue browsing marketplace"
            },
            "summary": "Order Summary",
            "back": "Back",
            "offerPrice": "Offer Price",
            "paymentMethod": "Payment Method",
            "sellerItemsAlipayRestriction": "Cart contains individual seller items. Only credit card payment is supported. AlipayHK is only available for orders with all company-owned items.",
            "alipayHKSellerRestriction": "Contains individual seller items, this payment method is unavailable",
            "alipayHKScanQR": "Scan QR code to complete payment",
            "creditCard": "Credit Card",
            "creditCardDesc": "Supports Visa, Mastercard and other major credit cards",
            "stripeMultiOrderHint": "Will create orders for {{marketItems}} marketplace items and {{auctionItems}} auction wins, merged into a single Stripe payment of HK${{total}}.",
            "alipayMultiOrderHint": "Will create {{count}} orders for {{count}} items. After confirmation, AlipayHK QR code will be shown. Scan to pay HK${{total}} total, then upload screenshot.",
            "agreeTermsPart1": "I have read and agree to the platform's",
            "termsLink": "Terms & Conditions",
            "agreeTermsPart2": ", including refund policy (apply within 48 hours of receipt) and platform rules.",
            "creatingOrders": "Creating orders...",
            "totalPayment": "Total Payment",
            "totalWithShipping": "Total (incl. shipping)",
            "totalExcludingShipping": "Total (excl. shipping)",
            "validatingStock": "Validating stock...",
            "creatingProgress": "Creating {{done}}/{{total}}...",
            "confirmCheckoutMultiple": "Confirm Checkout ({{count}} items)",
            "confirmCheckout": "Confirm Checkout",
            "backConfirm": {
                "title": "Go back?",
                "message": "Filled shipping information will not be saved. Are you sure you want to go back to shipping method selection?",
                "continueFilling": "Continue Filling",
                "confirm": "Confirm"
            },
            "nextStepAddress": "Next: Enter Address",
            "nextStepPayment": "Next: Confirm Payment",
            "stripeRedirecting": "{{count}} order(s) created. Redirecting to Stripe payment page...",
            "shipping": {
                "selectHint": "Please select a shipping method, then fill in the delivery address in the next step.",
                "sfExpress": "SF Express",
                "sfCOD": "Freight Collect",
                "sfDesc": "Shipping fee collected by SF Express upon pickup, based on weight and address",
                "hkPost": "HK Post (Surface Mail)",
                "hkPostDesc": "Local surface mail, HK$10 shipping fee will be added to order total",
                "sfExpressDisplay": "SF Express (Freight Collect)",
                "hkPostDisplay": "HK Post (Surface Mail)",
                "sfPoint": "SF Station",
                "sfPickup": "SF Pickup",
                "hkPostFee": "HK Post Shipping Fee",
                "sfTermsTitle": "SF Express Terms",
                "hkPostTitle": "HK Post - Surface Mail",
                "hkPostFeeDesc": "HK$10 shipping fee will be automatically added to order total, shipped by surface mail."
            },
            "address": {
                "savedAddresses": "Saved Addresses",
                "defaultBadge": "Default",
                "noSavedAddresses": "No saved addresses",
                "manualEntry": "Enter another address manually",
                "goToProfile": "Go to profile to add address",
                "recipientName": "Recipient Name",
                "recipientNamePlaceholder": "Full name",
                "phone": "Contact Phone",
                "deliveryMode": "Delivery Mode",
                "sfStation": "SF Station / Locker",
                "manualInput": "Enter address manually",
                "sfDistrict": "SF District",
                "selectDistrict": "Select district",
                "stations": "station(s)",
                "selectSfStation": "Select SF Station / Locker",
                "detailedAddress": "Detailed Address",
                "addressPlaceholder": "e.g. Room 201, 2/F, Citygate Outlets, 1 Lantau Outlet Drive, Tung Chung, NT",
                "sfDoorDeliveryHint": "SF door-to-door delivery. Please provide complete address including building name, floor and room number.",
                "deliveryAddress": "Delivery Address",
                "fullAddressHint": "Please provide complete address including building name, floor and room number.",
                "address": "Address"
            },
            "alipay": {
                "orderCreatedPayNow": "Order created. Please complete AlipayHK payment.",
                "scanQRInstruction": "Please scan the QR code below with AlipayHK App to pay",
                "openOnPhone": "Open AlipayHK on mobile",
                "paymentRefNote": "Please fill in order number in payment remarks:",
                "andMoreOrders": "and {{count}} more orders",
                "copiedOrderNo": "Order number copied! Please paste into AlipayHK remarks field.",
                "mustFillRef": "Please fill in the order number in AlipayHK remarks for payment verification.",
                "afterPaymentHint": "After completing AlipayHK payment, click the button below to upload screenshot. Order will be activated after admin review.",
                "doneUploadScreenshot": "Payment Done → Upload Screenshot",
                "confirmOrderNoFilled": "Order No. (please confirm it's filled in remarks):"
            },
            "proof": {
                "invalidFormat": "Please upload an image file (JPG, PNG, etc.)",
                "tooLarge": "Screenshot size cannot exceed 10MB",
                "uploaded": "Screenshot uploaded successfully!",
                "reviewTime": "Admin will review your payment screenshot within 1 business day. Order will be activated after approval.",
                "pendingReview": "Order created, screenshot pending review",
                "checkOrderStatus": "You can check order status on the \"My Orders\" page.",
                "uploadTitle": "Upload AlipayHK Payment Screenshot",
                "uploadDesc": "Please upload a screenshot of successful AlipayHK payment. The screenshot must clearly show:",
                "recipient": "Payee: Ling Do Limited",
                "amount": "Payment Amount",
                "status": "Payment Status: Success",
                "previewAlt": "Payment screenshot preview",
                "clickToReplace": "Click to replace screenshot",
                "clickToUpload": "Click to upload payment screenshot",
                "supportedFormats": "Supports JPG, PNG, max 10MB",
                "selected": "Selected: {{name}} ({{size}} KB)"
            },
            "checkoutDialog": {
                "title": "Checkout",
                "step1": "Shipping",
                "step2": "Address",
                "step3": "Payment",
                "step4": "Scan QR",
                "step5": "Upload Proof"
            }
        }
    },
    "ja": {
        "cart": {
            "removedUnavailable": "{{count}}件の無効な商品を削除しました",
            "removalFailed": "削除に失敗しました。再試行してください",
            "paymentSuccess": "お支払い完了！",
            "stripePaymentConfirmed": "Stripeクレジットカード決済が確認されました",
            "ordersCreated": "{{count}}件の注文が作成されました：",
            "orderNo": "注文番号",
            "waitingShipment": "発送待ち",
            "viewOrderStatus": "注文状況を確認",
            "sellerWillShip": "出品者は確認後に発送手配します。注文詳細ページで配送追跡番号を確認できます。",
            "orderCreatedGoToOrders": "注文が作成されました。「マイオーダー」で詳細を確認してください",
            "goToOrders": "マイオーダーへ",
            "continueShopping": "買い物を続ける",
            "backToMarketplace": "マーケットプレイスに戻る",
            "itemCount": "件",
            "empty": {
                "title": "カートは空です",
                "message": "マーケットプレイスでお気に入りのカードをカートに追加しましょう！",
                "goToMarketplace": "マーケットプレイスへ"
            },
            "unavailableWarning": "{{count}}件の商品が利用不可になりました。削除してからチェックアウトしてください。",
            "clearUnavailable": "無効商品を削除",
            "availableItems": "購入可能商品（{{count}}件）",
            "clearCart": "カートを空にする",
            "soonExpiring": "{{count}}件の商品が間もなく期限切れ：",
            "daysLeft": "残り{{count}}日",
            "auctionWon": "落札済み・支払い待ち（{{count}}件）",
            "payInTime": "期限内にお支払いを完了してください",
            "unavailableItems": "利用不可商品（{{count}}件）",
            "orderInfo": "注文情報",
            "marketplaceItems": "マーケット商品（{{count}}件）",
            "auctionWonItems": "落札商品（{{count}}件）",
            "checkout": "チェックアウトへ",
            "unavailableExcluded": "利用不可商品はチェックアウトに含まれません",
            "paymentTimeLeft": "支払い期限まで",
            "paymentExpired": "支払い期限が切れました。注文は自動的にキャンセルされます。",
            "auctionWonBadge": "落札",
            "orderLabel": "注文",
            "alipayHK": "AlipayHK",
            "alipayHKPayment": "AlipayHK決済",
            "alipayHKScanAndUpload": "QRコードをスキャンして支払い、完了後スクリーンショットをアップロード",
            "goToOrderUploadProof": "注文ページで支払い証明をアップロード",
            "offerAccepted": "出品者があなたのオファーを承認しました！{{timeLeft}}以内にお支払いください",
            "offerExpiredOriginalPrice": "オファーが期限切れ。元の価格 HK${{price}} で購入します",
            "pendingPayment": "支払い待ち",
            "loginPrompt": {
                "browseMarketplace": "マーケットプレイスを閲覧する"
            },
            "summary": "注文概要",
            "back": "戻る",
            "offerPrice": "オファー価格",
            "paymentMethod": "お支払い方法",
            "sellerItemsAlipayRestriction": "カートに個人出品者の商品が含まれています。クレジットカード払いのみ対応。AlipayHKは自社商品のみの注文に使用できます。",
            "alipayHKSellerRestriction": "個人出品者の商品が含まれているため、この支払い方法は使用できません",
            "alipayHKScanQR": "QRコードをスキャンして支払いを完了",
            "creditCard": "クレジットカード",
            "creditCardDesc": "Visa、Mastercardなど主要クレジットカードに対応",
            "stripeMultiOrderHint": "{{marketItems}}件のマーケット商品と{{auctionItems}}件の落札商品の注文を作成し、HK${{total}}のStripe決済にまとめます。",
            "alipayMultiOrderHint": "{{count}}件の商品に対して{{count}}件の注文を作成します。確認後、AlipayHK QRコードが表示されます。合計HK${{total}}をスキャンして支払い、スクリーンショットをアップロードしてください。",
            "agreeTermsPart1": "プラットフォームの",
            "termsLink": "売買規約",
            "agreeTermsPart2": "（受取後48時間以内の返金申請を含む）を読み、同意します。",
            "creatingOrders": "注文を作成中...",
            "totalPayment": "合計支払い金額",
            "totalWithShipping": "合計（送料込み）",
            "totalExcludingShipping": "合計（送料別）",
            "validatingStock": "在庫確認中...",
            "creatingProgress": "作成中 {{done}}/{{total}}...",
            "confirmCheckoutMultiple": "チェックアウト確認（{{count}}件）",
            "confirmCheckout": "チェックアウト確認",
            "backConfirm": {
                "title": "前のステップに戻りますか？",
                "message": "入力した配送情報は保存されません。配送方法選択ページに戻りますか？",
                "continueFilling": "入力を続ける",
                "confirm": "戻る"
            },
            "nextStepAddress": "次へ：住所入力",
            "nextStepPayment": "次へ：支払い確認",
            "stripeRedirecting": "{{count}}件の注文を作成しました。Stripe決済ページへリダイレクト中...",
            "shipping": {
                "selectHint": "配送方法を選択し、次のステップで配送先住所を入力してください。",
                "sfExpress": "順豊速運",
                "sfCOD": "着払い",
                "sfDesc": "送料は受取時に順豊速運へ支払い。重量と住所により異なります",
                "hkPost": "香港郵政（普通郵便）",
                "hkPostDesc": "ローカル普通郵便、HK$10の送料が注文合計に自動追加されます",
                "sfExpressDisplay": "順豊速運（着払い）",
                "hkPostDisplay": "香港郵政（普通郵便）",
                "sfPoint": "順豊ステーション",
                "sfPickup": "順豊受取",
                "hkPostFee": "香港郵政送料",
                "sfTermsTitle": "順豊速運規約",
                "hkPostTitle": "香港郵政 - 普通郵便",
                "hkPostFeeDesc": "HK$10の送料が注文合計に自動追加され、普通郵便で発送されます。"
            },
            "address": {
                "savedAddresses": "保存済み住所",
                "defaultBadge": "デフォルト",
                "noSavedAddresses": "保存済み住所なし",
                "manualEntry": "他の住所を手動入力",
                "goToProfile": "プロフィールで住所を追加",
                "recipientName": "受取人名",
                "recipientNamePlaceholder": "フルネーム",
                "phone": "連絡先電話番号",
                "deliveryMode": "配送方法",
                "sfStation": "順豊ステーション / ロッカー",
                "manualInput": "住所を手動入力",
                "sfDistrict": "順豊エリア",
                "selectDistrict": "エリアを選択",
                "stations": "件",
                "selectSfStation": "順豊ステーション / ロッカーを選択",
                "detailedAddress": "詳細住所",
                "addressPlaceholder": "例：東涌達東路1号東薈城2楼201室",
                "sfDoorDeliveryHint": "順豊宅配便。建物名、階数、部屋番号を含む完全な住所を入力してください。",
                "deliveryAddress": "配送先住所",
                "fullAddressHint": "建物名、階数、部屋番号を含む完全な住所を入力してください。",
                "address": "住所"
            },
            "alipay": {
                "orderCreatedPayNow": "注文が作成されました。AlipayHKで支払いを完了してください",
                "scanQRInstruction": "AlipayHKアプリで下のQRコードをスキャンして支払い",
                "openOnPhone": "スマートフォンでAlipayHKを開く",
                "paymentRefNote": "支払い備考に注文番号を記入してください：",
                "andMoreOrders": "他{{count}}件の注文",
                "copiedOrderNo": "注文番号をコピーしました！AlipayHKの備考欄に貼り付けてください。",
                "mustFillRef": "支払い確認のため、AlipayHKの備考欄に注文番号を必ず記入してください。",
                "afterPaymentHint": "AlipayHKでの支払い完了後、下のボタンをクリックしてスクリーンショットをアップロードしてください。管理者の確認後に注文が有効になります。",
                "doneUploadScreenshot": "支払い完了 → スクリーンショットをアップロード",
                "confirmOrderNoFilled": "注文番号（備考に記入済みか確認）："
            },
            "proof": {
                "invalidFormat": "画像ファイル（JPG、PNGなど）をアップロードしてください",
                "tooLarge": "スクリーンショットのサイズは10MB以下にしてください",
                "uploaded": "スクリーンショットのアップロードに成功しました！",
                "reviewTime": "管理者が1営業日以内に支払いスクリーンショットを確認します。承認後に注文が有効になります。",
                "pendingReview": "注文作成済み、スクリーンショット確認待ち",
                "checkOrderStatus": "「マイオーダー」ページで注文状況を確認できます。",
                "uploadTitle": "AlipayHK支払いスクリーンショットをアップロード",
                "uploadDesc": "AlipayHK支払い成功のスクリーンショットをアップロードしてください。以下が明確に表示されている必要があります：",
                "recipient": "受取人：零度有限公司",
                "amount": "支払い金額",
                "status": "支払い状況：成功",
                "previewAlt": "支払いスクリーンショットプレビュー",
                "clickToReplace": "クリックして交換",
                "clickToUpload": "クリックしてスクリーンショットをアップロード",
                "supportedFormats": "JPG、PNG対応、最大10MB",
                "selected": "選択済み：{{name}}（{{size}} KB）"
            },
            "checkoutDialog": {
                "title": "チェックアウト",
                "step1": "配送方法",
                "step2": "配送先",
                "step3": "支払い確認",
                "step4": "QRスキャン",
                "step5": "証明書アップロード"
            }
        }
    }
}

def deep_merge(base, updates):
    """Deep merge updates into base dict."""
    for key, value in updates.items():
        if key in base and isinstance(base[key], dict) and isinstance(value, dict):
            deep_merge(base[key], value)
        else:
            base[key] = value

for lang, keys in new_keys.items():
    filepath = os.path.join(BASE, f"{lang}.json")
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    deep_merge(data, keys)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {filepath}")

print("Done!")
