import json

paths = {
    "zh-TW": "/home/ubuntu/boxium-ptcg/client/src/locales/zh-TW.json",
    "en": "/home/ubuntu/boxium-ptcg/client/src/locales/en.json",
    "ja": "/home/ubuntu/boxium-ptcg/client/src/locales/ja.json",
}

new_keys = {
    "zh-TW": {
        "reVerify": "重新核對",
        "cancelApplication": "取消申請",
        "confirmCancel": "確定要取消此申請？",
        "confirmCancelBtn": "確認取消",
        "selectPaymentMethod": "選擇付款方式",
        "scanQROrClickLink": "掃描 QR code 或點擊連結完成付款",
        "uploadScreenshotAfterPay": "付款後請上傳截圖，管理員確認後補付將完成。",
        "screenshotPreview": "截圖預覽",
        "submitFailed": "提交失敗",
        "resubmitScreenshot": "重新提交截圖",
        "sendCardsToAddress": "請將卡牌寄至以下地址",
        "trackingSubmittedLabel": "已提交追蹤號碼",
        "trackingPlaceholder": "輸入順豐追蹤號碼（如：SF1234567890HK）",
        "trackingSubmittedWaiting": "已提交順豐追蹤號碼，BOXIUM 正在等待收件",
        "autoUpdateReceived": "收件後將自動更新狀態為「已收件」。",
        "sfTrackingNumber": "順豐追蹤號碼",
        "batchInfo": "出團批次資訊",
        "batchName": "批次",
        "shippedDate": "出團日期",
        "expectedReturn": "預計回件",
        "screenshotRejectedReupload": "截圖審核未通過，請重新上傳",
        "rejectionReason": "拒絕原因",
        "upgradedPaySurcharge": "服務層級已升級，請補付差價",
        "upgradedToTier": "您的申請已升級至 {{tier}}，",
        "surchargeDiffAmount": "需補付差價 HK${{amount}}。",
        "newTotalFee": "新總費用",
        "selectSurchargeMethod": "選擇補付方式",
        "creditCardStripe": "信用卡 / Stripe",
        "alipayHK": "支付寶 HK",
        "creditCardSurcharge": "信用卡補付差價",
        "alipayHKSurcharge": "支付寶 HK 補付差價",
        "alipayHKSurchargeAmount": "支付寶 HK 補付差價 HK${{amount}}",
        "alipayHKPayment": "支付寶 HK 付款",
        "surchargeScreenshotSubmitted": "補付截圖已提交！",
        "adminConfirmSurchargeWithin24h": "管理員將於 24 小時內確認補付。",
        "aiVerifyPassed": "AI 核對通過",
        "aiVerifyWarning": "AI 核對小心",
        "aiVerifyFailed2": "AI 核對未通過",
        "aiVerifyingWait": "AI 核對中，請稍候…",
        "gradingCompletePayNow": "鑑定完成！請完成付款",
        "payBeforeDeadline": "請於 {{date}} 前完成付款，逾期平台保留取消訂單的權利",
        "creditDebitCard": "信用卡 / 扣帳卡",
        "amountDue": "應付金額",
        "scanAlipayQR": "掃描支付寶 HK QR Code 付款",
        "orClickLinkToPay": "或點擊連結付款：",
        "paymentAmount": "付款金額",
        "remarkFillOrderNo": "備注請填寫申請單號：{{orderNo}}",
        "aiAutoVerify": "AI 自動核對",
        "uploadAlipayScreenshot": "完成付款後，請上傳支付寶 HK 付款成功截圖。系統將自動使用 AI 核對金額和單號。",
        "aiVerifying": "AI 核對中...",
        "aiAnalyzing": "正在分析截圖內容，核對金額和單號",
        "screenshotSubmittedSuccess": "截圖已提交！",
        "adminWillConfirmOrder": "管理員確認收款後，訂單將自動完成。如有查詢請聯絡 BOXIUM。",
        "surchargePaidWaitingReturn": "差價已確認，等待 BOXIUM 寄回",
        "surchargePaidReturnNote": "您的升級差價已確認收款，BOXIUM 正在安排將卡牌寄回至您的收貨地址。",
        "sfCOD": "順豐到付",
        "sfCODNote": "貨品將以順豐速遞到付方式寄回，請準備好運費。",
        "boxiumShipped": "BOXIUM 已寄出，追蹤號碼",
        "trackingNote": "您的卡牌已由 BOXIUM 寄出，請使用以下追蹤號碼查詢包裹狀態。",
        "trackingCopied": "追蹤號碼已複製",
        "sfQuery": "順豐查詢",
        "sfCODPickupNote": "順豐速遞到付，請準備好運費收取包裹。",
        "customerAddress": "客戶收貨地址",
        "afterGradingReturnNote": "鑑定完成後，BOXIUM 將把卡牌寄回此地址",
        "recipient": "收件人",
        "phone": "聯絡電話",
        "sfStation": "順豐站",
        "address": "地址",
        "cardListWithCount": "卡牌清單（{{count}} 張）",
        "initialFee": "初始代送費用",
        "paid": "已付",
        "upgradeSurcharge": "升級差價",
        "pendingPayment": "待補付",
        "totalPSAFee": "代送 PSA 費用合計",
        "boxiumNote": "BOXIUM 備注",
        "newTier": "新層級",
        "orderNo": "申請單號",
        "orderNoLabel": "單號",
        "amount": "金額",
        "canStillSubmitForManualReview": "如確認付款已完成，仍可提交截圖由管理員手動核對。",
    },
    "en": {
        "reVerify": "Re-verify",
        "cancelApplication": "Cancel Application",
        "confirmCancel": "Confirm cancel this application?",
        "confirmCancelBtn": "Confirm Cancel",
        "selectPaymentMethod": "Select Payment Method",
        "scanQROrClickLink": "Scan QR code or click link to complete payment",
        "uploadScreenshotAfterPay": "After payment, upload screenshot. Admin will confirm surcharge.",
        "screenshotPreview": "Screenshot Preview",
        "submitFailed": "Submit Failed",
        "resubmitScreenshot": "Resubmit Screenshot",
        "sendCardsToAddress": "Please send cards to the following address",
        "trackingSubmittedLabel": "Tracking number submitted",
        "trackingPlaceholder": "Enter SF Express tracking number (e.g. SF1234567890HK)",
        "trackingSubmittedWaiting": "SF tracking number submitted, BOXIUM is waiting for receipt",
        "autoUpdateReceived": "Status will auto-update to 'Received' after receipt.",
        "sfTrackingNumber": "SF Tracking Number",
        "batchInfo": "Batch Information",
        "batchName": "Batch",
        "shippedDate": "Shipped Date",
        "expectedReturn": "Expected Return",
        "screenshotRejectedReupload": "Screenshot rejected, please re-upload",
        "rejectionReason": "Rejection Reason",
        "upgradedPaySurcharge": "Service tier upgraded, please pay surcharge",
        "upgradedToTier": "Your application has been upgraded to {{tier}},",
        "surchargeDiffAmount": "Surcharge: HK${{amount}}.",
        "newTotalFee": "New Total Fee",
        "selectSurchargeMethod": "Select Surcharge Method",
        "creditCardStripe": "Credit Card / Stripe",
        "alipayHK": "Alipay HK",
        "creditCardSurcharge": "Credit Card Surcharge",
        "alipayHKSurcharge": "Alipay HK Surcharge",
        "alipayHKSurchargeAmount": "Alipay HK Surcharge HK${{amount}}",
        "alipayHKPayment": "Alipay HK Payment",
        "surchargeScreenshotSubmitted": "Surcharge screenshot submitted!",
        "adminConfirmSurchargeWithin24h": "Admin will confirm surcharge within 24 hours.",
        "aiVerifyPassed": "AI Verify Passed",
        "aiVerifyWarning": "AI Verify Warning",
        "aiVerifyFailed2": "AI Verify Failed",
        "aiVerifyingWait": "AI verifying, please wait…",
        "gradingCompletePayNow": "Grading complete! Please complete payment",
        "payBeforeDeadline": "Please complete payment before {{date}}, or the order may be cancelled",
        "creditDebitCard": "Credit / Debit Card",
        "amountDue": "Amount Due",
        "scanAlipayQR": "Scan Alipay HK QR Code to pay",
        "orClickLinkToPay": "Or click link to pay:",
        "paymentAmount": "Payment Amount",
        "remarkFillOrderNo": "Remark: fill in order no: {{orderNo}}",
        "aiAutoVerify": "AI Auto Verify",
        "uploadAlipayScreenshot": "After payment, upload Alipay HK payment screenshot. AI will verify amount and order no.",
        "aiVerifying": "AI verifying...",
        "aiAnalyzing": "Analyzing screenshot, verifying amount and order no",
        "screenshotSubmittedSuccess": "Screenshot submitted!",
        "adminWillConfirmOrder": "Order will complete after admin confirms payment. Contact BOXIUM for queries.",
        "surchargePaidWaitingReturn": "Surcharge confirmed, waiting for BOXIUM to ship back",
        "surchargePaidReturnNote": "Your upgrade surcharge has been confirmed. BOXIUM is arranging to ship cards back to your address.",
        "sfCOD": "SF COD",
        "sfCODNote": "Cards will be shipped back via SF Express COD. Please prepare shipping fee.",
        "boxiumShipped": "BOXIUM has shipped, tracking no.",
        "trackingNote": "Your cards have been shipped by BOXIUM. Use the tracking number below to track.",
        "trackingCopied": "Tracking number copied",
        "sfQuery": "SF Track",
        "sfCODPickupNote": "SF Express COD, please prepare shipping fee to receive package.",
        "customerAddress": "Customer Delivery Address",
        "afterGradingReturnNote": "After grading, BOXIUM will ship cards back to this address",
        "recipient": "Recipient",
        "phone": "Phone",
        "sfStation": "SF Station",
        "address": "Address",
        "cardListWithCount": "Card List ({{count}})",
        "initialFee": "Initial Fee",
        "paid": "Paid",
        "upgradeSurcharge": "Upgrade Surcharge",
        "pendingPayment": "Pending",
        "totalPSAFee": "Total PSA Fee",
        "boxiumNote": "BOXIUM Note",
        "newTier": "New Tier",
        "orderNo": "Application No.",
        "orderNoLabel": "Order No.",
        "amount": "Amount",
        "canStillSubmitForManualReview": "If payment is confirmed, you can still submit screenshot for manual review.",
    },
    "ja": {
        "reVerify": "再確認",
        "cancelApplication": "申請をキャンセル",
        "confirmCancel": "この申請をキャンセルしますか？",
        "confirmCancelBtn": "キャンセル確認",
        "selectPaymentMethod": "支払い方法を選択",
        "scanQROrClickLink": "QRコードをスキャンまたはリンクをクリックして支払い完了",
        "uploadScreenshotAfterPay": "支払い後、スクリーンショットをアップロードしてください。管理者が確認します。",
        "screenshotPreview": "スクリーンショットプレビュー",
        "submitFailed": "送信失敗",
        "resubmitScreenshot": "スクリーンショットを再送信",
        "sendCardsToAddress": "以下の住所にカードを送付してください",
        "trackingSubmittedLabel": "追跡番号を送信済み",
        "trackingPlaceholder": "SF Express追跡番号を入力（例：SF1234567890HK）",
        "trackingSubmittedWaiting": "SF追跡番号を送信済み、BOXIUMが受取を待っています",
        "autoUpdateReceived": "受取後、ステータスが自動的に「受取済み」に更新されます。",
        "sfTrackingNumber": "SF追跡番号",
        "batchInfo": "バッチ情報",
        "batchName": "バッチ",
        "shippedDate": "発送日",
        "expectedReturn": "返却予定日",
        "screenshotRejectedReupload": "スクリーンショットが却下されました。再アップロードしてください",
        "rejectionReason": "却下理由",
        "upgradedPaySurcharge": "サービスランクがアップグレードされました。差額をお支払いください",
        "upgradedToTier": "申請が{{tier}}にアップグレードされました、",
        "surchargeDiffAmount": "差額：HK${{amount}}。",
        "newTotalFee": "新しい合計料金",
        "selectSurchargeMethod": "差額支払い方法を選択",
        "creditCardStripe": "クレジットカード / Stripe",
        "alipayHK": "Alipay HK",
        "creditCardSurcharge": "クレジットカードで差額支払い",
        "alipayHKSurcharge": "Alipay HKで差額支払い",
        "alipayHKSurchargeAmount": "Alipay HK差額 HK${{amount}}",
        "alipayHKPayment": "Alipay HK支払い",
        "surchargeScreenshotSubmitted": "差額スクリーンショットを送信しました！",
        "adminConfirmSurchargeWithin24h": "管理者が24時間以内に差額を確認します。",
        "aiVerifyPassed": "AI確認通過",
        "aiVerifyWarning": "AI確認警告",
        "aiVerifyFailed2": "AI確認失敗",
        "aiVerifyingWait": "AI確認中、しばらくお待ちください…",
        "gradingCompletePayNow": "鑑定完了！お支払いを完了してください",
        "payBeforeDeadline": "{{date}}までにお支払いください。期限超過の場合、注文がキャンセルされる場合があります",
        "creditDebitCard": "クレジット / デビットカード",
        "amountDue": "支払い金額",
        "scanAlipayQR": "Alipay HK QRコードをスキャンして支払い",
        "orClickLinkToPay": "またはリンクをクリックして支払い：",
        "paymentAmount": "支払い金額",
        "remarkFillOrderNo": "備考：申請番号を記入：{{orderNo}}",
        "aiAutoVerify": "AI自動確認",
        "uploadAlipayScreenshot": "支払い後、Alipay HK支払いスクリーンショットをアップロードしてください。AIが金額と注文番号を確認します。",
        "aiVerifying": "AI確認中...",
        "aiAnalyzing": "スクリーンショットを分析中、金額と注文番号を確認",
        "screenshotSubmittedSuccess": "スクリーンショットを送信しました！",
        "adminWillConfirmOrder": "管理者が入金確認後、注文が自動完了します。お問い合わせはBOXIUMまで。",
        "surchargePaidWaitingReturn": "差額確認済み、BOXIUMの返送を待っています",
        "surchargePaidReturnNote": "アップグレード差額が確認されました。BOXIUMがカードをご住所に返送する手配をしています。",
        "sfCOD": "SF着払い",
        "sfCODNote": "カードはSF Express着払いで返送されます。送料をご準備ください。",
        "boxiumShipped": "BOXIUMが発送済み、追跡番号",
        "trackingNote": "カードはBOXIUMから発送されました。以下の追跡番号でご確認ください。",
        "trackingCopied": "追跡番号をコピーしました",
        "sfQuery": "SF追跡",
        "sfCODPickupNote": "SF Express着払い、荷物受取の際は送料をご準備ください。",
        "customerAddress": "お客様の配送先住所",
        "afterGradingReturnNote": "鑑定後、BOXIUMがこの住所にカードを返送します",
        "recipient": "受取人",
        "phone": "電話番号",
        "sfStation": "SFステーション",
        "address": "住所",
        "cardListWithCount": "カードリスト（{{count}}枚）",
        "initialFee": "初期代行費用",
        "paid": "支払済み",
        "upgradeSurcharge": "アップグレード差額",
        "pendingPayment": "支払い待ち",
        "totalPSAFee": "PSA代行費用合計",
        "boxiumNote": "BOXIUM備考",
        "newTier": "新しいランク",
        "orderNo": "申請番号",
        "orderNoLabel": "注文番号",
        "amount": "金額",
        "canStillSubmitForManualReview": "支払い完了が確認できた場合、スクリーンショットを送信して手動確認を依頼できます。",
    }
}

for lang, path in paths.items():
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    
    if "grading" not in data:
        data["grading"] = {}
    
    keys = new_keys[lang]
    added = 0
    for key, val in keys.items():
        if key not in data["grading"]:
            data["grading"][key] = val
            added += 1
    
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"{lang}: added {added} keys to grading section")

print("Done!")
