#!/usr/bin/env python3
import json, os

BASE = "/home/ubuntu/boxium-ptcg/client/src/locales"

new_keys = {
    "zh-TW": {
        "cart.freightExtra": "運費到付",
        "cart.sfTerms1": "【如寄順豐自提網點可享運費優惠】請於下單時提供收件人名、電話，並選擇你的順豐網點。運費金額將自動根據貨件重量、材積、收件地址計算。運費由順豐速運收取，於取件時支付。運費詳情可參考<a href=\"https://htm.sf-express.com/hk/tc/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-[#06038D] underline\">順豐速運香港官方網站</a>。",
        "cart.sfTerms2": "【客戶須知】由於順豐已暫停經SMS短訊方式發送取件訊息，所有取件訊息已改為透過順豐香港官方手機應用程式「SFHK APP」推送，客戶請提前下載「SFHK APP」，並開啟手機推送通知，以免錯過貨件運送提醒，同時客戶可透過「SFHK APP」隨時查看快件的最新狀態。",
        "cart.createOrdersStripe": "，合並為一筆 HK${{total}} 的 Stripe 付款，一次完成所有訂單的支付。",
        "cart.createOrdersAlipay": "將為 {{count}} 件商品建立 {{count}} 個訂單，確認後顯示支付寶 HK 收款 QR 碼，掃碼支付合計 HK${{total}}，完成後上傳截圖確認。",
        "cart.selectedFile": "已選擇：{{name}}（{{size}} KB）",
        "cart.selectDistrict": "選擇地區",
        "cart.sfStationLabel": "順豐點 / 智能櫃 *",
        "cart.selectSfStation": "選擇順豐點 / 智能櫃",
        "cart.detailedAddress": "詳細地址 *",
        "cart.addressPlaceholder": "例：新界東涌達東路1號東薈城2樓201室",
        "cart.sfDeliveryAddressNote": "順豐上門派送，請填寫完整地址（包括大廈名稱、樓層及室號）",
        "cart.hkPostTitle": "📮 香港郵政 - 平郵",
        "cart.hkPostFeeNote": "運費 HK$10 將自動加入訂單總額，以平郵方式寄出。",
        "cart.recipientName": "收件人姓名 *",
        "cart.recipientNamePlaceholder": "收件人全名",
        "cart.contactPhone": "聯絡電話 *",
        "cart.deliveryAddress": "送貨地址 *",
        "cart.fullAddressNote": "請填寫完整地址（包括大廈名稱、樓層及室號）",
        "cart.offerPrice": "出價價",
        "cart.auctionWon": "拍賣得標",
        "cart.hkPostShipping": "香港郵政運費",
        "cart.totalWithShipping": "合計（含運費）",
        "cart.totalExcludeShipping": "合計（不含運費）",
        "cart.sfCodLabel": "順豐速運（運費到付）",
        "cart.hkPostLabel": "香港郵政（平郵）",
        "cart.sfStationShort": "順豐點",
        "cart.hkPostPlusLabel": "香港郵政（平郵，+HK$10）",
        "cart.paymentMethod": "付款方式",
        "cart.sellerItemsPaymentNotice": "購物車包含個人賣家商品，僅支援信用卡付款。支付寶 HK 僅適用於全部為本公司自營商品的訂單。",
        "cart.alipayHkLabel": "支付寶 HK",
        "cart.unavailable": "不可用",
        "cart.alipaySellerItemsDisabled": "包含個人賣家商品，不可使用此付款方式",
        "cart.scanQrToPay": "掃描二維碼完成付款",
        "cart.creditCard": "信用卡",
        "cart.recommended": "推薦",
        "cart.creditCardNote": "支援 Visa、Mastercard 等主要信用卡",
        "cart.marketplaceItemsCount": "將為 {{count}} 件市集商品",
        "cart.and": "及 ",
        "cart.auctionItemsCount": "{{count}} 件拍賣得標",
        "cart.multipleOrders": "#{{first}} 等 {{count}} 個訂單",
        "cart.orderNo": "訂單編號",
        "cart.payee": "收款方",
        "cart.companyName": "零度有限公司",
        "cart.paymentAmount": "付款金額",
        "cart.paymentStatus": "付款狀態",
        "cart.paymentSuccess": "成功",
        "cart.continueFilling": "繼續填寫",
        "cart.confirmGoBack": "確定返回",
        "cart.uploading": "上傳中...",
        "cart.clickToChangeScreenshot": "點擊更換截圖",
    },
    "en": {
        "cart.freightExtra": "Freight collect",
        "cart.sfTerms1": "[SF Express pickup point discount available] Please provide recipient name, phone, and select your SF Express pickup point when ordering. Shipping fee is automatically calculated based on weight, dimensions, and delivery address. Paid to SF Express upon pickup.",
        "cart.sfTerms2": "[Customer Notice] SF Express has suspended SMS pickup notifications. All pickup notifications are now sent via the SFHK APP. Please download the SFHK APP in advance and enable push notifications to avoid missing delivery alerts.",
        "cart.createOrdersStripe": ", merged into a single HK${{total}} Stripe payment to complete all orders at once.",
        "cart.createOrdersAlipay": "Will create {{count}} orders for {{count}} items. After confirmation, an AlipayHK QR code will be shown. Scan to pay HK${{total}} total, then upload screenshot to confirm.",
        "cart.selectedFile": "Selected: {{name}} ({{size}} KB)",
        "cart.selectDistrict": "Select district",
        "cart.sfStationLabel": "SF Point / Locker *",
        "cart.selectSfStation": "Select SF Point / Locker",
        "cart.detailedAddress": "Detailed address *",
        "cart.addressPlaceholder": "e.g. Room 201, 2/F, Citygate Outlets, 1 Lantau Outlet Drive, Tung Chung, N.T.",
        "cart.sfDeliveryAddressNote": "SF Express door-to-door delivery. Please provide full address (including building name, floor, and unit number).",
        "cart.hkPostTitle": "📮 Hong Kong Post - Surface Mail",
        "cart.hkPostFeeNote": "Shipping fee of HK$10 will be automatically added to the order total, sent by surface mail.",
        "cart.recipientName": "Recipient name *",
        "cart.recipientNamePlaceholder": "Full name",
        "cart.contactPhone": "Contact phone *",
        "cart.deliveryAddress": "Delivery address *",
        "cart.fullAddressNote": "Please provide full address (including building name, floor, and unit number).",
        "cart.offerPrice": "Offer price",
        "cart.auctionWon": "Auction won",
        "cart.hkPostShipping": "HK Post shipping",
        "cart.totalWithShipping": "Total (incl. shipping)",
        "cart.totalExcludeShipping": "Total (excl. shipping)",
        "cart.sfCodLabel": "SF Express (freight collect)",
        "cart.hkPostLabel": "HK Post (surface mail)",
        "cart.sfStationShort": "SF Point",
        "cart.hkPostPlusLabel": "HK Post (surface mail, +HK$10)",
        "cart.paymentMethod": "Payment method",
        "cart.sellerItemsPaymentNotice": "Cart contains seller items. Only credit card payment is supported. AlipayHK is only available for orders with all items from our store.",
        "cart.alipayHkLabel": "AlipayHK",
        "cart.unavailable": "Unavailable",
        "cart.alipaySellerItemsDisabled": "Contains seller items, cannot use this payment method",
        "cart.scanQrToPay": "Scan QR code to pay",
        "cart.creditCard": "Credit card",
        "cart.recommended": "Recommended",
        "cart.creditCardNote": "Supports Visa, Mastercard and other major credit cards",
        "cart.marketplaceItemsCount": "Will create orders for {{count}} marketplace items",
        "cart.and": "and ",
        "cart.auctionItemsCount": "{{count}} auction wins",
        "cart.multipleOrders": "#{{first}} and {{count}} orders",
        "cart.orderNo": "Order number",
        "cart.payee": "Payee",
        "cart.companyName": "Zero Degree Limited",
        "cart.paymentAmount": "Payment amount",
        "cart.paymentStatus": "Payment status",
        "cart.paymentSuccess": "Successful",
        "cart.continueFilling": "Continue filling",
        "cart.confirmGoBack": "Confirm go back",
        "cart.uploading": "Uploading...",
        "cart.clickToChangeScreenshot": "Click to change screenshot",
    },
    "ja": {
        "cart.freightExtra": "着払い",
        "cart.sfTerms1": "【SF Expressの受け取りポイントをご利用の場合、送料割引あり】注文時に受取人名、電話番号を入力し、SF Expressの受け取りポイントを選択してください。送料は荷物の重量、サイズ、配送先住所に基づいて自動計算されます。",
        "cart.sfTerms2": "【お客様へのご注意】SF ExpressはSMSによる荷物受け取り通知を停止しました。すべての通知はSFHK APPを通じて送信されます。事前にSFHK APPをダウンロードし、プッシュ通知を有効にしてください。",
        "cart.createOrdersStripe": "、合計HK${{total}}のStripe決済にまとめて、すべての注文を一度に完了します。",
        "cart.createOrdersAlipay": "{{count}}件の商品に対して{{count}}件の注文を作成します。確認後、AlipayHKのQRコードが表示されます。合計HK${{total}}をスキャンして支払い、スクリーンショットをアップロードして確認してください。",
        "cart.selectedFile": "選択済み：{{name}}（{{size}} KB）",
        "cart.selectDistrict": "地区を選択",
        "cart.sfStationLabel": "SF受け取りポイント / ロッカー *",
        "cart.selectSfStation": "SF受け取りポイント / ロッカーを選択",
        "cart.detailedAddress": "詳細住所 *",
        "cart.addressPlaceholder": "例：新界東涌達東路1号東薈城2階201室",
        "cart.sfDeliveryAddressNote": "SF Express宅配便。建物名、階数、部屋番号を含む完全な住所を入力してください。",
        "cart.hkPostTitle": "📮 香港郵政 - 普通郵便",
        "cart.hkPostFeeNote": "送料HK$10が注文合計に自動的に追加され、普通郵便で発送されます。",
        "cart.recipientName": "受取人名 *",
        "cart.recipientNamePlaceholder": "フルネーム",
        "cart.contactPhone": "連絡先電話番号 *",
        "cart.deliveryAddress": "配送先住所 *",
        "cart.fullAddressNote": "建物名、階数、部屋番号を含む完全な住所を入力してください。",
        "cart.offerPrice": "オファー価格",
        "cart.auctionWon": "オークション落札",
        "cart.hkPostShipping": "香港郵政送料",
        "cart.totalWithShipping": "合計（送料込み）",
        "cart.totalExcludeShipping": "合計（送料別）",
        "cart.sfCodLabel": "SF Express（着払い）",
        "cart.hkPostLabel": "香港郵政（普通郵便）",
        "cart.sfStationShort": "SF受け取りポイント",
        "cart.hkPostPlusLabel": "香港郵政（普通郵便、+HK$10）",
        "cart.paymentMethod": "支払い方法",
        "cart.sellerItemsPaymentNotice": "カートに個人販売者の商品が含まれています。クレジットカード払いのみ対応しています。AlipayHKは当社自営商品のみの注文に限り使用可能です。",
        "cart.alipayHkLabel": "AlipayHK",
        "cart.unavailable": "利用不可",
        "cart.alipaySellerItemsDisabled": "個人販売者の商品が含まれているため、この支払い方法は使用できません",
        "cart.scanQrToPay": "QRコードをスキャンして支払う",
        "cart.creditCard": "クレジットカード",
        "cart.recommended": "おすすめ",
        "cart.creditCardNote": "Visa、Mastercardなど主要クレジットカードに対応",
        "cart.marketplaceItemsCount": "{{count}}件のマーケットプレイス商品の注文を作成します",
        "cart.and": "および",
        "cart.auctionItemsCount": "{{count}}件のオークション落札",
        "cart.multipleOrders": "#{{first}} など{{count}}件の注文",
        "cart.orderNo": "注文番号",
        "cart.payee": "受取人",
        "cart.companyName": "Zero Degree Limited",
        "cart.paymentAmount": "支払い金額",
        "cart.paymentStatus": "支払い状態",
        "cart.paymentSuccess": "成功",
        "cart.continueFilling": "入力を続ける",
        "cart.confirmGoBack": "戻ることを確認",
        "cart.uploading": "アップロード中...",
        "cart.clickToChangeScreenshot": "クリックしてスクリーンショットを変更",
    }
}

LANG_FILES = {
    "zh-TW": os.path.join(BASE, "zh-TW.json"),
    "en": os.path.join(BASE, "en.json"),
    "ja": os.path.join(BASE, "ja.json"),
}

for lang, keys in new_keys.items():
    path = LANG_FILES[lang]
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    
    added = 0
    for key, value in keys.items():
        parts = key.split('.')
        node = data
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        if parts[-1] not in node:
            node[parts[-1]] = value
            added += 1
    
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"[{lang}] Added {added} keys")

print("Done!")
