import json

files = {
    "zh-TW": "/home/ubuntu/boxium-ptcg/client/src/locales/zh-TW.json",
    "en": "/home/ubuntu/boxium-ptcg/client/src/locales/en.json",
    "ja": "/home/ubuntu/boxium-ptcg/client/src/locales/ja.json",
}

new_keys = {
    "zh-TW": {
        "common": {
            "optional": "選填",
            "edit": "編輯",
            "cancel": "取消",
            "processing": "處理中...",
            "submitting": "提交中...",
            "deleting": "刪除中...",
            "nextStep": "下一步",
            "backToHome": "返回首頁",
            "days": "日",
        },
        "seller": {
            "applyToSell": "申請成為賣家",
            "priceChangeNote": "修改售價不影響已建立的訂單金額",
            "soldCount": "已售出 {{count}} 件",
            "psa10MarketPrice": "PSA 10 市場均價",
            "psa10MarketPriceRef": "PSA 10 市場均價（參考）",
            "marketPrice": "市場均價",
            "marketRefPrice": "市場參考價",
            "noConditionRecords": "此品相無成交記錄，顯示 PSA 10 作參考",
            "noMarketPriceData": "此品相目前無市場均價資料",
            "basedOnRecords": "基於最近 {{count}} 筆成交",
            "priceTooLow": "定價不能低於 HKD 4.00（Stripe 信用卡付款最低限額）",
            "adminFeeExempt": "管理員帳號（免平台費）",
            "estimatedFee": "預計平台費",
            "estimatedReceive": "預計實收",
            "feeTier": "適用第 {{tier}} 級費率（{{rate}}%）",
            "estimatedFeeAmount": "預計平台費 -HKD {{amount}}",
            "aboveMarket": "高於{{label}} {{pct}}%",
            "belowMarket": "低於{{label}} {{pct}}%",
            "hoursLeft": "還有 {{hours}} 小時",
            "recipient": "收件人",
            "address": "地址",
            "listingActive": "上架中",
            "listingRemoved": "已下架",
            "editListing": {
                "descPlaceholder": "商品描述（可選）",
                "priceLabel": "售價（HKD）",
                "minPrice": "最低 HKD 4.00",
                "stockLabel": "庫存數量",
                "minStock": "最少 1 件",
                "priceError": "售價不能低於 HKD 4.00",
                "stockError": "庫存數量不能小於 1",
                "saveChanges": "儲存更改",
            },
            "newListing": {
                "title": "上架新商品",
                "step1": "基本資料",
                "step2": "定價設定",
                "imageRequired": "請至少上傳一張商品圖片（必填）",
                "clickToSearchCard": "點擊搜索並關聯卡牌",
                "titleMinLength": "商品名稱至少需要 3 個字元",
                "mode": {
                    "buyNowDesc": "買家直接以定價購買",
                    "auctionDesc": "買家競價，時限結標",
                    "auction": "拍賣",
                },
                "priceLabel": "售價（HKD）*",
                "loadingMarketPrice": "查詢市場均價中...",
                "productDescription": "商品描述",
                "productDescriptionPlaceholder": "詳細描述商品狀況、特點等（可選）",
                "quantity": "數量",
                "acceptOffersHint": "買家可提交低於定價的出價",
                "minOffer": "最低接受出價（HKD，選填）",
                "minOfferPlaceholder": "留空表示不設下限",
                "imageAlt": "圖片",
                "listingMode": "上架模式",
                "acceptsOffers": "接受出價",
                "notAccepting": "不接受",
                "confirmPublish": "確認後直接公開上架",
                "confirmPublishAuction": "提交後立即公開上架",
                "publishDesc": "商品提交後將自動公開，展示於市集中供買家瀏覽。",
                "agreeTerms": "我已閱讀並同意",
                "termsLink": "買賣條款",
                "termsDesc": "，包括平台服務費率、拍賣規則及退款政策。",
                "confirmList": "確認上架",
                "afterListing": "上架後起算",
                "startingBid": "起標價（HKD）*",
                "startingBidPlaceholder": "例：100",
                "reservePrice": "底價（HKD，選填）",
                "reservePriceHint": "競價須達底價才會成交，底價不公開顯示",
                "reservePricePlaceholder": "留空表示無底價",
                "reservePriceHidden": "不公開",
                "buyNowPrice": "即買價（HKD，選填）",
                "buyNowPriceHint": "買家可以此價直接結標購買",
                "buyNowPricePlaceholder": "留空表示無即買價",
                "bidIncrement": "最低加價幅度（HKD）",
                "auctionDays": "拍賣天數 *",
                "startTime": "開始時間（24小時制，留空表示立即開始）",
                "startNow": "立即開始",
                "startNowDesc": "上架後立即開始拍賣",
                "estimatedEndTime": "預計結標時間",
                "endTimePast": "結標時間已過去，請重新設定",
                "price": {
                    "allowOffers": "接受買家出價",
                },
            },
            "shipping": {
                "title": "填寫出貨資料",
                "orderNo": "訂單號",
                "buyerInfo": "買家收件資訊",
                "methodTitle": "送貨方式說明",
                "methodDesc": "本平台僅支援以下兩種送貨方式，不支援面交或門市自取：",
                "sfExpress": "順豐速運",
                "sfExpressDesc": "運費到付：買家收貨時支付運費，請填寫有效追蹤號碼",
                "sfExpressPlaceholder": "例：SF1234567890",
                "hkPost": "香港郵政（平郵）",
                "hkPostDesc": "訂單金額已包含 HK$10 郵費，平郵無追蹤號碼，追蹤號碼欄可留空",
                "hkPostTrackingPlaceholder": "平郵可留空（如有追蹤號可填入）",
                "methodLabel": "送貨方式",
                "selectMethod": "選擇送貨方式",
                "trackingLabel": "追蹤號碼",
                "previewTracking": "點擊預覽追蹤連結",
                "proofLabel": "出貨憑證圖片",
                "proofRequired": "必須上傳出貨憑證（如快遞單、收據截圖），否則無法提交",
                "proofAlt": "出貨憑證",
                "uploadPhoto": "點擊上傳出貨照片",
                "uploadHint": "支援 JPG、PNG（最大 10MB）",
                "fileSizeError": "圖片大小不能超過 10MB",
                "confirmShip": "確認出貨",
            },
            "deleteListing": {
                "title": "確認刪除商品",
                "desc": "您即將永久刪除以下 {{count}} 件商品，此操作不可復原：",
                "unnamed": "（未命名商品）",
                "notes": "注意事項",
                "note1": "商品將從資料庫永久刪除",
                "note2": "如有待付款訂單，將自動更新為已取消",
                "note3": "已售出商品不會被刪除",
            },
            "auctionTerms": {
                "title": "拍賣賣家條款",
                "intro": "上架拍賣前，請仔細閱讀並同意以下賣家責任條款：",
                "authenticityTitle": "商品真實性保證",
                "authenticityContent": "賣家須確保所上架商品為本人合法持有，商品描述、品相評級及圖片須如實反映商品狀況，不得虛假陳述或誇大。若商品為仿冒品或描述與實物不符，平台有權立即下架並封禁帳戶。",
                "shippingTitle": "出貨責任",
                "shippingContent": "拍賣結標且買家完成付款後，賣家須於 3 個工作天內安排出貨，並在平台填寫有效追蹤號碼。逾期未出貨將被記錄違規，影響帳戶評分及上架資格。",
                "withdrawTitle": "撤拍限制",
                "withdrawContent": "拍賣一經上架並有人出價後，賣家不得無故撤回拍賣。如需撤拍，須提前聯絡平台客服說明原因。惡意撤拍將視同違規處理，首次警告，再犯將限制上架資格。",
                "feeTitle": "平台服務費",
                "feeContent": "每筆成功成交的拍賣，平台將收取成交金額 5% 作為服務費，於買家付款後自動扣除。賣家實際到手金額為成交價扣除服務費後的餘額。",
                "newSellerTitle": "新賣家限制",
                "newSellerContent": "完成成交少於 5 次的新賣家，拍賣起拍價上限為 HK$5,000。起拍價超過 HK$10,000 的拍賣屬於高價風控監控範圍，將自動公開並通知管理員監控。",
                "violationTitle": "違規處理",
                "violationContent": "賣家違規（虛假描述、惡意撤拍、逾期不出貨等）將依以下程序處理：首次違規：警告 → 第二次：7 天限制上架 → 第三次：30 天封禁 → 第四次：永久封禁。",
                "protectionTitle": "買賣雙方保障",
                "protectionContent": "平台設有買賣雙方評價系統。拍賣完成後，買家可對賣家評分，評分記錄公開顯示於賣家個人頁面。賣家亦可對買家評分，共同維護平台交易環境。",
                "fullTermsLink": "如需查看完整條款，請訪問",
                "pageLink": "拍賣條款頁面",
                "agreeAndList": "我同意並繼續上架",
            },
            "listings": {
                "card": {
                    "deactivate": "下架",
                    "activate": "上架",
                    "adminDelisted": "已被管理員下架",
                },
            },
        },
    },
    "en": {
        "common": {
            "optional": "Optional",
            "edit": "Edit",
            "cancel": "Cancel",
            "processing": "Processing...",
            "submitting": "Submitting...",
            "deleting": "Deleting...",
            "nextStep": "Next",
            "backToHome": "Back to Home",
            "days": "days",
        },
        "seller": {
            "applyToSell": "Apply to Sell",
            "priceChangeNote": "Price changes do not affect existing orders",
            "soldCount": "{{count}} sold",
            "psa10MarketPrice": "PSA 10 Market Price",
            "psa10MarketPriceRef": "PSA 10 Market Price (Ref.)",
            "marketPrice": "Market Price",
            "marketRefPrice": "Market Reference Price",
            "noConditionRecords": "No sales records for this condition, showing PSA 10 as reference",
            "noMarketPriceData": "No market price data available for this condition",
            "basedOnRecords": "Based on {{count}} recent sales",
            "priceTooLow": "Price cannot be lower than HKD 4.00 (Stripe minimum)",
            "adminFeeExempt": "Admin account (fee exempt)",
            "estimatedFee": "Estimated platform fee",
            "estimatedReceive": "Estimated payout",
            "feeTier": "Tier {{tier}} rate ({{rate}}%)",
            "estimatedFeeAmount": "Est. fee -HKD {{amount}}",
            "aboveMarket": "{{pct}}% above {{label}}",
            "belowMarket": "{{pct}}% below {{label}}",
            "hoursLeft": "{{hours}} hours left",
            "recipient": "Recipient",
            "address": "Address",
            "listingActive": "Active",
            "listingRemoved": "Removed",
            "editListing": {
                "descPlaceholder": "Product description (optional)",
                "priceLabel": "Price (HKD)",
                "minPrice": "Minimum HKD 4.00",
                "stockLabel": "Stock quantity",
                "minStock": "Minimum 1",
                "priceError": "Price cannot be lower than HKD 4.00",
                "stockError": "Stock quantity cannot be less than 1",
                "saveChanges": "Save Changes",
            },
            "newListing": {
                "title": "New Listing",
                "step1": "Basic Info",
                "step2": "Pricing",
                "imageRequired": "Please upload at least one product image (required)",
                "clickToSearchCard": "Click to search and associate a card",
                "titleMinLength": "Product title must be at least 3 characters",
                "mode": {
                    "buyNowDesc": "Buyer purchases at fixed price",
                    "auctionDesc": "Buyers bid, ends at deadline",
                    "auction": "Auction",
                },
                "priceLabel": "Price (HKD) *",
                "loadingMarketPrice": "Loading market price...",
                "productDescription": "Product Description",
                "productDescriptionPlaceholder": "Describe the product condition, features, etc. (optional)",
                "quantity": "Qty",
                "acceptOffersHint": "Buyers can submit offers below the listed price",
                "minOffer": "Minimum offer (HKD, optional)",
                "minOfferPlaceholder": "Leave blank for no minimum",
                "imageAlt": "Image",
                "listingMode": "Listing Mode",
                "acceptsOffers": "Accepts offers",
                "notAccepting": "Not accepting",
                "confirmPublish": "Will be published immediately after confirmation",
                "confirmPublishAuction": "Will be published immediately after submission",
                "publishDesc": "Product will be automatically published and visible to buyers in the marketplace.",
                "agreeTerms": "I have read and agree to the",
                "termsLink": "Terms of Service",
                "termsDesc": ", including platform fees, auction rules, and refund policy.",
                "confirmList": "Confirm Listing",
                "afterListing": "after listing",
                "startingBid": "Starting Bid (HKD) *",
                "startingBidPlaceholder": "e.g. 100",
                "reservePrice": "Reserve Price (HKD, optional)",
                "reservePriceHint": "Auction only succeeds if reserve is met; reserve is not shown publicly",
                "reservePricePlaceholder": "Leave blank for no reserve",
                "reservePriceHidden": "hidden",
                "buyNowPrice": "Buy Now Price (HKD, optional)",
                "buyNowPriceHint": "Buyer can end auction immediately at this price",
                "buyNowPricePlaceholder": "Leave blank for no buy now",
                "bidIncrement": "Minimum Bid Increment (HKD)",
                "auctionDays": "Auction Duration *",
                "startTime": "Start Time (24h format, leave blank to start immediately)",
                "startNow": "Start immediately",
                "startNowDesc": "Auction starts immediately after listing",
                "estimatedEndTime": "Estimated end time",
                "endTimePast": "End time has passed, please reset",
                "price": {
                    "allowOffers": "Accept buyer offers",
                },
            },
            "shipping": {
                "title": "Enter Shipping Details",
                "orderNo": "Order No.",
                "buyerInfo": "Buyer Shipping Info",
                "methodTitle": "Shipping Method Guide",
                "methodDesc": "Only the following two shipping methods are supported. In-person pickup is not available:",
                "sfExpress": "SF Express",
                "sfExpressDesc": "Freight collect: buyer pays shipping on delivery. Please enter a valid tracking number.",
                "sfExpressPlaceholder": "e.g. SF1234567890",
                "hkPost": "HongKong Post (Surface Mail)",
                "hkPostDesc": "Order total includes HK$10 postage. Surface mail has no tracking number; tracking field can be left blank.",
                "hkPostTrackingPlaceholder": "Surface mail can be left blank (enter if available)",
                "methodLabel": "Shipping Method",
                "selectMethod": "Select shipping method",
                "trackingLabel": "Tracking Number",
                "previewTracking": "Click to preview tracking link",
                "proofLabel": "Shipping Proof Image",
                "proofRequired": "Must upload shipping proof (e.g. courier receipt, screenshot), otherwise cannot submit",
                "proofAlt": "Shipping Proof",
                "uploadPhoto": "Click to upload shipping photo",
                "uploadHint": "Supports JPG, PNG (max 10MB)",
                "fileSizeError": "Image size cannot exceed 10MB",
                "confirmShip": "Confirm Shipment",
            },
            "deleteListing": {
                "title": "Confirm Delete Listing",
                "desc": "You are about to permanently delete {{count}} listing(s). This cannot be undone:",
                "unnamed": "(Unnamed listing)",
                "notes": "Notes",
                "note1": "Listings will be permanently deleted from the database",
                "note2": "Pending payment orders will be automatically cancelled",
                "note3": "Sold listings will not be deleted",
            },
            "auctionTerms": {
                "title": "Auction Seller Terms",
                "intro": "Before listing an auction, please read and agree to the following seller responsibilities:",
                "authenticityTitle": "Product Authenticity Guarantee",
                "authenticityContent": "Sellers must ensure listed items are legally owned. Descriptions, condition grades, and images must accurately reflect the item. False descriptions or misrepresentation will result in immediate removal and account ban.",
                "shippingTitle": "Shipping Responsibility",
                "shippingContent": "After auction ends and buyer pays, seller must ship within 3 business days and enter a valid tracking number. Late shipment will be recorded as a violation, affecting account rating and listing privileges.",
                "withdrawTitle": "Withdrawal Restrictions",
                "withdrawContent": "Once an auction has received bids, sellers may not withdraw without cause. Contact customer service if withdrawal is necessary. Malicious withdrawal is treated as a violation: first offense is a warning, repeat offenses will restrict listing privileges.",
                "feeTitle": "Platform Service Fee",
                "feeContent": "A 5% service fee is charged on each successful auction, deducted automatically after buyer payment. Seller payout is the final price minus the service fee.",
                "newSellerTitle": "New Seller Restrictions",
                "newSellerContent": "New sellers with fewer than 5 completed transactions have a starting bid cap of HK$5,000. Auctions with starting bids over HK$10,000 are subject to high-value risk monitoring.",
                "violationTitle": "Violation Handling",
                "violationContent": "Violations (false descriptions, malicious withdrawal, late shipment, etc.) are handled as follows: 1st offense: Warning → 2nd: 7-day listing restriction → 3rd: 30-day ban → 4th: Permanent ban.",
                "protectionTitle": "Buyer & Seller Protection",
                "protectionContent": "The platform has a mutual rating system. After auction completion, buyers can rate sellers (publicly displayed on seller profile). Sellers can also rate buyers to maintain a healthy trading environment.",
                "fullTermsLink": "For full terms, visit",
                "pageLink": "Auction Terms Page",
                "agreeAndList": "I Agree and Continue Listing",
            },
            "listings": {
                "card": {
                    "deactivate": "Deactivate",
                    "activate": "Activate",
                    "adminDelisted": "Removed by admin",
                },
            },
        },
    },
    "ja": {
        "common": {
            "optional": "任意",
            "edit": "編集",
            "cancel": "キャンセル",
            "processing": "処理中...",
            "submitting": "送信中...",
            "deleting": "削除中...",
            "nextStep": "次へ",
            "backToHome": "ホームに戻る",
            "days": "日",
        },
        "seller": {
            "applyToSell": "出品者申請",
            "priceChangeNote": "価格変更は既存の注文に影響しません",
            "soldCount": "{{count}}件売却済み",
            "psa10MarketPrice": "PSA 10 市場価格",
            "psa10MarketPriceRef": "PSA 10 市場価格（参考）",
            "marketPrice": "市場価格",
            "marketRefPrice": "市場参考価格",
            "noConditionRecords": "このコンディションの取引記録なし。PSA 10を参考として表示",
            "noMarketPriceData": "このコンディションの市場価格データなし",
            "basedOnRecords": "直近{{count}}件の取引に基づく",
            "priceTooLow": "価格はHKD 4.00以上が必要です（Stripe最低金額）",
            "adminFeeExempt": "管理者アカウント（手数料免除）",
            "estimatedFee": "予定手数料",
            "estimatedReceive": "予定受取額",
            "feeTier": "ティア{{tier}}レート（{{rate}}%）",
            "estimatedFeeAmount": "予定手数料 -HKD {{amount}}",
            "aboveMarket": "{{label}}より{{pct}}%高い",
            "belowMarket": "{{label}}より{{pct}}%低い",
            "hoursLeft": "残り{{hours}}時間",
            "recipient": "受取人",
            "address": "住所",
            "listingActive": "出品中",
            "listingRemoved": "取り下げ済み",
            "editListing": {
                "descPlaceholder": "商品説明（任意）",
                "priceLabel": "価格（HKD）",
                "minPrice": "最低HKD 4.00",
                "stockLabel": "在庫数量",
                "minStock": "最低1件",
                "priceError": "価格はHKD 4.00以上が必要です",
                "stockError": "在庫数量は1以上が必要です",
                "saveChanges": "変更を保存",
            },
            "newListing": {
                "title": "新規出品",
                "step1": "基本情報",
                "step2": "価格設定",
                "imageRequired": "商品画像を1枚以上アップロードしてください（必須）",
                "clickToSearchCard": "クリックしてカードを検索・関連付け",
                "titleMinLength": "商品名は3文字以上必要です",
                "mode": {
                    "buyNowDesc": "購入者が定価で直接購入",
                    "auctionDesc": "入札制、期限終了で落札",
                    "auction": "オークション",
                },
                "priceLabel": "価格（HKD）*",
                "loadingMarketPrice": "市場価格を取得中...",
                "productDescription": "商品説明",
                "productDescriptionPlaceholder": "商品の状態、特徴などを詳しく説明（任意）",
                "quantity": "数量",
                "acceptOffersHint": "購入者は定価以下の価格を提案できます",
                "minOffer": "最低受付価格（HKD、任意）",
                "minOfferPlaceholder": "空白で下限なし",
                "imageAlt": "画像",
                "listingMode": "出品モード",
                "acceptsOffers": "価格交渉可",
                "notAccepting": "交渉不可",
                "confirmPublish": "確認後すぐに公開出品",
                "confirmPublishAuction": "送信後すぐに公開出品",
                "publishDesc": "商品は自動的に公開され、マーケットプレイスで購入者に表示されます。",
                "agreeTerms": "以下に同意します：",
                "termsLink": "利用規約",
                "termsDesc": "（プラットフォーム手数料、オークションルール、返金ポリシーを含む）",
                "confirmList": "出品確定",
                "afterListing": "出品後起算",
                "startingBid": "開始価格（HKD）*",
                "startingBidPlaceholder": "例：100",
                "reservePrice": "最低落札価格（HKD、任意）",
                "reservePriceHint": "最低落札価格に達した場合のみ成立。非公開",
                "reservePricePlaceholder": "空白で最低落札価格なし",
                "reservePriceHidden": "非公開",
                "buyNowPrice": "即決価格（HKD、任意）",
                "buyNowPriceHint": "購入者はこの価格でオークションを即終了できます",
                "buyNowPricePlaceholder": "空白で即決価格なし",
                "bidIncrement": "最低入札単位（HKD）",
                "auctionDays": "オークション期間 *",
                "startTime": "開始時刻（24時間制、空白で即時開始）",
                "startNow": "即時開始",
                "startNowDesc": "出品後すぐにオークション開始",
                "estimatedEndTime": "予定終了時刻",
                "endTimePast": "終了時刻が過去です。再設定してください",
                "price": {
                    "allowOffers": "価格交渉を受け付ける",
                },
            },
            "shipping": {
                "title": "発送情報入力",
                "orderNo": "注文番号",
                "buyerInfo": "購入者の配送情報",
                "methodTitle": "配送方法について",
                "methodDesc": "以下の2つの配送方法のみ対応。対面受け渡しは不可：",
                "sfExpress": "SF Express",
                "sfExpressDesc": "着払い：購入者が受取時に送料を支払います。有効な追跡番号を入力してください。",
                "sfExpressPlaceholder": "例：SF1234567890",
                "hkPost": "香港郵政（普通郵便）",
                "hkPostDesc": "注文金額にHK$10の送料が含まれます。普通郵便は追跡番号なし。空白可。",
                "hkPostTrackingPlaceholder": "普通郵便は空白可（番号があれば入力）",
                "methodLabel": "配送方法",
                "selectMethod": "配送方法を選択",
                "trackingLabel": "追跡番号",
                "previewTracking": "追跡リンクをプレビュー",
                "proofLabel": "発送証明画像",
                "proofRequired": "発送証明（宅配伝票、領収書スクリーンショットなど）のアップロードが必須です",
                "proofAlt": "発送証明",
                "uploadPhoto": "発送写真をアップロード",
                "uploadHint": "JPG、PNG対応（最大10MB）",
                "fileSizeError": "画像サイズは10MB以下にしてください",
                "confirmShip": "発送確定",
            },
            "deleteListing": {
                "title": "出品削除の確認",
                "desc": "以下の{{count}}件の出品を完全に削除します。この操作は元に戻せません：",
                "unnamed": "（無名の出品）",
                "notes": "注意事項",
                "note1": "出品はデータベースから完全に削除されます",
                "note2": "支払い待ちの注文は自動的にキャンセルされます",
                "note3": "売却済みの出品は削除されません",
            },
            "auctionTerms": {
                "title": "オークション出品者規約",
                "intro": "オークション出品前に、以下の出品者責任規約をよく読んで同意してください：",
                "authenticityTitle": "商品真正性の保証",
                "authenticityContent": "出品者は、出品商品が合法的に所有するものであることを確認する必要があります。説明、コンディション評価、画像は実物を正確に反映する必要があります。偽造品や虚偽説明の場合、プラットフォームは即座に削除しアカウントを停止します。",
                "shippingTitle": "発送責任",
                "shippingContent": "オークション終了後、購入者が支払いを完了したら、出品者は3営業日以内に発送し、有効な追跡番号を入力する必要があります。遅延発送は違反として記録され、アカウント評価と出品資格に影響します。",
                "withdrawTitle": "取り下げ制限",
                "withdrawContent": "入札があったオークションは、正当な理由なく取り下げることはできません。取り下げが必要な場合は、事前にカスタマーサービスに連絡してください。悪意ある取り下げは違反として処理されます：初回警告、再犯で出品資格制限。",
                "feeTitle": "プラットフォーム手数料",
                "feeContent": "落札成立ごとに、落札金額の5%がサービス手数料として徴収され、購入者の支払い後に自動的に差し引かれます。出品者の受取額は落札価格からサービス手数料を差し引いた金額です。",
                "newSellerTitle": "新規出品者制限",
                "newSellerContent": "取引完了5件未満の新規出品者は、開始価格の上限がHK$5,000です。開始価格がHK$10,000を超えるオークションは高額リスク監視対象となります。",
                "violationTitle": "違反処理",
                "violationContent": "違反（虚偽説明、悪意ある取り下げ、遅延発送など）は以下の手順で処理されます：初回：警告 → 2回目：7日間出品制限 → 3回目：30日間停止 → 4回目：永久停止。",
                "protectionTitle": "売買双方の保護",
                "protectionContent": "プラットフォームには相互評価システムがあります。オークション完了後、購入者は出品者を評価でき（出品者プロフィールに公開表示）、出品者も購入者を評価できます。",
                "fullTermsLink": "完全な規約については",
                "pageLink": "オークション規約ページ",
                "agreeAndList": "同意して出品を続ける",
            },
            "listings": {
                "card": {
                    "deactivate": "取り下げ",
                    "activate": "出品再開",
                    "adminDelisted": "管理者により削除",
                },
            },
        },
    },
}

def deep_merge(base, updates):
    for key, val in updates.items():
        if key in base and isinstance(base[key], dict) and isinstance(val, dict):
            deep_merge(base[key], val)
        else:
            base[key] = val

for lang, path in files.items():
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    
    deep_merge(data, new_keys[lang])
    
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Updated {lang}")

print("Done!")
