import json

LOCALES = {
    "zh-TW": "/home/ubuntu/boxium-ptcg/client/src/locales/zh-TW.json",
    "en": "/home/ubuntu/boxium-ptcg/client/src/locales/en.json",
    "ja": "/home/ubuntu/boxium-ptcg/client/src/locales/ja.json",
}

keys = {
    "zh-TW": {
        "toc": {
            "overview": "平台概覽",
            "buyNow": "直購流程",
            "auction": "拍賣流程",
            "fees": "平台收費",
            "payment": "付款與結算",
            "shipping": "交收安排",
            "returns": "退款政策",
            "conduct": "行為守則",
            "liability": "免責聲明"
        },
        "back": "返回上一頁",
        "officialBadge": "BOXIUM TCG 官方條款",
        "heroTitle": "買賣條款及細則",
        "heroDesc": "本條款適用於 Boxium PTCG 平台上的所有買賣交易，包括直購及拍賣商品。請於交易前仔細閱讀，使用本平台即表示你同意以下所有條款。",
        "lastUpdated": "最後更新：2025 年 4 月",
        "tocTitle": "目錄",
        "s1": {
            "title": "一、平台概覽",
            "intro": "Boxium PTCG（下稱「本平台」）是一個專為集換式卡牌（TCG）愛好者而設的香港買賣平台，提供<strong>直購</strong>及<strong>拍賣</strong>兩種交易模式，讓買賣雙方能夠安全、便捷地進行卡牌交易。",
            "buyNowMode": "直購模式",
            "buyNowDesc": "賣家設定固定售價，買家即時購買，交易即時確認。",
            "auctionMode": "拍賣模式",
            "auctionDesc": "賣家設定起拍價，買家競標，限時結束後最高出價者得標。",
            "infoBox": "本平台所有交易均以<strong>港幣（HKD）</strong>計算。賣家須完成 Stripe Connect 收款帳戶設定方可上架商品。"
        },
        "s2": {
            "title": "二、直購流程",
            "badge": "直購",
            "buyerFlow": "買家流程",
            "b1title": "瀏覽及選購",
            "b1desc": "在商品列表中選擇心儀商品，查閱商品詳情、品相評級及賣家評分。",
            "b2title": "加入購物車或即時購買",
            "b2desc": "點擊「立即購買」或加入購物車後結帳，確認訂單詳情及總金額。",
            "b3title": "完成付款",
            "b3desc": "透過 Stripe 安全支付頁面完成付款，系統即時確認訂單。",
            "b4title": "等候交收",
            "b4desc": "賣家確認出貨後，根據雙方協議的交收方式完成交收。",
            "sellerFlow": "賣家流程",
            "s1title": "上架商品",
            "s1desc": "填寫商品名稱、品相、系列、售價及商品圖片，提交審核。",
            "s2title": "等候管理員審核",
            "s2desc": "所有商品須經平台管理員審核後方可公開上架，確保商品資訊準確。",
            "s3title": "處理訂單",
            "s3desc": "收到訂單通知後，在規定時間內確認出貨並安排交收。",
            "s4title": "收款結算",
            "s4desc": "交易完成後，平台扣除服務費後將款項結算至賣家 Stripe 帳戶。",
            "warningBox": "買家確認付款後，訂單即告成立。除符合退款政策的情況外，買家不得單方面取消訂單。"
        },
        "s3": {
            "title": "三、拍賣流程及條款",
            "badge": "拍賣",
            "flowTitle": "拍賣流程",
            "a1title": "賣家設定拍賣",
            "a1desc": "設定起拍價、拍賣天數（3 日或 7 日）及可選即買價，提交審核後上架。",
            "a2title": "買家出價",
            "a2desc": "登入後可對進行中的拍賣出價，每次出價必須高於當前最高出價。",
            "a3title": "拍賣結束",
            "a3desc": "拍賣時間結束時，最高出價者自動得標。系統即時通知買賣雙方。",
            "a4title": "付款及交收",
            "a4desc": "得標買家須在 <strong>48 小時內</strong>完成付款，逾期視為放棄得標資格。",
            "rulesTitle": "拍賣重要規則",
            "r1title": "出價具法律約束力",
            "r1desc": "一旦出價，即構成購買承諾。得標後必須完成付款，否則帳號將受到限制。",
            "r2title": "即買價機制",
            "r2desc": "若賣家設有即買價，買家可隨時以即買價直接購買，拍賣即時結束。",
            "r3title": "自動通知",
            "r3desc": "被超越出價時，系統將自動通知買家，讓你有機會再次出價。",
            "r4title": "防狙擊機制",
            "r4desc": "拍賣結束前 5 分鐘內有新出價，拍賣時間將自動延長 5 分鐘，確保公平競標。",
            "r5title": "拍賣取消限制",
            "r5desc": "拍賣開始後，若已有出價，賣家不得單方面取消拍賣，違者將受到平台處分。",
            "r6title": "得標確認",
            "r6desc": "拍賣結束後，系統自動向得標買家發送付款連結，請留意通知。",
            "warningBox": "得標買家若在 48 小時內未完成付款，平台有權將商品重新上架，並對違規帳號採取相應措施，包括限制出價資格。"
        },
        "s4": {
            "title": "四、平台收費說明",
            "badge": "重要",
            "intro": "本平台採用<strong>階梯式服務費</strong>，按成交金額高低收取不同費率，成交金額越高，費率越低。服務費僅向<strong>賣家</strong>收取，買家無需支付額外服務費。",
            "tableTitle": "賣家服務費率（以成交金額計算）",
            "loading": "載入費率中...",
            "tier1": "第一級",
            "tier2": "第二級",
            "tier3": "第三級",
            "tierLabel": "第",
            "rangeBelow": "HKD {{amount}} 或以下",
            "rangeAbove": "HKD {{amount}} 或以上",
            "example": "成交 HKD {{amount}} → 服務費 HKD {{fee}}，實收 HKD {{receive}}",
            "notesTitle": "費率補充說明",
            "note1": "服務費於款項結算時自動扣除，賣家毋須另行繳付。",
            "note2": "費率以<strong>單筆成交金額</strong>計算，而非累計金額。",
            "note3": "平台保留調整費率的權利，並提前 7 日以公告形式通知賣家。",
            "note4": "買家付款時，Stripe 支付手續費由平台承擔，不另向買家收取。",
            "successBox": "上架商品及瀏覽平台完全免費。平台僅於交易成功後才收取服務費，不成交不收費。"
        },
        "s5": {
            "title": "五、付款與結算",
            "buyerPayment": "買家付款",
            "p1title": "接受付款方式",
            "p1desc": "本平台透過 Stripe 處理所有付款，支援 Visa、Mastercard、American Express 等主要信用卡及扣帳卡。",
            "p2title": "付款安全",
            "p2desc": "所有付款均透過 Stripe 加密處理，本平台不儲存任何信用卡資料。",
            "p3title": "付款時限",
            "p3desc": "直購訂單須即時完成付款；拍賣得標後須於 48 小時內付款。",
            "sellerPayout": "賣家結算與放款流程",
            "sp1title": "Stripe Connect 帳戶",
            "sp1desc": "賣家須設立並連接 Stripe Connect 帳戶，方可接收款項。",
            "sp2title": "買家確認收貨",
            "sp2desc": "買家收到商品後，須在訂單頁面點擊「確認收貨」。如買家在出貨後 14 天內未確認收貨，系統將自動完成訂單。",
            "sp3title": "48 小時冷靜期",
            "sp3desc": "買家確認收貨（或系統自動完成訂單）後，款項進入 <strong>48 小時冷靜期保護</strong>。在此期間，買家可就商品問題提出爭議申請。",
            "sp4title": "自動放款",
            "sp4desc": "冷靜期結束後，若無任何爭議，系統將自動將款項（扣除平台服務費後的實收金額）轉帳至賣家 Stripe Connect 帳戶。",
            "sp5title": "爭議暫停放款",
            "sp5desc": "如冷靜期內買家提出爭議，款項將暫時凍結，直至爭議處理完畢後方可放款。",
            "timelineTitle": "放款時間軸",
            "tl1step": "買家確認收貨",
            "tl1sub": "或系統自動完成（14天後）",
            "tl2step": "48 小時冷靜期",
            "tl2sub": "買家可提出爭議申請",
            "tl3step": "自動放款",
            "tl3sub": "款項轉入賣家帳戶",
            "infoBox": "如賣家尚未設立 Stripe Connect 帳戶，款項將暫時保留，直至帳戶設立完成後方可提取。冷靜期保護機制旨在保障買家權益，同時確保賣家在無爭議的情況下能及時收款。"
        },
        "s6": {
            "title": "六、交收安排",
            "intro": "本平台採用郵寄方式進行交收，<strong>不支援面交或門市自取</strong>。買家在結帳時選擇以下寄送方式：",
            "sf": {
                "title": "順豐速運（運費到付）",
                "desc": "賣家負責安全包裝及寄出，運費由順豐速運收取，買家於取件時支付。運費金額視貨件重量及地址而定。"
            },
            "hkpost": {
                "title": "香港郵政（平郵）",
                "desc": "賣家負責安全包裝及寄出，運費 HK$10 將自動計入訂單總額，以平郵方式寄出。"
            },
            "warningBox": "本平台不支援面交及門市自取。如商品在運送途中損毀或遺失，責任歸屬由雙方協商解決，平台不承擔相關責任。"
        },
        "s7": {
            "title": "七、退款及退貨政策",
            "intro": "本平台的退款政策以保障買家利益為前提，同時尊重賣家的合理權益。",
            "acceptTitle": "可申請退款的情況",
            "a1title": "商品與描述嚴重不符",
            "a1desc": "收到商品的品相、版本或狀況與賣家描述有重大差異。",
            "a2title": "收到損毀商品",
            "a2desc": "商品在運送過程中損毀，且非買家原因造成。",
            "a3title": "賣家未能出貨",
            "a3desc": "賣家在承諾時間內未能安排交收，且未有合理解釋。",
            "rejectTitle": "不接受退款的情況",
            "r1title": "買家個人原因",
            "r1desc": "買家改變主意、重複購買或個人喜好問題，不接受退款。",
            "r2title": "拍賣得標後",
            "r2desc": "拍賣成交後，除商品描述嚴重不符外，一律不接受退款。",
            "r3title": "已使用或改動的商品",
            "r3desc": "商品經買家使用、改動或損毀後，不接受退款申請。",
            "infoBox": "如商品出現問題需申請退款，請於收貨後 <strong>48 小時</strong>內透過平台客服提交申請介入調解，並提供相關證明（如照片）。平台客服將協助處理您的退款事宜。"
        },
        "s8": {
            "title": "八、用戶行為守則",
            "intro": "為維護平台的公平交易環境，所有用戶須遵守以下行為守則：",
            "c1title": "禁止虛假描述",
            "c1desc": "賣家不得以虛假或誤導性資訊描述商品，包括品相、版本及真偽。",
            "c2title": "禁止操控出價",
            "c2desc": "禁止以多個帳號或與他人勾結的方式操控拍賣出價。",
            "c3title": "禁止場外交易",
            "c3desc": "禁止繞過平台進行私下交易，以規避平台服務費。",
            "c4title": "禁止騷擾行為",
            "c4desc": "禁止以任何形式騷擾、威脅或欺詐其他用戶。",
            "c5title": "誠實交易",
            "c5desc": "買賣雙方須誠實、守信地完成每一筆交易。",
            "c6title": "及時回應",
            "c6desc": "交易雙方應在合理時間內回應對方的訊息及請求。",
            "penaltyTitle": "違規懲罰制度",
            "penaltyCount": "違規次數",
            "penaltyAction": "懲罰措施",
            "penaltyDuration": "封禁時長",
            "p1count": "第 1 次",
            "p1action": "書面警告，永久記錄",
            "p1duration": "無封禁",
            "p2count": "第 2 次",
            "p2action": "封禁競標資格",
            "p2duration": "7 天",
            "p3count": "第 3 次",
            "p3action": "封禁競標資格",
            "p3duration": "30 天",
            "p4count": "第 4 次及以上",
            "p4action": "永久封禁，保留追討損失權利",
            "p4duration": "永久",
            "warningBox": "違反行為守則的用戶，平台有權採取相應措施，包括警告、暫停帳號或永久封禁，視乎違規嚴重程度而定。如認為違規記錄有誤，可在 7 個工作日內向平台客服提出書面申訴。"
        },
        "s9": {
            "title": "九、免責聲明及法律條款",
            "l1title": "平台角色",
            "l1desc": "本平台僅作為買賣雙方的交易媒介，不對商品的真偽、品質或狀況作出任何保證。",
            "l2title": "交易風險",
            "l2desc": "買賣雙方須自行承擔交易風險。本平台對因交易產生的任何損失不承擔法律責任。",
            "l3title": "賠償上限",
            "l3desc": "若本平台被裁定須就任何事項承擔責任，最高賠償責任不超過相關交易中本平台實際收取的服務費金額。",
            "l4title": "服務中斷",
            "l4desc": "本平台不保證服務的持續性及穩定性，因技術故障或維護導致的服務中斷，平台不承擔責任。",
            "l5title": "條款修改",
            "l5desc": "本平台保留隨時修改條款的權利，修改後的條款將在平台公告後生效。繼續使用本平台即表示接受修改後的條款。",
            "l6title": "適用法律",
            "l6desc": "本條款受香港特別行政區法律管轄，任何爭議應提交香港法院解決。",
            "infoBox": "如對本條款有任何疑問，請透過平台客服功能聯絡我們。我們致力於為買賣雙方提供公平、安全的交易環境。"
        },
        "highlights": {
            "h1title": "平台保障",
            "h1desc": "本平台作為中介，提供爭議調解服務，保障買賣雙方的合理權益。",
            "h2title": "公平交易",
            "h2desc": "所有出價具法律約束力，防狙擊機制確保公平競標，違規行為受到相應處理。",
            "h3title": "時效要求",
            "h3desc": "得標後 48 小時內付款，賣家付款確認後 3 個工作日內發貨，逾期將受處分。"
        },
        "cta": {
            "title": "準備好開始交易了嗎？",
            "desc": "閱讀並同意以上條款後，即可開始在 Boxium PTCG 買賣卡牌。",
            "browse": "瀏覽商品",
            "sell": "開始出售"
        },
        "copyright": "保留所有權利。",
        "privacyLink": "私隱政策"
    },
    "en": {
        "toc": {
            "overview": "Overview",
            "buyNow": "Buy Now",
            "auction": "Auction",
            "fees": "Platform Fees",
            "payment": "Payment",
            "shipping": "Shipping",
            "returns": "Returns",
            "conduct": "Conduct",
            "liability": "Disclaimer"
        },
        "back": "Go Back",
        "officialBadge": "BOXIUM TCG Official Terms",
        "heroTitle": "Terms & Conditions",
        "heroDesc": "These terms apply to all transactions on the Boxium PTCG platform, including buy-now and auction items. Please read carefully before transacting. Using this platform means you agree to all terms below.",
        "lastUpdated": "Last Updated: April 2025",
        "tocTitle": "Table of Contents",
        "s1": {
            "title": "1. Platform Overview",
            "intro": "Boxium PTCG (\"the Platform\") is a Hong Kong trading platform for TCG enthusiasts, offering <strong>Buy Now</strong> and <strong>Auction</strong> transaction modes for safe and convenient card trading.",
            "buyNowMode": "Buy Now Mode",
            "buyNowDesc": "Seller sets a fixed price, buyer purchases instantly, transaction confirmed immediately.",
            "auctionMode": "Auction Mode",
            "auctionDesc": "Seller sets a starting price, buyers bid, highest bidder wins when time expires.",
            "infoBox": "All transactions on this platform are in <strong>Hong Kong Dollars (HKD)</strong>. Sellers must complete Stripe Connect account setup before listing items."
        },
        "s2": {
            "title": "2. Buy Now Process",
            "badge": "Buy Now",
            "buyerFlow": "Buyer Flow",
            "b1title": "Browse & Select",
            "b1desc": "Browse listings, check item details, condition grade, and seller rating.",
            "b2title": "Add to Cart or Buy Now",
            "b2desc": "Click \"Buy Now\" or add to cart and checkout, confirm order details and total.",
            "b3title": "Complete Payment",
            "b3desc": "Complete payment via Stripe secure checkout, system confirms order instantly.",
            "b4title": "Wait for Delivery",
            "b4desc": "After seller confirms shipment, complete handover per agreed method.",
            "sellerFlow": "Seller Flow",
            "s1title": "List Item",
            "s1desc": "Fill in item name, condition, series, price, and photos, then submit for review.",
            "s2title": "Await Admin Review",
            "s2desc": "All items require platform admin review before going public to ensure accuracy.",
            "s3title": "Process Orders",
            "s3desc": "Upon receiving order notification, confirm shipment and arrange delivery within the required time.",
            "s4title": "Receive Payment",
            "s4desc": "After transaction completes, platform deducts service fee and settles to seller's Stripe account.",
            "warningBox": "Once buyer confirms payment, the order is established. Buyer cannot unilaterally cancel except under refund policy conditions."
        },
        "s3": {
            "title": "3. Auction Process & Terms",
            "badge": "Auction",
            "flowTitle": "Auction Flow",
            "a1title": "Seller Sets Up Auction",
            "a1desc": "Set starting price, auction duration (3 or 7 days), and optional buy-now price, then submit for review.",
            "a2title": "Buyer Bids",
            "a2desc": "After login, bid on active auctions; each bid must exceed the current highest bid.",
            "a3title": "Auction Ends",
            "a3desc": "When auction time expires, the highest bidder wins automatically. System notifies both parties instantly.",
            "a4title": "Payment & Delivery",
            "a4desc": "Winning buyer must complete payment within <strong>48 hours</strong>; failure to do so forfeits the winning bid.",
            "rulesTitle": "Important Auction Rules",
            "r1title": "Bids Are Legally Binding",
            "r1desc": "Once placed, a bid constitutes a purchase commitment. Payment must be completed after winning, or account will be restricted.",
            "r2title": "Buy-Now Price Mechanism",
            "r2desc": "If seller sets a buy-now price, buyer can purchase at that price anytime, ending the auction immediately.",
            "r3title": "Automatic Notifications",
            "r3desc": "When outbid, the system automatically notifies the buyer, giving them a chance to bid again.",
            "r4title": "Anti-Sniping Mechanism",
            "r4desc": "If a new bid is placed within 5 minutes of auction end, the auction extends by 5 minutes to ensure fair bidding.",
            "r5title": "Auction Cancellation Restriction",
            "r5desc": "Once an auction has bids, sellers cannot unilaterally cancel; violations will result in platform penalties.",
            "r6title": "Win Confirmation",
            "r6desc": "After auction ends, system automatically sends payment link to winning buyer; please check notifications.",
            "warningBox": "If winning buyer fails to pay within 48 hours, platform may relist the item and take action against the violating account, including restricting bidding privileges."
        },
        "s4": {
            "title": "4. Platform Fee Structure",
            "badge": "Important",
            "intro": "The platform uses a <strong>tiered service fee</strong> based on transaction amount—higher amounts have lower rates. Fees are charged to <strong>sellers only</strong>; buyers pay no additional service fees.",
            "tableTitle": "Seller Service Fee Rates (by transaction amount)",
            "loading": "Loading fee rates...",
            "tier1": "Tier 1",
            "tier2": "Tier 2",
            "tier3": "Tier 3",
            "tierLabel": "Tier ",
            "rangeBelow": "HKD {{amount}} or below",
            "rangeAbove": "HKD {{amount}} or above",
            "example": "Sale HKD {{amount}} → Fee HKD {{fee}}, Net HKD {{receive}}",
            "notesTitle": "Additional Notes",
            "note1": "Service fee is automatically deducted at settlement; sellers need not pay separately.",
            "note2": "Rate is calculated on <strong>individual transaction amount</strong>, not cumulative.",
            "note3": "Platform reserves the right to adjust rates with 7 days advance notice to sellers.",
            "note4": "Stripe payment processing fees are borne by the platform; buyers are not charged extra.",
            "successBox": "Listing items and browsing the platform is completely free. Platform only charges service fees upon successful transactions."
        },
        "s5": {
            "title": "5. Payment & Settlement",
            "buyerPayment": "Buyer Payment",
            "p1title": "Accepted Payment Methods",
            "p1desc": "The platform processes all payments via Stripe, supporting Visa, Mastercard, American Express, and other major credit/debit cards.",
            "p2title": "Payment Security",
            "p2desc": "All payments are encrypted via Stripe; the platform does not store any credit card information.",
            "p3title": "Payment Deadline",
            "p3desc": "Buy-now orders require immediate payment; auction winners must pay within 48 hours.",
            "sellerPayout": "Seller Settlement & Payout Process",
            "sp1title": "Stripe Connect Account",
            "sp1desc": "Sellers must set up and connect a Stripe Connect account to receive payments.",
            "sp2title": "Buyer Confirms Receipt",
            "sp2desc": "After receiving the item, buyer must click \"Confirm Receipt\" on the order page. If buyer doesn't confirm within 14 days of shipment, system auto-completes the order.",
            "sp3title": "48-Hour Cooling Period",
            "sp3desc": "After buyer confirms receipt (or system auto-completes), funds enter a <strong>48-hour cooling period protection</strong>. During this time, buyer can raise a dispute.",
            "sp4title": "Automatic Payout",
            "sp4desc": "After cooling period ends with no disputes, system automatically transfers funds (minus platform service fee) to seller's Stripe Connect account.",
            "sp5title": "Dispute Holds Payout",
            "sp5desc": "If buyer raises a dispute during cooling period, funds are frozen until the dispute is resolved.",
            "timelineTitle": "Payout Timeline",
            "tl1step": "Buyer Confirms Receipt",
            "tl1sub": "Or system auto-completes (after 14 days)",
            "tl2step": "48-Hour Cooling Period",
            "tl2sub": "Buyer can raise dispute",
            "tl3step": "Automatic Payout",
            "tl3sub": "Funds transferred to seller",
            "infoBox": "If seller hasn't set up a Stripe Connect account, funds will be held until account setup is complete. The cooling period protects buyer rights while ensuring sellers receive timely payment when no disputes arise."
        },
        "s6": {
            "title": "6. Shipping Arrangements",
            "intro": "The platform uses postal delivery; <strong>in-person pickup and store collection are not supported</strong>. Buyers choose from the following shipping methods at checkout:",
            "sf": {
                "title": "SF Express (freight collect)",
                "desc": "Seller handles secure packaging and shipping; freight is collected by SF Express and paid by buyer upon pickup. Amount varies by weight and address."
            },
            "hkpost": {
                "title": "Hong Kong Post (surface mail)",
                "desc": "Seller handles secure packaging and shipping; HK$10 shipping fee is automatically added to order total, sent via surface mail."
            },
            "warningBox": "In-person pickup and store collection are not supported. If items are damaged or lost in transit, liability is resolved by mutual agreement; the platform bears no responsibility."
        },
        "s7": {
            "title": "7. Refund & Return Policy",
            "intro": "The platform's refund policy prioritizes buyer protection while respecting sellers' reasonable rights.",
            "acceptTitle": "Eligible Refund Situations",
            "a1title": "Item Significantly Differs from Description",
            "a1desc": "Received item's condition, version, or state significantly differs from seller's description.",
            "a2title": "Received Damaged Item",
            "a2desc": "Item was damaged in transit and not due to buyer's actions.",
            "a3title": "Seller Failed to Ship",
            "a3desc": "Seller failed to arrange delivery within the promised time without reasonable explanation.",
            "rejectTitle": "Non-Refundable Situations",
            "r1title": "Buyer's Personal Reasons",
            "r1desc": "Change of mind, duplicate purchase, or personal preference issues are not eligible for refunds.",
            "r2title": "After Winning Auction",
            "r2desc": "After auction completion, refunds are not accepted except for significant description discrepancies.",
            "r3title": "Used or Modified Items",
            "r3desc": "Items that have been used, modified, or damaged by the buyer are not eligible for refunds.",
            "infoBox": "If you need to apply for a refund, please submit a request through platform support within <strong>48 hours</strong> of receipt with supporting evidence (e.g., photos). Platform support will assist with your refund."
        },
        "s8": {
            "title": "8. User Code of Conduct",
            "intro": "To maintain a fair trading environment, all users must follow these conduct guidelines:",
            "c1title": "No False Descriptions",
            "c1desc": "Sellers must not describe items with false or misleading information, including condition, version, and authenticity.",
            "c2title": "No Bid Manipulation",
            "c2desc": "Using multiple accounts or colluding with others to manipulate auction bids is prohibited.",
            "c3title": "No Off-Platform Transactions",
            "c3desc": "Bypassing the platform for private transactions to avoid service fees is prohibited.",
            "c4title": "No Harassment",
            "c4desc": "Harassing, threatening, or defrauding other users in any form is prohibited.",
            "c5title": "Honest Trading",
            "c5desc": "Both buyers and sellers must complete each transaction honestly and in good faith.",
            "c6title": "Timely Response",
            "c6desc": "Both parties should respond to messages and requests within a reasonable time.",
            "penaltyTitle": "Violation Penalty System",
            "penaltyCount": "Violations",
            "penaltyAction": "Penalty",
            "penaltyDuration": "Ban Duration",
            "p1count": "1st offense",
            "p1action": "Written warning, permanent record",
            "p1duration": "No ban",
            "p2count": "2nd offense",
            "p2action": "Bidding privilege suspended",
            "p2duration": "7 days",
            "p3count": "3rd offense",
            "p3action": "Bidding privilege suspended",
            "p3duration": "30 days",
            "p4count": "4th offense+",
            "p4action": "Permanent ban, right to pursue damages reserved",
            "p4duration": "Permanent",
            "warningBox": "Users who violate the code of conduct may face warnings, account suspension, or permanent bans depending on severity. If you believe a violation record is incorrect, you may submit a written appeal to platform support within 7 business days."
        },
        "s9": {
            "title": "9. Disclaimer & Legal Terms",
            "l1title": "Platform Role",
            "l1desc": "The platform serves only as an intermediary for transactions and makes no guarantees about item authenticity, quality, or condition.",
            "l2title": "Transaction Risk",
            "l2desc": "Both parties assume transaction risks themselves. The platform bears no legal liability for any losses arising from transactions.",
            "l3title": "Liability Cap",
            "l3desc": "If the platform is found liable for any matter, maximum liability shall not exceed the service fee actually collected by the platform in the relevant transaction.",
            "l4title": "Service Interruption",
            "l4desc": "The platform does not guarantee service continuity or stability; the platform bears no responsibility for interruptions due to technical failures or maintenance.",
            "l5title": "Terms Modification",
            "l5desc": "The platform reserves the right to modify terms at any time; modified terms take effect after platform announcement. Continued use constitutes acceptance.",
            "l6title": "Governing Law",
            "l6desc": "These terms are governed by the laws of the Hong Kong Special Administrative Region; any disputes shall be submitted to Hong Kong courts.",
            "infoBox": "If you have any questions about these terms, please contact us through the platform support function. We are committed to providing a fair and safe trading environment for all parties."
        },
        "highlights": {
            "h1title": "Platform Protection",
            "h1desc": "The platform acts as intermediary, providing dispute mediation to protect the reasonable rights of both buyers and sellers.",
            "h2title": "Fair Trading",
            "h2desc": "All bids are legally binding, anti-sniping mechanism ensures fair bidding, and violations are handled appropriately.",
            "h3title": "Time Requirements",
            "h3desc": "Payment within 48 hours of winning, seller ships within 3 business days of payment confirmation; violations will be penalized."
        },
        "cta": {
            "title": "Ready to Start Trading?",
            "desc": "After reading and agreeing to the above terms, you can start buying and selling cards on Boxium PTCG.",
            "browse": "Browse Items",
            "sell": "Start Selling"
        },
        "copyright": "All rights reserved.",
        "privacyLink": "Privacy Policy"
    },
    "ja": {
        "toc": {
            "overview": "プラットフォーム概要",
            "buyNow": "即時購入",
            "auction": "オークション",
            "fees": "手数料",
            "payment": "支払い・精算",
            "shipping": "配送",
            "returns": "返金ポリシー",
            "conduct": "行動規範",
            "liability": "免責事項"
        },
        "back": "前のページに戻る",
        "officialBadge": "BOXIUM TCG 公式規約",
        "heroTitle": "売買規約",
        "heroDesc": "本規約はBoxium PTCGプラットフォーム上のすべての取引（即時購入・オークション）に適用されます。取引前によくお読みください。本プラットフォームの利用は以下の規約への同意を意味します。",
        "lastUpdated": "最終更新：2025年4月",
        "tocTitle": "目次",
        "s1": {
            "title": "1. プラットフォーム概要",
            "intro": "Boxium PTCG（以下「本プラットフォーム」）は、TCG愛好家向けの香港売買プラットフォームで、<strong>即時購入</strong>と<strong>オークション</strong>の2つの取引モードを提供し、安全・便利なカード取引を実現します。",
            "buyNowMode": "即時購入モード",
            "buyNowDesc": "出品者が固定価格を設定し、購入者が即時購入、取引が即時確定。",
            "auctionMode": "オークションモード",
            "auctionDesc": "出品者が開始価格を設定し、入札者が競争、時間終了時の最高入札者が落札。",
            "infoBox": "本プラットフォームのすべての取引は<strong>香港ドル（HKD）</strong>で行われます。出品者はStripe Connectアカウントの設定完了後に商品を出品できます。"
        },
        "s2": {
            "title": "2. 即時購入プロセス",
            "badge": "即時購入",
            "buyerFlow": "購入者フロー",
            "b1title": "閲覧・選択",
            "b1desc": "商品一覧から希望の商品を選び、商品詳細・状態グレード・出品者評価を確認。",
            "b2title": "カートに追加または即時購入",
            "b2desc": "「今すぐ購入」をクリックするかカートに追加してチェックアウト、注文詳細と合計金額を確認。",
            "b3title": "支払い完了",
            "b3desc": "Stripe安全決済ページで支払いを完了、システムが注文を即時確認。",
            "b4title": "受け取り待ち",
            "b4desc": "出品者が発送確認後、合意した受け渡し方法で受け取り完了。",
            "sellerFlow": "出品者フロー",
            "s1title": "商品出品",
            "s1desc": "商品名・状態・シリーズ・価格・写真を入力して審査提出。",
            "s2title": "管理者審査待ち",
            "s2desc": "すべての商品は情報の正確性確保のため、管理者審査後に公開されます。",
            "s3title": "注文処理",
            "s3desc": "注文通知受信後、規定時間内に発送確認と配送手配を行う。",
            "s4title": "入金精算",
            "s4desc": "取引完了後、プラットフォームがサービス料を差し引いた金額を出品者のStripeアカウントに精算。",
            "warningBox": "購入者が支払いを確認した時点で注文が成立します。返金ポリシーに該当する場合を除き、購入者は一方的に注文をキャンセルできません。"
        },
        "s3": {
            "title": "3. オークションプロセス・規約",
            "badge": "オークション",
            "flowTitle": "オークションフロー",
            "a1title": "出品者がオークションを設定",
            "a1desc": "開始価格・オークション期間（3日または7日）・任意の即時購入価格を設定して審査提出。",
            "a2title": "購入者が入札",
            "a2desc": "ログイン後、進行中のオークションに入札可能；各入札は現在の最高入札額を超える必要がある。",
            "a3title": "オークション終了",
            "a3desc": "オークション時間終了時、最高入札者が自動落札。システムが双方に即時通知。",
            "a4title": "支払い・受け渡し",
            "a4desc": "落札者は<strong>48時間以内</strong>に支払いを完了する必要があります。期限超過は落札資格の放棄とみなされます。",
            "rulesTitle": "オークション重要ルール",
            "r1title": "入札は法的拘束力を持つ",
            "r1desc": "入札した時点で購入の約束が成立します。落札後は必ず支払いを完了してください。違反するとアカウントが制限されます。",
            "r2title": "即時購入価格の仕組み",
            "r2desc": "出品者が即時購入価格を設定した場合、購入者はいつでもその価格で購入でき、オークションは即時終了します。",
            "r3title": "自動通知",
            "r3desc": "入札を超えられた場合、システムが自動的に購入者に通知し、再入札の機会を提供します。",
            "r4title": "スナイピング防止機能",
            "r4desc": "オークション終了5分以内に新しい入札があった場合、オークション時間が5分延長され、公平な競争を確保します。",
            "r5title": "オークションキャンセル制限",
            "r5desc": "入札がある場合、出品者はオークションを一方的にキャンセルできません。違反するとプラットフォームの処分を受けます。",
            "r6title": "落札確認",
            "r6desc": "オークション終了後、システムが自動的に落札者に支払いリンクを送信します。通知をご確認ください。",
            "warningBox": "落札者が48時間以内に支払いを完了しない場合、プラットフォームは商品を再出品し、違反アカウントに対して入札資格の制限を含む措置を取ることができます。"
        },
        "s4": {
            "title": "4. プラットフォーム手数料",
            "badge": "重要",
            "intro": "本プラットフォームは<strong>段階的サービス料</strong>を採用しており、取引金額が高いほど料率が低くなります。サービス料は<strong>出品者のみ</strong>に課され、購入者は追加サービス料不要です。",
            "tableTitle": "出品者サービス料率（取引金額基準）",
            "loading": "料率を読み込み中...",
            "tier1": "第1段階",
            "tier2": "第2段階",
            "tier3": "第3段階",
            "tierLabel": "第",
            "rangeBelow": "HKD {{amount}} 以下",
            "rangeAbove": "HKD {{amount}} 以上",
            "example": "成約 HKD {{amount}} → 手数料 HKD {{fee}}、受取 HKD {{receive}}",
            "notesTitle": "補足説明",
            "note1": "サービス料は精算時に自動控除されます。出品者は別途支払い不要です。",
            "note2": "料率は<strong>1件の取引金額</strong>で計算され、累計金額ではありません。",
            "note3": "プラットフォームは料率を変更する権利を保有し、7日前に出品者に告知します。",
            "note4": "購入者の支払い時のStripe決済手数料はプラットフォームが負担し、購入者には請求されません。",
            "successBox": "商品出品とプラットフォーム閲覧は完全無料です。サービス料は取引成功時のみ発生します。"
        },
        "s5": {
            "title": "5. 支払い・精算",
            "buyerPayment": "購入者の支払い",
            "p1title": "対応支払い方法",
            "p1desc": "本プラットフォームはStripeで全決済を処理し、Visa、Mastercard、American Expressなど主要クレジット・デビットカードに対応。",
            "p2title": "支払いセキュリティ",
            "p2desc": "全決済はStripeで暗号化処理され、本プラットフォームはクレジットカード情報を保存しません。",
            "p3title": "支払い期限",
            "p3desc": "即時購入注文は即時支払いが必要；オークション落札後は48時間以内に支払い。",
            "sellerPayout": "出品者精算・支払いプロセス",
            "sp1title": "Stripe Connectアカウント",
            "sp1desc": "出品者は支払いを受け取るためにStripe Connectアカウントを設定・連携する必要があります。",
            "sp2title": "購入者が受取確認",
            "sp2desc": "商品受取後、購入者は注文ページで「受取確認」をクリックする必要があります。発送後14日以内に確認がない場合、システムが自動的に注文を完了します。",
            "sp3title": "48時間クーリング期間",
            "sp3desc": "購入者が受取確認後（またはシステム自動完了後）、資金は<strong>48時間クーリング期間保護</strong>に入ります。この期間中、購入者は商品に関する異議を申し立てることができます。",
            "sp4title": "自動支払い",
            "sp4desc": "クーリング期間終了後、異議がなければシステムが自動的に資金（プラットフォームサービス料控除後）を出品者のStripe Connectアカウントに振り込みます。",
            "sp5title": "異議による支払い保留",
            "sp5desc": "クーリング期間中に購入者が異議を申し立てた場合、異議解決まで資金が凍結されます。",
            "timelineTitle": "支払いタイムライン",
            "tl1step": "購入者が受取確認",
            "tl1sub": "またはシステム自動完了（14日後）",
            "tl2step": "48時間クーリング期間",
            "tl2sub": "購入者が異議申し立て可能",
            "tl3step": "自動支払い",
            "tl3sub": "出品者アカウントへ振込",
            "infoBox": "出品者がStripe Connectアカウントを設定していない場合、設定完了まで資金が保留されます。クーリング期間保護は購入者の権利を守りつつ、異議がない場合の出品者への適時支払いを確保します。"
        },
        "s6": {
            "title": "6. 配送手配",
            "intro": "本プラットフォームは郵送による受け渡しを採用しており、<strong>対面受け渡しと店舗受け取りは対応していません</strong>。購入者はチェックアウト時に以下の配送方法を選択します：",
            "sf": {
                "title": "SF Express（着払い）",
                "desc": "出品者が安全な梱包と発送を担当し、送料はSF Expressが収集し購入者が受取時に支払います。金額は重量と住所によって異なります。"
            },
            "hkpost": {
                "title": "香港郵政（普通郵便）",
                "desc": "出品者が安全な梱包と発送を担当し、HK$10の送料が注文合計に自動加算され、普通郵便で発送されます。"
            },
            "warningBox": "対面受け渡しと店舗受け取りは対応していません。輸送中の商品の損傷または紛失については、双方の協議により責任を解決し、プラットフォームは責任を負いません。"
        },
        "s7": {
            "title": "7. 返金・返品ポリシー",
            "intro": "本プラットフォームの返金ポリシーは購入者の利益保護を前提とし、出品者の合理的な権利も尊重します。",
            "acceptTitle": "返金申請可能な状況",
            "a1title": "商品が説明と大きく異なる",
            "a1desc": "受け取った商品の状態・バージョン・状況が出品者の説明と大きく異なる。",
            "a2title": "破損商品を受け取った",
            "a2desc": "輸送中に商品が破損し、購入者の原因ではない。",
            "a3title": "出品者が発送できなかった",
            "a3desc": "出品者が合理的な説明なしに約束した時間内に配送を手配できなかった。",
            "rejectTitle": "返金不可の状況",
            "r1title": "購入者個人の理由",
            "r1desc": "気が変わった、重複購入、個人的な好みの問題は返金対象外。",
            "r2title": "オークション落札後",
            "r2desc": "オークション成約後は、説明との重大な相違を除き、返金は受け付けません。",
            "r3title": "使用済みまたは改変された商品",
            "r3desc": "購入者が使用、改変、または損傷した商品は返金申請対象外。",
            "infoBox": "商品に問題があり返金を申請する場合は、受取後<strong>48時間以内</strong>にプラットフォームサポートを通じて申請を提出し、証拠（写真など）を提供してください。プラットフォームサポートが返金手続きをサポートします。"
        },
        "s8": {
            "title": "8. ユーザー行動規範",
            "intro": "公平な取引環境を維持するため、すべてのユーザーは以下の行動規範を遵守する必要があります：",
            "c1title": "虚偽説明禁止",
            "c1desc": "出品者は状態・バージョン・真偽を含む虚偽または誤解を招く情報で商品を説明してはなりません。",
            "c2title": "入札操作禁止",
            "c2desc": "複数アカウントまたは他者との共謀によるオークション入札の操作は禁止されています。",
            "c3title": "プラットフォーム外取引禁止",
            "c3desc": "サービス料を回避するためにプラットフォームを迂回した私的取引は禁止されています。",
            "c4title": "嫌がらせ禁止",
            "c4desc": "いかなる形式でも他のユーザーへの嫌がらせ・脅迫・詐欺は禁止されています。",
            "c5title": "誠実な取引",
            "c5desc": "売買双方は誠実かつ誠意を持って各取引を完了する必要があります。",
            "c6title": "迅速な対応",
            "c6desc": "取引双方は合理的な時間内に相手のメッセージや要求に応答する必要があります。",
            "penaltyTitle": "違反ペナルティ制度",
            "penaltyCount": "違反回数",
            "penaltyAction": "ペナルティ",
            "penaltyDuration": "停止期間",
            "p1count": "1回目",
            "p1action": "書面警告、永久記録",
            "p1duration": "停止なし",
            "p2count": "2回目",
            "p2action": "入札資格停止",
            "p2duration": "7日間",
            "p3count": "3回目",
            "p3action": "入札資格停止",
            "p3duration": "30日間",
            "p4count": "4回目以上",
            "p4action": "永久停止、損害賠償請求権留保",
            "p4duration": "永久",
            "warningBox": "行動規範に違反したユーザーは、違反の深刻さに応じて警告・アカウント停止・永久停止の措置を受ける可能性があります。違反記録が誤りと思われる場合は、7営業日以内にプラットフォームサポートに書面で異議申し立てができます。"
        },
        "s9": {
            "title": "9. 免責事項・法的条項",
            "l1title": "プラットフォームの役割",
            "l1desc": "本プラットフォームは取引の仲介者としてのみ機能し、商品の真偽・品質・状態について一切保証しません。",
            "l2title": "取引リスク",
            "l2desc": "売買双方は自ら取引リスクを負います。本プラットフォームは取引から生じるいかなる損失についても法的責任を負いません。",
            "l3title": "賠償上限",
            "l3desc": "本プラットフォームが責任を負うと判断された場合、最大賠償責任は当該取引でプラットフォームが実際に収取したサービス料を超えません。",
            "l4title": "サービス中断",
            "l4desc": "本プラットフォームはサービスの継続性・安定性を保証せず、技術的障害や保守によるサービス中断について責任を負いません。",
            "l5title": "規約変更",
            "l5desc": "本プラットフォームはいつでも規約を変更する権利を保有し、変更後の規約はプラットフォーム告知後に発効します。継続使用は変更への同意を意味します。",
            "l6title": "準拠法",
            "l6desc": "本規約は香港特別行政区の法律に準拠し、紛争は香港の裁判所に提出されます。",
            "infoBox": "本規約についてご不明な点がある場合は、プラットフォームサポート機能を通じてお問い合わせください。売買双方に公平で安全な取引環境を提供することに尽力しています。"
        },
        "highlights": {
            "h1title": "プラットフォーム保護",
            "h1desc": "本プラットフォームは仲介者として紛争調停サービスを提供し、売買双方の合理的な権利を保護します。",
            "h2title": "公平な取引",
            "h2desc": "すべての入札は法的拘束力を持ち、スナイピング防止機能が公平な競争を確保し、違反行為は適切に処理されます。",
            "h3title": "時間要件",
            "h3desc": "落札後48時間以内に支払い、出品者は支払い確認後3営業日以内に発送；期限超過は処分の対象となります。"
        },
        "cta": {
            "title": "取引を始める準備はできましたか？",
            "desc": "上記の規約を読んで同意した後、Boxium PTCGでカードの売買を開始できます。",
            "browse": "商品を見る",
            "sell": "出品を始める"
        },
        "copyright": "全著作権所有。",
        "privacyLink": "プライバシーポリシー"
    }
}

for locale, path in LOCALES.items():
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    data['auctionTerms'] = keys[locale]
    
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"✓ Updated {locale}")

print("\nDone!")
