import json, os

base = "/home/ubuntu/boxium-ptcg/client/src/locales"

new_keys = {
    "profile": {
        "seoTitle": " 的個人頁面 - BOXIUM TCG",
        "seoTitleDefault": "個人頁面 - BOXIUM TCG",
        "seoDescription": "管理您的 BOXIUM TCG 帳戶、查看收藏、關注清單及交易記錄。",
        "accountDeletedSuccess": "帳號已成功刪除",
        "deleteFailed": "刪除失敗",
        "enterEmailToConfirm": "請輸入您的電子郵件地址以確認",
        "deleteAccount": "刪除帳號",
        "deleteAccountDesc": "此操作無法復原，所有資料將被永久刪除",
        "deleteWarning": "此操作無法復原。刪除後，您的所有個人資料、觀察清單、通知及相關記錄將被永久移除。",
        "pleaseNote": "請注意：",
        "deleteNote1": "觀察清單與瀏覽記錄將被刪除",
        "deleteNote2": "通知記錄將被刪除",
        "deleteNote3": "出價與出價記錄將被刪除",
        "deleteNote4": "購物車與收藏清單將被清空",
        "deleteNote5": "您的帳號將無法恢復",
        "dangerZone": "危險區域",
        "passwordChangedSuccess": "密碼已成功修改",
        "changeFailed": "修改失敗",
        "fillAllFields": "請填寫所有欄位",
        "passwordMinLength": "新密碼至少需要 8 個字元",
        "passwordMismatch": "新密碼與確認密碼不一致",
        "changePassword": "修改密碼",
        "changePasswordDesc": "請輸入現有密碼及新密碼以完成修改",
        "currentPassword": "現有密碼",
        "currentPasswordPlaceholder": "請輸入現有密碼",
        "newPasswordPlaceholder": "至少 8 個字元",
        "confirmPasswordPlaceholder": "再次輸入新密碼",
        "confirmChange": "確認修改",
        "profileInfo": "個人資料",
        "profileUpdated": "個人資料已更新",
        "updateFailed": "更新失敗",
        "namePlaceholder": "輸入姓名",
        "phone": "電話",
        "notSet": "未設定",
        "cardTracking": "卡牌追蹤",
        "wishlistTab": "收藏商品",
        "noWishlist": "尚未收藏任何商品",
        "goToMarketplace": "前往市集瀏覽",
        "sortNewest": "最新收藏",
        "sortOldest": "最早收藏",
        "statusActive": "在售",
        "statusSold": "已售出",
        "statusRemoved": "已下架",
        "findSimilar": "尋找同款",
        "defaultAddressLabel": "預設地址",
        "addressDeleted": "地址已刪除",
        "defaultAddressUpdated": "預設地址已更新",
        "enterRecipientName": "請輸入收件人姓名",
        "enterPhone": "請輸入聯繫電話",
        "selectSFStation": "請選擇順豐自提站",
        "sfStationInvalid": "順豐站點編號格式不正確",
        "enterAddress": "請輸入地址",
        "manageAddresses": "管理您的收貨地址，付款時可快速帶入",
        "addAddress": "新增地址",
        "normalAddress": "普通地址",
        "sfPickup": "順豐自提",
        "contactPhone": "聯繫電話",
        "sfStation": "順豐站",
        "sfLocker": "智能櫃",
        "searchStation": "搜尋站點 / 智能櫃",
        "regionFilter": "地區篩選",
        "allRegions": "全部地區",
        "orEnterStationCode": "或直接輸入站點編號",
        "saveChanges": "儲存更改",
        "noOrders": "暫無訂單記錄",
        "goShopping": "前往商城購物",
        "activeOrders": "進行中",
        "searchOrderPlaceholder": "搜尋訂單號或商品名稱...",
        "noOrdersFound": "找不到",
        "noOrdersInStatus": "此狀態暫無訂單",
        "totalOrders": "共 {{count}} 筆訂單",
        "allNotificationsRead": "已標記所有通知為已讀",
        "unreadCount": "{{count}} 則未讀",
        "markAllRead": "全部已讀",
        "unread": "未讀",
        "allTypes": "所有類型",
        "notifTrade": "交易",
        "notifOffer": "出價",
        "notifShipping": "物流",
        "notifDispute": "爭議",
        "notifSystem": "系統",
        "noUnreadNotifs": "沒有未讀通知",
        "noNotifs": "暫無通知",
        "viewDetails": "查看詳情",
        "batchOrders": "訂單批次 · {{count}} 件商品",
        "goToCart": "前往購物車付款",
        "goToMarket": "前往市集",
        "disputeReason": "爭議原因",
        "resolutionResult": "處理結果",
        "courier": "快遞",
        "trackingNo": "追蹤號",
        "collapseDetails": "收起詳情",
        "shippingInfo": "收貨資料",
        "paymentInfo": "付款資料",
        "confirmReceipt": "確認收貨",
        "confirmReceiptDesc": "確認已收到商品並且狀態良好？確認後款項將轉帳給賣家，此操作無法撤銷。",
        "disputeReasonLabel": "爭議原因（至少 10 個字）",
        "uploadEvidence": "上傳佐證（選填，最多 3 個）",
        "rating": "評分",
        "ratingVeryBad": "非常不滿意",
        "ratingBad": "不滿意",
        "ratingOk": "一般",
        "reviewComment": "評語（選填）",
        "offerCancelled": "出價已取消",
        "offerPending": "待回覆",
        "noOffers": "暫無出價記錄",
        "offerMessage": "留言",
        "rejectionReason": "拒絕原因",
        "expires": "到期",
        "cancelOffer": "取消出價",
        "auctionEnded": "已結標",
        "bidLeading": "🏆 領先中",
        "bidOutbid": "⚠️ 被超越",
        "bidWon": "✅ 得標",
        "bidLost": "未得標",
        "viewOrder": "查看訂單",
        "clickToBidAgain": "點擊前往拍賣頁面再次出價",
        "autoCompleteNote": "如未確認收貨，系統將於 {{date}} 自動完成訂單",
        "tradesTab": "交易記錄",
    }
}

en_keys = {
    "profile": {
        "seoTitle": "'s Profile - BOXIUM TCG",
        "seoTitleDefault": "Profile - BOXIUM TCG",
        "seoDescription": "Manage your BOXIUM TCG account, view collections, watchlist, and trade history.",
        "accountDeletedSuccess": "Account deleted successfully",
        "deleteFailed": "Delete failed",
        "enterEmailToConfirm": "Please enter your email address to confirm",
        "deleteAccount": "Delete Account",
        "deleteAccountDesc": "This action cannot be undone, all data will be permanently deleted",
        "deleteWarning": "This action cannot be undone. After deletion, all your personal data, watchlist, notifications, and related records will be permanently removed.",
        "pleaseNote": "Please note:",
        "deleteNote1": "Watchlist and browsing history will be deleted",
        "deleteNote2": "Notification history will be deleted",
        "deleteNote3": "Bids and bid history will be deleted",
        "deleteNote4": "Cart and wishlist will be cleared",
        "deleteNote5": "Your account cannot be recovered",
        "dangerZone": "Danger Zone",
        "passwordChangedSuccess": "Password changed successfully",
        "changeFailed": "Change failed",
        "fillAllFields": "Please fill in all fields",
        "passwordMinLength": "New password must be at least 8 characters",
        "passwordMismatch": "New password and confirmation do not match",
        "changePassword": "Change Password",
        "changePasswordDesc": "Enter your current password and new password to complete the change",
        "currentPassword": "Current Password",
        "currentPasswordPlaceholder": "Enter current password",
        "newPasswordPlaceholder": "At least 8 characters",
        "confirmPasswordPlaceholder": "Re-enter new password",
        "confirmChange": "Confirm Change",
        "profileInfo": "Profile",
        "profileUpdated": "Profile updated",
        "updateFailed": "Update failed",
        "namePlaceholder": "Enter name",
        "phone": "Phone",
        "notSet": "Not set",
        "cardTracking": "Card Tracking",
        "wishlistTab": "Wishlist",
        "noWishlist": "No items in wishlist",
        "goToMarketplace": "Browse Marketplace",
        "sortNewest": "Newest",
        "sortOldest": "Oldest",
        "statusActive": "Active",
        "statusSold": "Sold",
        "statusRemoved": "Removed",
        "findSimilar": "Find Similar",
        "defaultAddressLabel": "Default Address",
        "addressDeleted": "Address deleted",
        "defaultAddressUpdated": "Default address updated",
        "enterRecipientName": "Please enter recipient name",
        "enterPhone": "Please enter phone number",
        "selectSFStation": "Please select SF Express station",
        "sfStationInvalid": "Invalid SF station code format",
        "enterAddress": "Please enter address",
        "manageAddresses": "Manage your shipping addresses for quick checkout",
        "addAddress": "Add Address",
        "normalAddress": "Normal Address",
        "sfPickup": "SF Pickup",
        "contactPhone": "Contact Phone",
        "sfStation": "SF Station",
        "sfLocker": "Smart Locker",
        "searchStation": "Search Station / Smart Locker",
        "regionFilter": "Region Filter",
        "allRegions": "All Regions",
        "orEnterStationCode": "Or enter station code directly",
        "saveChanges": "Save Changes",
        "noOrders": "No orders yet",
        "goShopping": "Go Shopping",
        "activeOrders": "Active",
        "searchOrderPlaceholder": "Search order number or product name...",
        "noOrdersFound": "No orders found for",
        "noOrdersInStatus": "No orders in this status",
        "totalOrders": "{{count}} orders total",
        "allNotificationsRead": "All notifications marked as read",
        "unreadCount": "{{count}} unread",
        "markAllRead": "Mark All Read",
        "unread": "Unread",
        "allTypes": "All Types",
        "notifTrade": "Trade",
        "notifOffer": "Offer",
        "notifShipping": "Shipping",
        "notifDispute": "Dispute",
        "notifSystem": "System",
        "noUnreadNotifs": "No unread notifications",
        "noNotifs": "No notifications",
        "viewDetails": "View Details",
        "batchOrders": "Batch · {{count}} items",
        "goToCart": "Go to Cart",
        "goToMarket": "Go to Marketplace",
        "disputeReason": "Dispute Reason",
        "resolutionResult": "Resolution",
        "courier": "Courier",
        "trackingNo": "Tracking No.",
        "collapseDetails": "Collapse",
        "shippingInfo": "Shipping Info",
        "paymentInfo": "Payment Info",
        "confirmReceipt": "Confirm Receipt",
        "confirmReceiptDesc": "Confirm you have received the item in good condition? Payment will be transferred to the seller after confirmation. This action cannot be undone.",
        "disputeReasonLabel": "Dispute Reason (at least 10 characters)",
        "uploadEvidence": "Upload Evidence (optional, max 3)",
        "rating": "Rating",
        "ratingVeryBad": "Very Dissatisfied",
        "ratingBad": "Dissatisfied",
        "ratingOk": "Neutral",
        "reviewComment": "Comment (optional)",
        "offerCancelled": "Offer cancelled",
        "offerPending": "Pending",
        "noOffers": "No offers yet",
        "offerMessage": "Message",
        "rejectionReason": "Rejection Reason",
        "expires": "Expires",
        "cancelOffer": "Cancel Offer",
        "auctionEnded": "Ended",
        "bidLeading": "🏆 Leading",
        "bidOutbid": "⚠️ Outbid",
        "bidWon": "✅ Won",
        "bidLost": "Lost",
        "viewOrder": "View Order",
        "clickToBidAgain": "Click to bid again on auction page",
        "autoCompleteNote": "If not confirmed, order will auto-complete on {{date}}",
        "tradesTab": "Trade History",
    }
}

ja_keys = {
    "profile": {
        "seoTitle": "のプロフィール - BOXIUM TCG",
        "seoTitleDefault": "プロフィール - BOXIUM TCG",
        "seoDescription": "BOXIUM TCGアカウントを管理し、コレクション、ウォッチリスト、取引履歴を確認。",
        "accountDeletedSuccess": "アカウントが正常に削除されました",
        "deleteFailed": "削除に失敗しました",
        "enterEmailToConfirm": "確認のためメールアドレスを入力してください",
        "deleteAccount": "アカウント削除",
        "deleteAccountDesc": "この操作は元に戻せません。すべてのデータが永久に削除されます",
        "deleteWarning": "この操作は元に戻せません。削除後、すべての個人データ、ウォッチリスト、通知、関連記録が永久に削除されます。",
        "pleaseNote": "注意：",
        "deleteNote1": "ウォッチリストと閲覧履歴が削除されます",
        "deleteNote2": "通知履歴が削除されます",
        "deleteNote3": "入札と入札履歴が削除されます",
        "deleteNote4": "カートとウィッシュリストがクリアされます",
        "deleteNote5": "アカウントは復元できません",
        "dangerZone": "危険ゾーン",
        "passwordChangedSuccess": "パスワードが正常に変更されました",
        "changeFailed": "変更に失敗しました",
        "fillAllFields": "すべての項目を入力してください",
        "passwordMinLength": "新しいパスワードは8文字以上必要です",
        "passwordMismatch": "新しいパスワードと確認パスワードが一致しません",
        "changePassword": "パスワード変更",
        "changePasswordDesc": "現在のパスワードと新しいパスワードを入力してください",
        "currentPassword": "現在のパスワード",
        "currentPasswordPlaceholder": "現在のパスワードを入力",
        "newPasswordPlaceholder": "8文字以上",
        "confirmPasswordPlaceholder": "新しいパスワードを再入力",
        "confirmChange": "変更を確認",
        "profileInfo": "プロフィール",
        "profileUpdated": "プロフィールが更新されました",
        "updateFailed": "更新に失敗しました",
        "namePlaceholder": "名前を入力",
        "phone": "電話",
        "notSet": "未設定",
        "cardTracking": "カード追跡",
        "wishlistTab": "お気に入り商品",
        "noWishlist": "お気に入り商品がありません",
        "goToMarketplace": "マーケットプレイスへ",
        "sortNewest": "最新順",
        "sortOldest": "古い順",
        "statusActive": "販売中",
        "statusSold": "売り切れ",
        "statusRemoved": "削除済み",
        "findSimilar": "類似品を探す",
        "defaultAddressLabel": "デフォルト住所",
        "addressDeleted": "住所が削除されました",
        "defaultAddressUpdated": "デフォルト住所が更新されました",
        "enterRecipientName": "受取人名を入力してください",
        "enterPhone": "電話番号を入力してください",
        "selectSFStation": "SF Expressステーションを選択してください",
        "sfStationInvalid": "SFステーション番号の形式が正しくありません",
        "enterAddress": "住所を入力してください",
        "manageAddresses": "配送先住所を管理し、チェックアウト時に素早く入力できます",
        "addAddress": "住所を追加",
        "normalAddress": "通常住所",
        "sfPickup": "SF受取",
        "contactPhone": "連絡先電話番号",
        "sfStation": "SFステーション",
        "sfLocker": "スマートロッカー",
        "searchStation": "ステーション/スマートロッカーを検索",
        "regionFilter": "地域フィルター",
        "allRegions": "全地域",
        "orEnterStationCode": "またはステーションコードを直接入力",
        "saveChanges": "変更を保存",
        "noOrders": "注文がありません",
        "goShopping": "ショッピングへ",
        "activeOrders": "進行中",
        "searchOrderPlaceholder": "注文番号または商品名を検索...",
        "noOrdersFound": "注文が見つかりません",
        "noOrdersInStatus": "このステータスの注文はありません",
        "totalOrders": "合計 {{count}} 件",
        "allNotificationsRead": "すべての通知を既読にしました",
        "unreadCount": "{{count}} 件未読",
        "markAllRead": "すべて既読",
        "unread": "未読",
        "allTypes": "すべての種類",
        "notifTrade": "取引",
        "notifOffer": "オファー",
        "notifShipping": "配送",
        "notifDispute": "紛争",
        "notifSystem": "システム",
        "noUnreadNotifs": "未読通知なし",
        "noNotifs": "通知なし",
        "viewDetails": "詳細を見る",
        "batchOrders": "バッチ · {{count}} 件",
        "goToCart": "カートへ",
        "goToMarket": "マーケットへ",
        "disputeReason": "紛争理由",
        "resolutionResult": "解決結果",
        "courier": "宅配便",
        "trackingNo": "追跡番号",
        "collapseDetails": "折りたたむ",
        "shippingInfo": "配送情報",
        "paymentInfo": "支払い情報",
        "confirmReceipt": "受取確認",
        "confirmReceiptDesc": "商品を良好な状態で受け取ったことを確認しますか？確認後、支払いが売り手に転送されます。この操作は元に戻せません。",
        "disputeReasonLabel": "紛争理由（10文字以上）",
        "uploadEvidence": "証拠をアップロード（任意、最大3件）",
        "rating": "評価",
        "ratingVeryBad": "非常に不満",
        "ratingBad": "不満",
        "ratingOk": "普通",
        "reviewComment": "コメント（任意）",
        "offerCancelled": "オファーがキャンセルされました",
        "offerPending": "返答待ち",
        "noOffers": "オファーがありません",
        "offerMessage": "メッセージ",
        "rejectionReason": "拒否理由",
        "expires": "有効期限",
        "cancelOffer": "オファーをキャンセル",
        "auctionEnded": "終了",
        "bidLeading": "🏆 リード中",
        "bidOutbid": "⚠️ 上回られた",
        "bidWon": "✅ 落札",
        "bidLost": "落札失敗",
        "viewOrder": "注文を見る",
        "clickToBidAgain": "オークションページで再入札",
        "autoCompleteNote": "未確認の場合、{{date}}に自動完了します",
        "tradesTab": "取引履歴",
    }
}

def deep_merge(base, updates):
    for k, v in updates.items():
        if k in base and isinstance(base[k], dict) and isinstance(v, dict):
            deep_merge(base[k], v)
        else:
            base[k] = v

files = {
    "zh-TW.json": new_keys,
    "en.json": en_keys,
    "ja.json": ja_keys,
}

for fname, keys in files.items():
    fpath = os.path.join(base, fname)
    with open(fpath, encoding='utf-8') as f:
        data = json.load(f)
    deep_merge(data, keys)
    with open(fpath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {fname}")

print("Done!")
