import json, os

base = "/home/ubuntu/boxium-ptcg/client/src/locales"

new_keys = {
    "marketplaceListing": {
        "image": "圖片",
        "clickToZoom": "點擊放大",
        "thumbnail": "縮圖",
        "noConditionData": "暫無",
        "showingAllConditions": "品相的交易數據，以下為所有品相的市場參考價",
        "trendFlat": "持平",
        "vsMarket": "比市場均價",
        "below": "低",
        "above": "高",
        "avgPrice": "均價",
        "dataSource": "數據來源：BOXIUM",
        "allConditionsRef": " · 所有品相（參考）",
        "chartDays": "圖表顯示近 {{days}} 天（共 {{count}} 筆記錄）",
        "viewAllReviews": "查看全部 {{count}} 則評價",
        "otherSellerItems": "同一賣家的其他商品",
        "cannotGetPaymentLink": "無法獲取付款連結",
        "goToPayment": "前往付款",
        "seoCondition": "商品狀況",
        "seoPrice": "價格",
        "verifyFailed": "驗證失敗",
        "uploadFailed": "上傳失敗",
        "officialSeller": "🏻 BOXIUM 官方",
        "privateSeller": "👤 個人賣家",
        "otherTCG": "其他 TCG",
        "stock": "庫存",
        "pieces": "件",
        "totalSold": "已售 {{count}} 件",
        "viewProfile": "查看主頁",
        "orderNo": "訂單號",
        "disputeInProgress": "此商品正在爭議處理中",
        "disputeDesc": "管理員正在處理相關爭議，商品暫時無法購買",
        "loginToBuy1": "請先",
        "loginToBuy2": "才能購買",
        "offerAmount": "出價金額",
        "offerExpires": "出價將於",
        "expires": "到期",
        "makeOffer": "出價洽議",
        "loginToOffer": "請先登入才能出價",
        "shareWhatsApp": "WhatsApp 分享",
        "copyLink": "複製連結",
        "reportItem": "舉報此商品",
        "orderSubmitted": "訂單已提交",
        "disputeNoBuy": "爭議處理中，暫時無法購買",
        "offer": "出價",
        "paymentAmount": "付款金額",
        "alipayQR": "支付寶 HK QR Code",
        "openAlipayMobile": "在手機上開啟支付寶 HK",
        "detailedAddress": "詳細地址",
        "district": "地區",
        "region": "區域",
        "requiredFields": "* 必填欄位。如不需要寄送可跳過。",
        "requiredFieldsSeller": "* 必填欄位。收貨地址將提供給賣家安排寄送。",
        "nextUploadScreenshot": "下一步：上傳截圖",
        "uploadAlipayScreenshotDesc": "請上傳支付寶 HK 的付款成功截圖，系統將自動驗證金額是否一致。",
        "paymentScreenshot": "付款截圖",
        "aiVerifying": "AI 正在驗證付款金額...",
        "allVerified": "三項驗",
        "verifyIncomplete": "驗證未完全",
        "payee": "收款方",
        "amount": "金額",
        "status": "狀態",
        "unrecognized": "未識別",
        "aiConfidence": "AI 信心度",
        "high": "高",
        "medium": "中",
        "low": "低",
        "reuploadScreenshot": "重新上傳截圖",
        "clickToUpload": "點擊上傳截圖",
        "supportedFormats": "支援 JPG、PNG，最大 5MB",
        "confirmPaidWarning": "⚠️ 如確認已付款，可繼續提交",
        "manualReviewNote": "訂單將標記為「待人工核對」，管理員將在 1-2 個工作天內確認。",
        "marketPrice": "市價",
        "minOffer": "最低可出價",
        "offerAmountLabel": "出價金額（HKD）",
        "offerAmountPlaceholder": "請輸入出價金額",
        "offerMinWarning": "出價金額不能低於定價的 70%（最低 HKD {{min}}）",
        "offerMessage": "留言（可選）",
        "offerMessagePlaceholder": "可以說明出價原因或其他要求...",
        "submitOffer": "送出出價",
        "reportReason": "舉報原因",
        "selectReportReason": "請選擇舉報原因",
        "reportFake": "假貨 / 詐騙",
        "reportWrongDesc": "商品與描述不符",
        "reportProhibited": "禁售商品",
        "reportScam": "詐騙行為",
        "reportDetails": "詳細說明（可選）",
        "reportDetailsPlaceholder": "請詳述舉報原因...",
        "submitReport": "提交舉報",
        "addToCartFailed": "加入購物車失敗",
        "loginToCart": "登入後加入購物車",
        "inCartPending": "已在購物車（待付款）",
        "inCart": "已在購物車",
        "goToCartPay": "前往購物車付款",
        "adding": "加入中...",
        "added": "已加入✓",
        "addToCartPay": "加入購物車付款",
        "validLocker": "✓ 有效智能櫃編號",
        "validStation": "✓ 有效順豐站編號",
        "payment": {
            "redirecting": "正在跳轉至付款頁面..."
        },
        "cond": {
            "psa8_below": "PSA 8以下",
            "psa8_below_short": "PSA8以下",
            "bgs8_below": "BGS 9以下",
            "bgs8_below_short": "BGS9以下",
            "ars9": "ARS9",
            "ars8_below": "ARS8以下"
        },
        "boxiumMarketPrice": "BOXIUM 市場成交價",
        "loading": "載入中...",
        "noRecentTransactions": "暫無近期成交記錄",
        "viewDetailedChart": "查看詳細圖表",
        "chart": {
            "insufficientData": "數據不足，無法顯示圖表"
        },
        "trend7d": "7天趨勢",
        "productImage": "商品圖片",
        "address": {
            "region": {
                "hongkong": "香港（不指定）"
            }
        }
    }
}

en_keys = {
    "marketplaceListing": {
        "image": "Image",
        "clickToZoom": "Click to zoom",
        "thumbnail": "Thumbnail",
        "noConditionData": "No transaction data for",
        "showingAllConditions": "condition, showing all conditions as reference",
        "trendFlat": "Flat",
        "vsMarket": "vs market avg",
        "below": "lower",
        "above": "higher",
        "avgPrice": "Avg Price",
        "dataSource": "Data source: BOXIUM",
        "allConditionsRef": " · All conditions (reference)",
        "chartDays": "Chart shows last {{days}} days ({{count}} records)",
        "viewAllReviews": "View all {{count}} reviews",
        "otherSellerItems": "Other items from this seller",
        "cannotGetPaymentLink": "Cannot get payment link",
        "goToPayment": "Go to Payment",
        "seoCondition": "Condition",
        "seoPrice": "Price",
        "verifyFailed": "Verification failed",
        "uploadFailed": "Upload failed",
        "officialSeller": "🏻 BOXIUM Official",
        "privateSeller": "👤 Private Seller",
        "otherTCG": "Other TCG",
        "stock": "Stock",
        "pieces": "pcs",
        "totalSold": "{{count}} sold",
        "viewProfile": "View Profile",
        "orderNo": "Order No.",
        "disputeInProgress": "This item is under dispute",
        "disputeDesc": "Admin is handling the dispute, item temporarily unavailable",
        "loginToBuy1": "Please",
        "loginToBuy2": "to purchase",
        "offerAmount": "Offer Amount",
        "offerExpires": "Offer expires at",
        "expires": "",
        "makeOffer": "Make Offer",
        "loginToOffer": "Login to make an offer",
        "shareWhatsApp": "Share on WhatsApp",
        "copyLink": "Copy Link",
        "reportItem": "Report Item",
        "orderSubmitted": "Order submitted",
        "disputeNoBuy": "Under dispute, unavailable",
        "offer": "Offer",
        "paymentAmount": "Payment Amount",
        "alipayQR": "Alipay HK QR Code",
        "openAlipayMobile": "Open Alipay HK on mobile",
        "detailedAddress": "Detailed Address",
        "district": "District",
        "region": "Region",
        "requiredFields": "* Required fields. Skip if no shipping needed.",
        "requiredFieldsSeller": "* Required fields. Address will be provided to seller.",
        "nextUploadScreenshot": "Next: Upload Screenshot",
        "uploadAlipayScreenshotDesc": "Upload your Alipay HK payment success screenshot for verification.",
        "paymentScreenshot": "Payment Screenshot",
        "aiVerifying": "AI is verifying payment amount...",
        "allVerified": "All verified",
        "verifyIncomplete": "Verification incomplete",
        "payee": "Payee",
        "amount": "Amount",
        "status": "Status",
        "unrecognized": "Unrecognized",
        "aiConfidence": "AI Confidence",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "reuploadScreenshot": "Re-upload Screenshot",
        "clickToUpload": "Click to upload screenshot",
        "supportedFormats": "Supports JPG, PNG, max 5MB",
        "confirmPaidWarning": "⚠️ If payment confirmed, you may proceed",
        "manualReviewNote": "Order will be marked as 'Pending Review'. Admin will confirm within 1-2 business days.",
        "marketPrice": "Market Price",
        "minOffer": "Min. offer",
        "offerAmountLabel": "Offer Amount (HKD)",
        "offerAmountPlaceholder": "Enter offer amount",
        "offerMinWarning": "Offer cannot be less than 70% of listing price (min HKD {{min}})",
        "offerMessage": "Message (optional)",
        "offerMessagePlaceholder": "Explain your offer or add requirements...",
        "submitOffer": "Submit Offer",
        "reportReason": "Report Reason",
        "selectReportReason": "Select report reason",
        "reportFake": "Fake / Scam",
        "reportWrongDesc": "Item doesn't match description",
        "reportProhibited": "Prohibited item",
        "reportScam": "Scam behavior",
        "reportDetails": "Details (optional)",
        "reportDetailsPlaceholder": "Describe the report reason...",
        "submitReport": "Submit Report",
        "addToCartFailed": "Failed to add to cart",
        "loginToCart": "Login to add to cart",
        "inCartPending": "In cart (pending payment)",
        "inCart": "In cart",
        "goToCartPay": "Go to cart to pay",
        "adding": "Adding...",
        "added": "Added ✓",
        "addToCartPay": "Add to cart & pay",
        "validLocker": "✓ Valid locker code",
        "validStation": "✓ Valid station code",
        "payment": {
            "redirecting": "Redirecting to payment page..."
        },
        "cond": {
            "psa8_below": "PSA 8 or below",
            "psa8_below_short": "PSA8-",
            "bgs8_below": "BGS 9 or below",
            "bgs8_below_short": "BGS9-",
            "ars9": "ARS9",
            "ars8_below": "ARS8 or below"
        },
        "boxiumMarketPrice": "BOXIUM Market Price",
        "loading": "Loading...",
        "noRecentTransactions": "No recent transactions",
        "viewDetailedChart": "View detailed chart",
        "chart": {
            "insufficientData": "Insufficient data to display chart"
        },
        "trend7d": "7-day trend",
        "productImage": "Product Image",
        "address": {
            "region": {
                "hongkong": "Hong Kong (Any)"
            }
        }
    }
}

ja_keys = {
    "marketplaceListing": {
        "image": "画像",
        "clickToZoom": "クリックで拡大",
        "thumbnail": "サムネイル",
        "noConditionData": "取引データなし",
        "showingAllConditions": "コンディションのデータがないため、全コンディションを表示",
        "trendFlat": "横ばい",
        "vsMarket": "市場平均比",
        "below": "安い",
        "above": "高い",
        "avgPrice": "平均価格",
        "dataSource": "データソース：BOXIUM",
        "allConditionsRef": " · 全コンディション（参考）",
        "chartDays": "直近{{days}}日のチャート（{{count}}件）",
        "viewAllReviews": "全{{count}}件のレビューを見る",
        "otherSellerItems": "同じ出品者の他の商品",
        "cannotGetPaymentLink": "支払いリンクを取得できません",
        "goToPayment": "支払いへ進む",
        "seoCondition": "コンディション",
        "seoPrice": "価格",
        "verifyFailed": "検証失敗",
        "uploadFailed": "アップロード失敗",
        "officialSeller": "🏻 BOXIUM公式",
        "privateSeller": "👤 個人出品者",
        "otherTCG": "その他TCG",
        "stock": "在庫",
        "pieces": "個",
        "totalSold": "{{count}}個販売済み",
        "viewProfile": "プロフィールを見る",
        "orderNo": "注文番号",
        "disputeInProgress": "この商品は紛争処理中です",
        "disputeDesc": "管理者が紛争を処理中です。商品は一時的に購入できません",
        "loginToBuy1": "",
        "loginToBuy2": "購入するにはログインしてください",
        "offerAmount": "提案金額",
        "offerExpires": "提案は",
        "expires": "に期限切れ",
        "makeOffer": "価格交渉",
        "loginToOffer": "提案するにはログインしてください",
        "shareWhatsApp": "WhatsAppでシェア",
        "copyLink": "リンクをコピー",
        "reportItem": "商品を報告",
        "orderSubmitted": "注文が送信されました",
        "disputeNoBuy": "紛争処理中、購入不可",
        "offer": "提案",
        "paymentAmount": "支払金額",
        "alipayQR": "Alipay HK QRコード",
        "openAlipayMobile": "モバイルでAlipay HKを開く",
        "detailedAddress": "詳細住所",
        "district": "地区",
        "region": "地域",
        "requiredFields": "* 必須項目。配送不要の場合はスキップ可。",
        "requiredFieldsSeller": "* 必須項目。住所は出品者に提供されます。",
        "nextUploadScreenshot": "次へ：スクリーンショットをアップロード",
        "uploadAlipayScreenshotDesc": "Alipay HKの支払い成功スクリーンショットをアップロードしてください。",
        "paymentScreenshot": "支払いスクリーンショット",
        "aiVerifying": "AIが支払い金額を確認中...",
        "allVerified": "3項目確認済み",
        "verifyIncomplete": "確認未完了",
        "payee": "受取人",
        "amount": "金額",
        "status": "ステータス",
        "unrecognized": "認識不可",
        "aiConfidence": "AI信頼度",
        "high": "高",
        "medium": "中",
        "low": "低",
        "reuploadScreenshot": "スクリーンショットを再アップロード",
        "clickToUpload": "クリックしてアップロード",
        "supportedFormats": "JPG・PNG対応、最大5MB",
        "confirmPaidWarning": "⚠️ 支払い確認済みの場合は続行できます",
        "manualReviewNote": "注文は「手動確認待ち」としてマークされます。1-2営業日以内に確認します。",
        "marketPrice": "市場価格",
        "minOffer": "最低提案価格",
        "offerAmountLabel": "提案金額（HKD）",
        "offerAmountPlaceholder": "提案金額を入力",
        "offerMinWarning": "提案金額は定価の70%以上（最低HKD {{min}}）",
        "offerMessage": "メッセージ（任意）",
        "offerMessagePlaceholder": "提案理由や要望を入力...",
        "submitOffer": "提案を送信",
        "reportReason": "報告理由",
        "selectReportReason": "報告理由を選択",
        "reportFake": "偽物 / 詐欺",
        "reportWrongDesc": "商品説明と異なる",
        "reportProhibited": "禁止商品",
        "reportScam": "詐欺行為",
        "reportDetails": "詳細（任意）",
        "reportDetailsPlaceholder": "報告理由を詳しく説明...",
        "submitReport": "報告を送信",
        "addToCartFailed": "カートへの追加に失敗しました",
        "loginToCart": "ログインしてカートに追加",
        "inCartPending": "カートに追加済み（支払い待ち）",
        "inCart": "カートに追加済み",
        "goToCartPay": "カートで支払う",
        "adding": "追加中...",
        "added": "追加済み ✓",
        "addToCartPay": "カートに追加して支払う",
        "validLocker": "✓ 有効なロッカーコード",
        "validStation": "✓ 有効なステーションコード",
        "payment": {
            "redirecting": "支払いページへリダイレクト中..."
        },
        "cond": {
            "psa8_below": "PSA 8以下",
            "psa8_below_short": "PSA8以下",
            "bgs8_below": "BGS 9以下",
            "bgs8_below_short": "BGS9以下",
            "ars9": "ARS9",
            "ars8_below": "ARS8以下"
        },
        "boxiumMarketPrice": "BOXIUM市場価格",
        "loading": "読み込み中...",
        "noRecentTransactions": "最近の取引なし",
        "viewDetailedChart": "詳細チャートを見る",
        "chart": {
            "insufficientData": "データ不足でチャートを表示できません"
        },
        "trend7d": "7日間トレンド",
        "productImage": "商品画像",
        "address": {
            "region": {
                "hongkong": "香港（指定なし）"
            }
        }
    }
}

def deep_merge(base, new):
    for k, v in new.items():
        if k in base and isinstance(base[k], dict) and isinstance(v, dict):
            deep_merge(base[k], v)
        elif k not in base:
            base[k] = v

files = {
    "zh-TW.json": new_keys,
    "en.json": en_keys,
    "ja.json": ja_keys,
}

for fname, keys in files.items():
    fpath = os.path.join(base, fname)
    with open(fpath, encoding='utf-8') as f:
        data = json.load(f)
    deep_merge(data, keys)
    with open(fpath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Updated {fname}")

print("Done!")
