#!/usr/bin/env python3
"""Add all missing translation keys to locale files."""
import json

BASE = '/home/ubuntu/boxium-ptcg/client/src/locales'

def deep_merge(base, updates):
    for k, v in updates.items():
        if k in base and isinstance(base[k], dict) and isinstance(v, dict):
            deep_merge(base[k], v)
        else:
            base[k] = v

# ── zh-TW keys ────────────────────────────────────────────────────────────────
zh_tw = {
    'marquee': {
        'title': '最新上架商品',
        'itemsForSale': '共 {{count}} 件商品在售',
    },
    'searchResults': {
        'seo': {
            'title': '搜尋 TCG 卡牌價格 - BOXIUM 市場格價平台',
            'titleWithQuery': '搜尋「{{query}}」的 TCG 卡牌價格 - BOXIUM 市場格價平台',
            'descWithQuery': '在 BOXIUM 搜尋「{{query}}」相關的 TCG 卡牌，查看 PSA 10 價格、SNKRDUNK 交易記錄和市場趨勢分析。',
            'keywordsWithQuery': '{{query}},TCG 卡牌,集換式卡牌,PSA 10,卡牌價格,SNKRDUNK,市場格價',
        },
        'header': {
            'titleWithQuery': '搜尋「{{query}}」的 TCG 卡牌價格',
            'title': '搜尋 TCG 卡牌價格',
            'found': '找到 {{count}} 張卡牌',
        },
        'pagination': {
            'pageInfo': '第 {{page}} 頁 / 共 {{total}} 頁（總共 {{count}} 張卡牌）',
            'showing': '顯示 {{from}}-{{to}} 張',
        },
        'card': {
            'imageAlt': '卡牌圖像',
            'sealedProduct': '卡盒',
        },
        'noResults': {
            'withQuery': '找不到「{{query}}」相符的卡牌',
            'empty': '請輸入搜尋關鍵字',
        },
        'suggestions': {
            'finding': '正在尋找相似搜尋',
            'didYouMean': '您是否想搜尋：',
        },
    },
    'register': {
        'resendSuccess': '驗證電郵已重新發送！',
        'resendFailed': '發送失敗，請稍後再試',
        'verifyTitle': '請驗證您的電郵地址',
        'verifyDesc': '我們已發送驗證電郵至',
        'verifyInstruction': '請查看您的收件箱（包括垃圾郵件），點擊驗證連結完成帳號啟用。驗證連結將於 24 小時後過期。',
        'resendCooldown': '重新發送（{{seconds}} 秒後）',
        'resendButton': '重新發送驗證電郵',
        'subtitle': '創建您的 BOXIUM TCG 帳號',
        'passwordHint': '至少 8 個字符，包含大小寫字母和數字',
        'submit': '註冊',
        'hasAccount': '已經有帳號？',
        'agreePrivacy': '註冊即表示你同意我們的',
        'privacyPolicy': '隱私政策',
    },
    'common': {
        'backToLogin': '返回登入',
        'loginNow': '立即登入',
        'registering': '註冊中...',
        'sending': '發送中...',
        'prevPage': '上一頁',
        'nextPage': '下一頁',
        'backToHome': '返回首頁',
        'backToSearch': '返回搜尋',
        'backToMarket': '返回市集',
        'addToCart': '加入購物車',
        'buyNow': '立即購買',
        'cancel': '取消',
        'confirm': '確認',
        'clear': '清除',
        'delete': '刪除',
        'loading': '載入中...',
        'uploading': '上傳中...',
        'submitting': '提交中...',
        'viewDetails': '查看詳情',
        'viewAll': '查看全部',
        'readMore': '閱讀更多',
        'back': '返回',
        'prevStep': '上一步',
        'nextStep': '下一步',
        'addToWishlist': '加入收藏',
        'addedToWishlist': '已加入收藏',
        'share': '分享',
        'wishlist': '收藏',
    },
    'about': {
        'title': '關於 BOXIUM',
        'subtitle': 'BOXIUM 是一個專為集換式卡牌（TCG）愛好者打造的市場格價平台',
        'mission': {'title': '我們的使命'},
        'contact': {'title': '聯絡我們'},
    },
    'setBrowse': {
        'searchPlaceholder': '搜尋系列...',
        'allSeries': '所有系列',
        'noResults': '沒有找到符合的系列',
        'cardCount': '卡牌數量',
        'cards': '張卡牌',
    },
    'pricingSearch': {
        'placeholder': '搜尋卡牌...',
        'results': '搜尋結果',
        'noResults': '找不到相符的卡牌',
        'latestPrice': '最新價格',
        'noPrice': '無價格資料',
    },
    'pricingDetail': {
        'priceTrend': '價格走勢',
        'highPrice': '最高價',
        'lowPrice': '最低價',
        'avgPrice': '平均價',
        'transactions': '成交記錄',
        'noTransactions': '暫無成交記錄',
        'date': '日期',
        'price': '價格',
        'source': '來源',
        'grade': '等級',
    },
    'marketplace': {
        'sold': '已售出',
        'outOfStock': '庫存不足',
        'sellerInfo': '賣家資訊',
        'description': '商品描述',
        'details': '商品詳情',
        'shippingInfo': '運費說明',
        'notFound': '找不到此商品',
        'unlisted': '此商品已下架',
        'condition': '品相',
        'rating': '評價',
        'sales': '筆成交',
        'quantity': '數量',
        'subtotal': '小計',
        'confirmPurchase': '確認購買',
    },
    'grading': {
        'submitTitle': '送評申請',
        'submit': '提交送評',
        'confirmSubmit': '確認提交',
        'cardInfo': '卡牌資訊',
        'serviceLevel': '送評等級',
        'contactInfo': '聯絡資訊',
        'paymentMethod': '付款方式',
        'summary': '申請摘要',
        'selectCard': '選擇卡牌',
        'cardName': '卡牌名稱',
        'cardNumber': '卡牌編號',
        'cardSet': '卡牌系列',
        'quantity': '數量',
        'notes': '備註',
        'name': '姓名',
        'phone': '電話',
        'address': '地址',
        'fee': '送評費用',
        'total': '合計',
        'success': '申請成功',
        'failed': '申請失敗',
    },
    'cardSelection': {
        'title': '選擇卡牌',
        'searchPlaceholder': '搜尋卡牌...',
        'noResults': '找不到相符的卡牌',
        'confirmSelect': '確認選擇',
        'selected': '已選擇',
    },
    'cardPicker': {
        'title': '選擇卡牌',
        'searchPlaceholder': '搜尋卡牌...',
        'noResults': '找不到相符的卡牌',
        'confirmSelect': '確認選擇',
    },
    'dispute': {
        'uploadImage': '上傳圖片',
        'uploadVideo': '上傳影片',
        'fileTooLarge': '檔案過大',
        'unsupportedFormat': '不支援的檔案格式',
        'maxFilesError': '最多上傳 10 個檔案',
        'images': '張圖片',
        'videos': '個影片',
    },
    'batch': {
        'processing': '處理中...',
        'completed': '✨ 完成！',
        'failed': '失敗',
        'paused': '已暫停',
        'title': '批次任務進度',
        'total': '共',
        'items': '項',
        'success': '成功',
        'error': '錯誤',
        'batchUpdate': '批量更新',
    },
    'unsubscribe': {
        'title': '取消訂閱',
        'success': '已成功取消訂閱',
        'failed': '取消訂閱失敗',
        'loading': '處理中...',
        'backToHome': '返回首頁',
    },
    'topicCluster': {
        'title': '主題群組',
        'notFound': '找不到主題',
        'relatedArticles': '相關文章',
    },
}

# ── en keys ────────────────────────────────────────────────────────────────────
en = {
    'marquee': {
        'title': 'Latest Listings',
        'itemsForSale': '{{count}} items for sale',
    },
    'searchResults': {
        'seo': {
            'title': 'Search TCG Card Prices - BOXIUM Market Price Platform',
            'titleWithQuery': 'Search "{{query}}" TCG Card Prices - BOXIUM',
            'descWithQuery': 'Search BOXIUM for "{{query}}" TCG cards, check PSA 10 prices, SNKRDUNK transaction records and market trend analysis.',
            'keywordsWithQuery': '{{query}},TCG cards,trading card game,PSA 10,card prices,SNKRDUNK,market prices',
        },
        'header': {
            'titleWithQuery': 'TCG Card Prices for "{{query}}"',
            'title': 'Search TCG Card Prices',
            'found': 'Found {{count}} cards',
        },
        'pagination': {
            'pageInfo': 'Page {{page}} of {{total}} ({{count}} cards total)',
            'showing': 'Showing {{from}}-{{to}}',
        },
        'card': {
            'imageAlt': 'card image',
            'sealedProduct': 'Box',
        },
        'noResults': {
            'withQuery': 'No cards found for "{{query}}"',
            'empty': 'Please enter a search keyword',
        },
        'suggestions': {
            'finding': 'Finding similar searches',
            'didYouMean': 'Did you mean:',
        },
    },
    'register': {
        'resendSuccess': 'Verification email resent!',
        'resendFailed': 'Failed to send, please try again later',
        'verifyTitle': 'Please verify your email address',
        'verifyDesc': 'We have sent a verification email to',
        'verifyInstruction': 'Please check your inbox (including spam), click the verification link to activate your account. The link expires in 24 hours.',
        'resendCooldown': 'Resend ({{seconds}}s)',
        'resendButton': 'Resend Verification Email',
        'subtitle': 'Create your BOXIUM TCG account',
        'passwordHint': 'At least 8 characters, including uppercase, lowercase and numbers',
        'submit': 'Register',
        'hasAccount': 'Already have an account?',
        'agreePrivacy': 'By registering you agree to our',
        'privacyPolicy': 'Privacy Policy',
    },
    'common': {
        'backToLogin': 'Back to Login',
        'loginNow': 'Login Now',
        'registering': 'Registering...',
        'sending': 'Sending...',
        'prevPage': 'Previous',
        'nextPage': 'Next',
        'backToHome': 'Back to Home',
        'backToSearch': 'Back to Search',
        'backToMarket': 'Back to Market',
        'addToCart': 'Add to Cart',
        'buyNow': 'Buy Now',
        'cancel': 'Cancel',
        'confirm': 'Confirm',
        'clear': 'Clear',
        'delete': 'Delete',
        'loading': 'Loading...',
        'uploading': 'Uploading...',
        'submitting': 'Submitting...',
        'viewDetails': 'View Details',
        'viewAll': 'View All',
        'readMore': 'Read More',
        'back': 'Back',
        'prevStep': 'Previous Step',
        'nextStep': 'Next Step',
        'addToWishlist': 'Add to Wishlist',
        'addedToWishlist': 'Added to Wishlist',
        'share': 'Share',
        'wishlist': 'Wishlist',
    },
    'about': {
        'title': 'About BOXIUM',
        'subtitle': 'BOXIUM is a market price platform built for TCG enthusiasts',
        'mission': {'title': 'Our Mission'},
        'contact': {'title': 'Contact Us'},
    },
    'setBrowse': {
        'searchPlaceholder': 'Search sets...',
        'allSeries': 'All Series',
        'noResults': 'No matching sets found',
        'cardCount': 'Card Count',
        'cards': 'cards',
    },
    'pricingSearch': {
        'placeholder': 'Search cards...',
        'results': 'Search Results',
        'noResults': 'No matching cards found',
        'latestPrice': 'Latest Price',
        'noPrice': 'No price data',
    },
    'pricingDetail': {
        'priceTrend': 'Price Trend',
        'highPrice': 'High',
        'lowPrice': 'Low',
        'avgPrice': 'Average',
        'transactions': 'Transaction History',
        'noTransactions': 'No transaction records',
        'date': 'Date',
        'price': 'Price',
        'source': 'Source',
        'grade': 'Grade',
    },
    'marketplace': {
        'sold': 'Sold',
        'outOfStock': 'Out of Stock',
        'sellerInfo': 'Seller Info',
        'description': 'Description',
        'details': 'Product Details',
        'shippingInfo': 'Shipping Info',
        'notFound': 'Product not found',
        'unlisted': 'This product has been unlisted',
        'condition': 'Condition',
        'rating': 'Rating',
        'sales': 'sales',
        'quantity': 'Quantity',
        'subtotal': 'Subtotal',
        'confirmPurchase': 'Confirm Purchase',
    },
    'grading': {
        'submitTitle': 'Grading Submission',
        'submit': 'Submit for Grading',
        'confirmSubmit': 'Confirm Submission',
        'cardInfo': 'Card Information',
        'serviceLevel': 'Service Level',
        'contactInfo': 'Contact Information',
        'paymentMethod': 'Payment Method',
        'summary': 'Application Summary',
        'selectCard': 'Select Card',
        'cardName': 'Card Name',
        'cardNumber': 'Card Number',
        'cardSet': 'Card Set',
        'quantity': 'Quantity',
        'notes': 'Notes',
        'name': 'Name',
        'phone': 'Phone',
        'address': 'Address',
        'fee': 'Grading Fee',
        'total': 'Total',
        'success': 'Application submitted successfully',
        'failed': 'Application failed',
    },
    'cardSelection': {
        'title': 'Select Card',
        'searchPlaceholder': 'Search cards...',
        'noResults': 'No matching cards found',
        'confirmSelect': 'Confirm Selection',
        'selected': 'Selected',
    },
    'cardPicker': {
        'title': 'Select Card',
        'searchPlaceholder': 'Search cards...',
        'noResults': 'No matching cards found',
        'confirmSelect': 'Confirm Selection',
    },
    'dispute': {
        'uploadImage': 'Upload Image',
        'uploadVideo': 'Upload Video',
        'fileTooLarge': 'File too large',
        'unsupportedFormat': 'Unsupported file format',
        'maxFilesError': 'Maximum 10 files allowed',
        'images': 'images',
        'videos': 'videos',
    },
    'batch': {
        'processing': 'Processing...',
        'completed': '✨ Completed!',
        'failed': 'Failed',
        'paused': 'Paused',
        'title': 'Batch Task Progress',
        'total': 'Total',
        'items': 'items',
        'success': 'Success',
        'error': 'Error',
        'batchUpdate': 'Batch Update',
    },
    'unsubscribe': {
        'title': 'Unsubscribe',
        'success': 'Successfully unsubscribed',
        'failed': 'Failed to unsubscribe',
        'loading': 'Processing...',
        'backToHome': 'Back to Home',
    },
    'topicCluster': {
        'title': 'Topic Cluster',
        'notFound': 'Topic not found',
        'relatedArticles': 'related articles',
    },
}

# ── ja keys ────────────────────────────────────────────────────────────────────
ja = {
    'marquee': {
        'title': '最新出品',
        'itemsForSale': '{{count}} 件出品中',
    },
    'searchResults': {
        'seo': {
            'title': 'TCGカード価格検索 - BOXIUM マーケット価格プラットフォーム',
            'titleWithQuery': '「{{query}}」のTCGカード価格検索 - BOXIUM',
            'descWithQuery': 'BOXIUMで「{{query}}」関連のTCGカードを検索、PSA 10価格やSNKRDUNK取引記録を確認。',
            'keywordsWithQuery': '{{query}},TCGカード,トレーディングカード,PSA 10,カード価格,SNKRDUNK,市場価格',
        },
        'header': {
            'titleWithQuery': '「{{query}}」のTCGカード価格',
            'title': 'TCGカード価格検索',
            'found': '{{count}}枚のカードが見つかりました',
        },
        'pagination': {
            'pageInfo': '{{page}} / {{total}} ページ（合計 {{count}} 枚）',
            'showing': '{{from}}-{{to}} 枚を表示',
        },
        'card': {
            'imageAlt': 'カード画像',
            'sealedProduct': 'ボックス',
        },
        'noResults': {
            'withQuery': '「{{query}}」に一致するカードが見つかりません',
            'empty': '検索キーワードを入力してください',
        },
        'suggestions': {
            'finding': '類似検索を探しています',
            'didYouMean': 'もしかして：',
        },
    },
    'register': {
        'resendSuccess': '確認メールを再送しました！',
        'resendFailed': '送信失敗、後でもう一度お試しください',
        'verifyTitle': 'メールアドレスを確認してください',
        'verifyDesc': '確認メールを送信しました',
        'verifyInstruction': '受信トレイ（迷惑メールを含む）を確認し、確認リンクをクリックしてアカウントを有効化してください。リンクは24時間後に期限切れになります。',
        'resendCooldown': '再送（{{seconds}}秒後）',
        'resendButton': '確認メールを再送',
        'subtitle': 'BOXIUM TCGアカウントを作成',
        'passwordHint': '8文字以上、大文字・小文字・数字を含む',
        'submit': '登録',
        'hasAccount': 'すでにアカウントをお持ちですか？',
        'agreePrivacy': '登録することで、当社の',
        'privacyPolicy': 'プライバシーポリシー',
    },
    'common': {
        'backToLogin': 'ログインに戻る',
        'loginNow': 'ログイン',
        'registering': '登録中...',
        'sending': '送信中...',
        'prevPage': '前へ',
        'nextPage': '次へ',
        'backToHome': 'ホームに戻る',
        'backToSearch': '検索に戻る',
        'backToMarket': 'マーケットに戻る',
        'addToCart': 'カートに追加',
        'buyNow': '今すぐ購入',
        'cancel': 'キャンセル',
        'confirm': '確認',
        'clear': 'クリア',
        'delete': '削除',
        'loading': '読み込み中...',
        'uploading': 'アップロード中...',
        'submitting': '送信中...',
        'viewDetails': '詳細を見る',
        'viewAll': 'すべて見る',
        'readMore': '続きを読む',
        'back': '戻る',
        'prevStep': '前のステップ',
        'nextStep': '次のステップ',
        'addToWishlist': 'ウィッシュリストに追加',
        'addedToWishlist': 'ウィッシュリストに追加済み',
        'share': 'シェア',
        'wishlist': 'ウィッシュリスト',
    },
    'about': {
        'title': 'BOXIUMについて',
        'subtitle': 'BOXIUMはTCGファンのための市場価格プラットフォームです',
        'mission': {'title': '私たちのミッション'},
        'contact': {'title': 'お問い合わせ'},
    },
    'setBrowse': {
        'searchPlaceholder': 'セットを検索...',
        'allSeries': 'すべてのシリーズ',
        'noResults': '一致するセットが見つかりません',
        'cardCount': 'カード数',
        'cards': '枚',
    },
    'pricingSearch': {
        'placeholder': 'カードを検索...',
        'results': '検索結果',
        'noResults': '一致するカードが見つかりません',
        'latestPrice': '最新価格',
        'noPrice': '価格データなし',
    },
    'pricingDetail': {
        'priceTrend': '価格推移',
        'highPrice': '最高値',
        'lowPrice': '最安値',
        'avgPrice': '平均価格',
        'transactions': '取引履歴',
        'noTransactions': '取引記録なし',
        'date': '日付',
        'price': '価格',
        'source': 'ソース',
        'grade': 'グレード',
    },
    'marketplace': {
        'sold': '売り切れ',
        'outOfStock': '在庫不足',
        'sellerInfo': '出品者情報',
        'description': '商品説明',
        'details': '商品詳細',
        'shippingInfo': '配送情報',
        'notFound': '商品が見つかりません',
        'unlisted': 'この商品は削除されました',
        'condition': 'コンディション',
        'rating': '評価',
        'sales': '件の取引',
        'quantity': '数量',
        'subtotal': '小計',
        'confirmPurchase': '購入確認',
    },
    'grading': {
        'submitTitle': 'グレーディング申請',
        'submit': 'グレーディング申請',
        'confirmSubmit': '申請確認',
        'cardInfo': 'カード情報',
        'serviceLevel': 'サービスレベル',
        'contactInfo': '連絡先情報',
        'paymentMethod': '支払い方法',
        'summary': '申請概要',
        'selectCard': 'カードを選択',
        'cardName': 'カード名',
        'cardNumber': 'カード番号',
        'cardSet': 'カードセット',
        'quantity': '数量',
        'notes': 'メモ',
        'name': '名前',
        'phone': '電話番号',
        'address': '住所',
        'fee': 'グレーディング費用',
        'total': '合計',
        'success': '申請成功',
        'failed': '申請失敗',
    },
    'cardSelection': {
        'title': 'カードを選択',
        'searchPlaceholder': 'カードを検索...',
        'noResults': '一致するカードが見つかりません',
        'confirmSelect': '選択を確認',
        'selected': '選択済み',
    },
    'cardPicker': {
        'title': 'カードを選択',
        'searchPlaceholder': 'カードを検索...',
        'noResults': '一致するカードが見つかりません',
        'confirmSelect': '選択を確認',
    },
    'dispute': {
        'uploadImage': '画像をアップロード',
        'uploadVideo': '動画をアップロード',
        'fileTooLarge': 'ファイルが大きすぎます',
        'unsupportedFormat': 'サポートされていないファイル形式',
        'maxFilesError': '最大10ファイルまでアップロード可能',
        'images': '枚の画像',
        'videos': '本の動画',
    },
    'batch': {
        'processing': '処理中...',
        'completed': '✨ 完了！',
        'failed': '失敗',
        'paused': '一時停止',
        'title': 'バッチタスクの進捗',
        'total': '合計',
        'items': '件',
        'success': '成功',
        'error': 'エラー',
        'batchUpdate': '一括更新',
    },
    'unsubscribe': {
        'title': '配信停止',
        'success': '配信停止しました',
        'failed': '配信停止に失敗しました',
        'loading': '処理中...',
        'backToHome': 'ホームに戻る',
    },
    'topicCluster': {
        'title': 'トピッククラスター',
        'notFound': 'トピックが見つかりません',
        'relatedArticles': '関連記事',
    },
}

# Apply updates
for lang, updates in [('zh-TW', zh_tw), ('en', en), ('ja', ja)]:
    path = f'{BASE}/{lang}.json'
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    deep_merge(data, updates)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'Updated {lang}.json')

print('All locale files updated successfully!')
