path = "/home/ubuntu/boxium-ptcg/client/src/pages/OrderDetail.tsx"
with open(path, encoding='utf-8') as f:
    content = f.read()

replacements = [
    # State initialization
    ('region: "香港"', 'region: t("orderDetail.hongKong")'),
    # Error toasts
    ('e.message || "無法獲取付款連結"', 'e.message || t("orderDetail.errorGetCheckout")'),
    ('e.message || "無法切換付款方式"', 'e.message || t("orderDetail.errorSwitchPayment")'),
    ('e.message || "提交失敗，請重試"', 'e.message || t("common.submitFailed")'),
    ('"驗證失敗：" + e.message', 't("orderDetail.verifyFailed") + e.message'),
    # PayOrderButton UI
    ('<CreditCard className="w-4 h-4 mr-2" />前往付款', '<CreditCard className="w-4 h-4 mr-2" />{t("orderDetail.goToPay")}'),
    ('alipayStep === "select" ? "選擇付款方式" : alipayStep === "done" ? "訂單已提交" : "支付寶 HK 付款"',
     'alipayStep === "select" ? t("orderDetail.selectPayMethod") : alipayStep === "done" ? t("orderDetail.orderSubmitted") : t("orderDetail.alipayHkPay")'),
    ('<span className="text-white font-bold text-lg">支</span>', '<span className="text-white font-bold text-lg">{t("orderDetail.alipayChar")}</span>'),
    ('<p className="text-sm text-gray-500">請揃描 QR Code 或點擊連結付款</p>', '<p className="text-sm text-gray-500">{t("orderDetail.scanQrOrClick")}</p>'),
    ('<Smartphone className="w-4 h-4" />在手機上開啟支付寶 HK', '<Smartphone className="w-4 h-4" />{t("orderDetail.openAlipayOnPhone")}'),
    ('<Copy className="w-3 h-3" />複製編號', '<Copy className="w-3 h-3" />{t("orderDetail.copyId")}'),
    ('"我已完成付款，上傳截圖" : "我已完成付款，填寫收貨地址"',
     't("orderDetail.paidUploadScreenshot") : t("orderDetail.paidEnterAddress")'),
    ('<p className="text-xs mt-1 text-gray-500">收貨地址將提供給賣家安排寄送</p>',
     '<p className="text-xs mt-1 text-gray-500">{t("orderDetail.addressForSeller")}</p>'),
    ('<Label>收件人姓名 *</Label>', '<Label>{t("orderDetail.recipientName")} *</Label>'),
    ('<Label>聯絡電話 *</Label>', '<Label>{t("orderDetail.contactPhone")} *</Label>'),
    ('<Label>詳細地址 *</Label>', '<Label>{t("orderDetail.detailedAddress")} *</Label>'),
    ('<Label>區域</Label>', '<Label>{t("orderDetail.region")}</Label>'),
    ('<option value={t("orderDetail.hongKong")}>香港（不指定）</option>',
     '<option value={t("orderDetail.hongKong")}>{t("orderDetail.hongKongAny")}</option>'),
    ('<p className="text-xs text-gray-400">* 必填欄位。如不需要寄送可跳過。</p>',
     '<p className="text-xs text-gray-400">{t("orderDetail.requiredFields")}</p>'),
    ('下一步：上傳截圖', '{t("orderDetail.nextUploadScreenshot")}'),
    ('<p className="font-bold text-[#06038D]">付款金額：HKD {parseFloat(amount).toFixed(2)}</p>',
     '<p className="font-bold text-[#06038D]">{t("orderDetail.paymentAmount")}：HKD {parseFloat(amount).toFixed(2)}</p>'),
    # Verify result labels
    ('`收款方：${verifyResult.detectedPayee ?? "未識別"}${!ver',
     '`${t("orderDetail.payee")}：${verifyResult.detectedPayee ?? t("orderDetail.unrecognized")}${!ver'),
    ('"未識別"', 't("orderDetail.unrecognized")'),
    ('`金額：${verifyResult.currency ?? "HKD"} ${verifyRe',
     '`${t("orderDetail.amount")}：${verifyResult.currency ?? "HKD"} ${verifyRe'),
    ('`狀態：${verifyResult.detectedStatus ?? "未識別"}${!ve',
     '`${t("orderDetail.status")}：${verifyResult.detectedStatus ?? t("orderDetail.unrecognized")}${!ve'),
    ('<p className="text-sm text-gray-500">點擊上傳截圖</p>', '<p className="text-sm text-gray-500">{t("orderDetail.clickToUploadScreenshot")}</p>'),
    ('<p className="text-xs text-gray-400 mt-1">支援 JPG、PNG，最大 5MB</p>',
     '<p className="text-xs text-gray-400 mt-1">{t("orderDetail.screenshotHint")}</p>'),
    ('<p className="font-medium">⚠️ 如確認已付款，可繼續提交</p>',
     '<p className="font-medium">{t("orderDetail.ifConfirmedPaid")}</p>'),
    ('<p className="mt-1">訂單將標記為「待人工核對」，管理員將在 1-2 個工作天內確認。</p>',
     '<p className="mt-1">{t("orderDetail.manualReviewNote")}</p>'),
    ('{submitProofMutation.isPending ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" />提交中...</> : canSub',
     '{submitProofMutation.isPending ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" />{t("common.submitting")}</> : canSub'),
    ('<p className="font-bold text-lg text-[#06038D]">訂單已提交！</p>',
     '<p className="font-bold text-lg text-[#06038D]">{t("orderDetail.orderSubmittedTitle")}</p>'),
    ('<p className="text-sm text-gray-500">我們將在核對收款後確認你的訂單，通常需要 1-2 個工作天。</p>',
     '<p className="text-sm text-gray-500">{t("orderDetail.orderSubmittedDesc")}</p>'),
    ('<Button className="w-full bg-[#06038D] hover:bg-[#0804b8] text-white" onClick={resetAndClose}>關閉</Button>',
     '<Button className="w-full bg-[#06038D] hover:bg-[#0804b8] text-white" onClick={resetAndClose}>{t("common.close")}</Button>'),
    # Shipping methods map
    ('sf_express: { label: "順豐速運 (SF Express)"', 'sf_express: { label: t("orderDetail.sfExpress")'),
    ('hk_post: { label: "香港郵政 (HK Post)"', 'hk_post: { label: t("orderDetail.hkPost")'),
    ('hkpost: { label: "香港郵政 (HK Post)"', 'hkpost: { label: t("orderDetail.hkPost")'),
    ('chunghwa_post: { label: "中華郵政"', 'chunghwa_post: { label: t("orderDetail.chunghwaPost")'),
    ('black_cat: { label: "黑貓宅急"', 'black_cat: { label: t("orderDetail.blackCat")'),
    ('other: { label: "其他"', 'other: { label: t("orderDetail.other")'),
    ('if (!shippingMethod) return "快遞";', 'if (!shippingMethod) return t("orderDetail.courier");'),
    # Status labels map - these are at module level so need to be functions
    # Order status badges
    ('pending_payment: { label: "待付款"', 'pending_payment: { label: t("orders.status.pending_payment")'),
    ('paid_held: { label: "已付款，等待出貨"', 'paid_held: { label: t("orders.status.paid_held")'),
    ('payment_received: { label: "已收款"', 'payment_received: { label: t("orders.status.payment_received")'),
    ('processing: { label: "處理中"', 'processing: { label: t("orders.status.processing")'),
    ('shipped: { label: "已出貨"', 'shipped: { label: t("orders.status.shipped")'),
    ('delivered: { label: "已送達"', 'delivered: { label: t("orders.status.delivered")'),
    ('completed: { label: "已完成"', 'completed: { label: t("orders.status.completed")'),
    ('cancelled: { label: "已取消"', 'cancelled: { label: t("orders.status.cancelled")'),
    ('disputed: { label: "爭議中"', 'disputed: { label: t("orders.status.disputed")'),
    # Timeline steps
    ('{ key: "pending_payment", label: "訂單建立"', '{ key: "pending_payment", label: t("orderDetail.timeline.orderCreated")'),
    ('{ key: "payment_received", label: "付款確認"', '{ key: "payment_received", label: t("orderDetail.timeline.paymentConfirmed")'),
    ('{ key: "processing", label: "賣家處理中"', '{ key: "processing", label: t("orderDetail.timeline.sellerProcessing")'),
    ('{ key: "shipped", label: "已出貨"', '{ key: "shipped", label: t("orderDetail.timeline.shipped")'),
    ('{ key: "completed", label: "確認收貨"', '{ key: "completed", label: t("orderDetail.timeline.completed")'),
    # Order cancelled
    ('<p className="text-sm text-gray-500">此訂單已被取消</p>',
     '<p className="text-sm text-gray-500">{t("orderDetail.orderCancelled")}</p>'),
    ('<p className="text-sm text-red-500">管理員將在 1-3 個工作天內處理</p>',
     '<p className="text-sm text-red-500">{t("orderDetail.adminWillProcess")}</p>'),
    ('<p className="text-xs font-medium text-red-700 mb-1">爭議原因：</p>',
     '<p className="text-xs font-medium text-red-700 mb-1">{t("orderDetail.disputeReason")}：</p>'),
    ('<p className="text-sm font-semibold text-orange-900">提交證據可加快處理</p>',
     '<p className="text-sm font-semibold text-orange-900">{t("orderDetail.submitEvidenceTitle")}</p>'),
    ('<p className="text-xs text-orange-700 mt-0.5">上傳商品照片、對話截圖等證據，有助管理員在 1 個工作天內更快裁決。</p>',
     '<p className="text-xs text-orange-700 mt-0.5">{t("orderDetail.submitEvidenceDesc")}</p>'),
    ('<span>📤</span> 前往上傳爭議證據', '<span>📤</span> {t("orderDetail.goUploadEvidence")}'),
    ('<p className="text-xs font-semibold text-green-700">處理結果：</p>',
     '<p className="text-xs font-semibold text-green-700">{t("orderDetail.disputeResult")}：</p>'),
    # Tracking
    ('追蹤號：<span className="font-mono font-bold">{order.trackingNumber}</span>',
     '{t("orderDetail.trackingNo")}：<span className="font-mono font-bold">{order.trackingNumber}</span>'),
    ('toast.success("追蹤號已複製")', 'toast.success(t("orderDetail.trackingCopied"))'),
    ('系統將於 {new Date(order.autoCompleteAt).toLocaleDateString("zh-HK")} 自動完成',
     '{t("orderDetail.autoCompleteOn")} {new Date(order.autoCompleteAt).toLocaleDateString("zh-HK")}'),
    # Alipay proof timeline
    ('<p className="text-xs font-medium text-gray-700">截圖已提交</p>',
     '<p className="text-xs font-medium text-gray-700">{t("orderDetail.screenshotSubmitted")}</p>'),
    ('<p className="text-xs font-medium text-yellow-700">截圖審核中</p>',
     '<p className="text-xs font-medium text-yellow-700">{t("orderDetail.screenshotReviewing")}</p>'),
    ('<p className="text-xs text-gray-400">管理員將盡快核對，通常在 24 小時內完成</p>',
     '<p className="text-xs text-gray-400">{t("orderDetail.reviewWithin24h")}</p>'),
    ('<p className="text-xs font-medium text-green-700">截圖已核准</p>',
     '<p className="text-xs font-medium text-green-700">{t("orderDetail.screenshotApproved")}</p>'),
    ('<p className="text-xs text-gray-400">付款已確認，賣家將開始處理訂單</p>',
     '<p className="text-xs text-gray-400">{t("orderDetail.paymentConfirmedSellerProcessing")}</p>'),
    ('<p className="text-xs font-medium text-red-700">截圖已拒絕</p>',
     '<p className="text-xs font-medium text-red-700">{t("orderDetail.screenshotRejected")}</p>'),
    ('<p className="text-xs text-gray-400">請重新上傳正確的付款截圖</p>',
     '<p className="text-xs text-gray-400">{t("orderDetail.reuploadScreenshot")}</p>'),
    # Toast messages
    ('toast.success("❌ 訂單已取消")', 'toast.success(t("orderDetail.orderCancelledToast"))'),
    ('toast.success("✅ 已確認收貨，款項將轉帳給賣家")', 'toast.success(t("orderDetail.confirmedDelivery"))'),
    ('e.message || "上傳失敗，請重試"', 'e.message || t("common.uploadFailed")'),
    ('"驗證失敗：" + e.message', 't("orderDetail.verifyFailed") + e.message'),
    ('toast.success("⚠️ 爭議申請已提交，管理員將盡快處理")', 'toast.success(t("orderDetail.disputeSubmitted"))'),
    ('toast.error("最多可上傳 3 張截圖")', 'toast.error(t("orderDetail.maxScreenshots"))'),
    ('if (file.size > 5 * 1024 * 1024) { toast.error("圖片不能超過 5MB"); continue; }',
     'if (file.size > 5 * 1024 * 1024) { toast.error(t("orderDetail.imageTooLarge5MB")); continue; }'),
    ('toast.success(`已上傳 ${newUrls.length} 張截圖`)', 'toast.success(t("orderDetail.uploadedScreenshots", { count: newUrls.length }))'),
    ('toast.error("上傳失敗，請重試")', 'toast.error(t("common.uploadFailed"))'),
    ('toast.success("📦 已確認出貨，買家將收到通知")', 'toast.success(t("orderDetail.shippedConfirmed"))'),
    ('if (file.size > 10 * 1024 * 1024) { toast.error("圖片不能超過 10MB"); return; }',
     'if (file.size > 10 * 1024 * 1024) { toast.error(t("orderDetail.imageTooLarge10MB")); return; }'),
    ('toast.success("出貨憑證已上傳")', 'toast.success(t("orderDetail.shippingProofUploaded"))'),
    ('} catch { toast.error("圖片上傳失敗，請重試"); }', '} catch { toast.error(t("common.uploadFailed")); }'),
    ('toast.success("⭐ 評價已提交，感謝你的反饋！")', 'toast.success(t("orderDetail.reviewSubmitted"))'),
    ('<p className="font-medium text-gray-700">訂單不存在或無權查看</p>',
     '<p className="font-medium text-gray-700">{t("orderDetail.notFound")}</p>'),
    ('toast.success("訂單號已複製")', 'toast.success(t("orderDetail.orderNoCopied"))'),
    ('<ArrowLeft className="w-4 h-4 mr-1" />返回訂單', '<ArrowLeft className="w-4 h-4 mr-1" />{t("orderDetail.backToOrders")}'),
    # Auction order notice
    ('<p className="text-xs font-bold text-[#06038D]">拍賣得標訂單</p>',
     '<p className="text-xs font-bold text-[#06038D]">{t("orderDetail.auctionWonOrder")}</p>'),
    # Countdown
    ('<p className="text-[10px] text-amber-500">剩餘時間</p>',
     '<p className="text-[10px] text-amber-500">{t("orderDetail.timeRemaining")}</p>'),
    ('<p className="text-xs text-red-700 font-medium">付款時限已到，訂單即將自動取消</p>',
     '<p className="text-xs text-red-700 font-medium">{t("orderDetail.paymentExpired")}</p>'),
    # Payout hold
    ("'💰 賣家即將收到款項' : '放款冷靜期中'",
     "t('orderDetail.sellerReceivingSoon') : t('orderDetail.payoutCooldown')"),
    ("? '冷靜期已結束，系統正在處理放款給賣家'",
     "? t('orderDetail.cooldownEndedProcessing')"),
    ('<p className="text-[10px] text-blue-500">小時</p>',
     '<p className="text-[10px] text-blue-500">{t("common.hours")}</p>'),
    ('⚠️ 如商品有問題，請於冷靜期內申請爭議，放款後將無法退款。',
     '{t("orderDetail.disputeBeforePayout")}'),
    # Buttons
    ('<ShoppingCart className="w-4 h-4 mr-2" />前往購物車付款',
     '<ShoppingCart className="w-4 h-4 mr-2" />{t("orderDetail.goToCartPay")}'),
    ('<XCircle className="w-4 h-4 mr-1.5" />取消訂單', '<XCircle className="w-4 h-4 mr-1.5" />{t("orderDetail.cancelOrder")}'),
    ('<Package className="w-3.5 h-3.5" />付款已成功，等待賣家出貨中...',
     '<Package className="w-3.5 h-3.5" />{t("orderDetail.waitingForShipment")}'),
    ('<Truck className="w-4 h-4 mr-1.5" />確認出貨', '<Truck className="w-4 h-4 mr-1.5" />{t("orderDetail.confirmShipment")}'),
    ('<span className="text-xs text-gray-500">買家已付款，請盡快安排出貨</span>',
     '<span className="text-xs text-gray-500">{t("orderDetail.buyerPaidPleaseShip")}</span>'),
    ('<Flag className="w-3.5 h-3.5" />等待管理員處理中，請勿重複提交等待回覆',
     '<Flag className="w-3.5 h-3.5" />{t("orderDetail.waitingAdminProcess")}'),
    ('<CheckCircle className="w-4 h-4 mr-1.5" />確認收貨', '<CheckCircle className="w-4 h-4 mr-1.5" />{t("orderDetail.confirmDelivery")}'),
    ('<Flag className="w-4 h-4 mr-1.5" />申請爭議', '<Flag className="w-4 h-4 mr-1.5" />{t("orderDetail.applyDispute")}'),
    ('<p className="text-[10px] text-red-500">還有 {disputeDaysLeft} 天可申請</p>',
     '<p className="text-[10px] text-red-500">{t("orderDetail.disputeDaysLeft", { days: disputeDaysLeft })}</p>'),
    ('<p className="text-xs text-gray-500 self-center">爭議申請期限已過（7 天）</p>',
     '<p className="text-xs text-gray-500 self-center">{t("orderDetail.disputeExpired")}</p>'),
    ('<Star className="w-4 h-4 mr-1.5" />評價賣家', '<Star className="w-4 h-4 mr-1.5" />{t("orderDetail.rateSeller")}'),
    # Review
    ('已評價 {review.rating} 星', '{t("orderDetail.ratedStars", { rating: review.rating })}'),
    # Alipay proof status
    ('<p className="font-semibold text-amber-800 text-sm">截圖審核中</p>',
     '<p className="font-semibold text-amber-800 text-sm">{t("orderDetail.screenshotReviewing")}</p>'),
    ('<p className="text-amber-700 text-xs mt-1">管理員正在核對您的付款截圖，通常在 1 個工作日內完成。</p>',
     '<p className="text-amber-700 text-xs mt-1">{t("orderDetail.reviewingDesc")}</p>'),
    ('<p className="font-semibold text-green-800 text-sm">截圖已核准 ✅</p>',
     '<p className="font-semibold text-green-800 text-sm">{t("orderDetail.screenshotApprovedTitle")}</p>'),
    ('<p className="text-green-700 text-xs mt-1">您的付款截圖已通過管理員審核，付款已確認完成。</p>',
     '<p className="text-green-700 text-xs mt-1">{t("orderDetail.screenshotApprovedDesc")}</p>'),
    ('<p className="font-semibold text-red-800 text-sm">付款截圖已被拒絕</p>',
     '<p className="font-semibold text-red-800 text-sm">{t("orderDetail.screenshotRejectedTitle")}</p>'),
    ('<p className="text-red-700 text-xs mt-1">管理員拒絕原因：{(order as any).paymentRejectionReason}</p>',
     '<p className="text-red-700 text-xs mt-1">{t("orderDetail.rejectionReason")}：{(order as any).paymentRejectionReason}</p>'),
    ('<p className="text-red-600 text-xs mt-1">請重新上傳正確的付款截圖。</p>',
     '<p className="text-red-600 text-xs mt-1">{t("orderDetail.reuploadScreenshot")}</p>'),
    ('<span>🔄</span> 重新上傳付款截圖', '<span>🔄</span> {t("orderDetail.reuploadScreenshotBtn")}'),
    # Order progress
    ('<ShieldCheck className="w-4 h-4" style={{ color: "#06038d" }} />訂單進度',
     '<ShieldCheck className="w-4 h-4" style={{ color: "#06038d" }} />{t("orderDetail.orderProgress")}'),
    ('{ key: "pending_payment", label: "待付款" },', '{ key: "pending_payment", label: t("orderDetail.timeline.pendingPayment") },'),
    ('{ key: "paid_held", label: "付款確認" },', '{ key: "paid_held", label: t("orderDetail.timeline.paymentConfirmed") },'),
    ('{ key: "shipped", label: "已出貨" },', '{ key: "shipped", label: t("orderDetail.timeline.shipped") },'),
    ('{ key: "completed", label: "已完成" },', '{ key: "completed", label: t("orderDetail.timeline.completed") },'),
    # Logistics section
    ('<p className="font-medium text-indigo-900 text-sm">物流資訊</p>',
     '<p className="font-medium text-indigo-900 text-sm">{t("orderDetail.logisticsInfo")}</p>'),
    ('追蹤號：<span className="font-mono font-bold">{order.trackingNumber}</span>',
     '{t("orderDetail.trackingNo")}：<span className="font-mono font-bold">{order.trackingNumber}</span>'),
    ('點擊查詢追蹤狀態', '{t("orderDetail.clickToTrack")}'),
    ('出貨時間：{new Date(order.shippedAt)', '{t("orderDetail.shippedAt")}：{new Date(order.shippedAt)'),
    ('<p className="text-xs font-medium text-indigo-700">自動確認收貨倒計時</p>',
     '<p className="text-xs font-medium text-indigo-700">{t("orderDetail.autoCompleteCountdown")}</p>'),
    ('{autoCompleteCountdown.days > 0 && `${autoCompleteCountdown.days} 天 `}',
     '{autoCompleteCountdown.days > 0 && `${autoCompleteCountdown.days} ${t("common.days")} `}'),
    ('{autoCompleteCountdown.hours} 小時 {autoCompleteCountdown.minutes} 分鐘',
     '{autoCompleteCountdown.hours} {t("common.hours")} {autoCompleteCountdown.minutes} {t("common.minutes")}'),
    ('如未手動確認，系統將於 {new Date(order.autoCompleteAt).toLocaleDateString("zh-HK")} 自動完成訂單',
     '{t("orderDetail.autoCompleteNote")} {new Date(order.autoCompleteAt).toLocaleDateString("zh-HK")}'),
    # Shipping proof
    ('<p className="font-semibold text-sm" style={{ color: "#06038d" }}>賣家出貨憑證</p>',
     '<p className="font-semibold text-sm" style={{ color: "#06038d" }}>{t("orderDetail.sellerShippingProof")}</p>'),
    ('alt="出貨憑證"', 'alt={t("orderDetail.shippingProofAlt")}'),
    ('點擊放大查看', '{t("orderDetail.clickToEnlarge")}'),
    ('<p className="text-xs text-indigo-600 mt-2">賣家已上傳出貨憑證圖片，如有疑問請聯絡客服。</p>',
     '<p className="text-xs text-indigo-600 mt-2">{t("orderDetail.shippingProofUploaded")}</p>'),
    # External links
    ('<ExternalLink className="w-3 h-3 mr-1" />查看', '<ExternalLink className="w-3 h-3 mr-1" />{t("common.view")}'),
    # Shipping address
    ('<h2 className="font-semibold mb-3 text-sm uppercase tracking-wide" style={{ color: "#06038d" }}>收貨資料</h2>',
     '<h2 className="font-semibold mb-3 text-sm uppercase tracking-wide" style={{ color: "#06038d" }}>{t("orderDetail.shippingAddress")}</h2>'),
    ("shippingAddr.sfStationCode.startsWith('H') ? '順豐智能櫃' : '順豐站'",
     "shippingAddr.sfStationCode.startsWith('H') ? t('orderDetail.sfLocker') : t('orderDetail.sfStation')"),
    # Payment summary
    ('<h2 className="font-semibold mb-3 text-sm uppercase tracking-wide" style={{ color: "#06038d" }}>付款摘要</h2>',
     '<h2 className="font-semibold mb-3 text-sm uppercase tracking-wide" style={{ color: "#06038d" }}>{t("orderDetail.paymentSummary")}</h2>'),
    ('<span className="text-gray-500">商品金額</span>', '<span className="text-gray-500">{t("orderDetail.itemAmount")}</span>'),
    ('<span className="text-gray-500">送貨方式</span>', '<span className="text-gray-500">{t("orderDetail.shippingMethod")}</span>'),
    ("order.shippingMethod === 'sf_express' ? '🚚 順豐速運（運費到付）' :",
     "order.shippingMethod === 'sf_express' ? `🚚 ${t('orderDetail.sfExpressCollect')}` :"),
    ("order.shippingMethod === 'hk_post' ? '📮 香港郵政（平郵）' :",
     "order.shippingMethod === 'hk_post' ? `📮 ${t('orderDetail.hkPostSurface')}` :"),
    ("order.shippingMethod ? order.shippingMethod : '未設定'",
     "order.shippingMethod ? order.shippingMethod : t('orderDetail.notSet')"),
    ('order.paymentMethod === "alipay_hk" ? "支付寶 HK" : "Stripe 信用卡"',
     'order.paymentMethod === "alipay_hk" ? t("orderDetail.alipayHk") : t("orderDetail.stripeCard")'),
    ('order.paymentStatus === "paid" ? "已付款" : order.paymentStatus === "pending" ? "待付款" : order.paymentStatu',
     'order.paymentStatus === "paid" ? t("orderDetail.paid") : order.paymentStatus === "pending" ? t("orderDetail.pendingPayment") : order.paymentStatu'),
    ('<span className="text-xs font-medium text-amber-800">支付寶 HK 退款狀態</span>',
     '<span className="text-xs font-medium text-amber-800">{t("orderDetail.alipayRefundStatus")}</span>'),
    ("(order as any).alipayRefundStatus === 'completed' ? '已退款' :",
     "(order as any).alipayRefundStatus === 'completed' ? t('orderDetail.refunded') :"),
    ("(order as any).alipayRefundStatus === 'processing' ? '退款處理中' : '待退款'",
     "(order as any).alipayRefundStatus === 'processing' ? t('orderDetail.refundProcessing') : t('orderDetail.pendingRefund')"),
    ('<p className="text-xs text-amber-700">退款金額：HKD {parseFloat((order as any).alipayRefundAmount).toFixed(',
     '<p className="text-xs text-amber-700">{t("orderDetail.refundAmount")}：HKD {parseFloat((order as any).alipayRefundAmount).toFixed('),
    ('<p className="text-xs text-green-700">退款完成時間：{new Date((order as any).alipayRefundCompletedAt).toLocal',
     '<p className="text-xs text-green-700">{t("orderDetail.refundCompletedAt")}：{new Date((order as any).alipayRefundCompletedAt).toLocal'),
    ('<span>總計</span>', '<span>{t("orderDetail.total")}</span>'),
    ('<span>本訂單適用第 {tier} 級費率（{ratePercent}%）</span>',
     '<span>{t("orderDetail.feeTier", { tier, rate: ratePercent })}</span>'),
    ('<span>賣家實收</span>', '<span>{t("orderDetail.sellerReceives")}</span>'),
    ('<p className="text-xs text-gray-500 font-medium">支付寶 HK 付款截圖</p>',
     '<p className="text-xs text-gray-500 font-medium">{t("orderDetail.alipayScreenshot")}</p>'),
    ('<Loader2 className="w-3 h-3 animate-spin" />截圖審核中',
     '<Loader2 className="w-3 h-3 animate-spin" />{t("orderDetail.screenshotReviewing")}'),
    ('<XCircle className="w-3 h-3" />已被拒絕', '<XCircle className="w-3 h-3" />{t("orderDetail.rejected")}'),
    # Cancel dialog
    ('只有「待付款」狀態的訂單可以取消。付款後如需退款請申請爭議。',
     '{t("orderDetail.cancelNote")}'),
    ('<p className="text-sm font-medium">取消原因（選填）</p>',
     '<p className="text-sm font-medium">{t("orderDetail.cancelReason")}</p>'),
    ('placeholder="請說明取消原因，例如：誤購、不需要等"',
     'placeholder={t("orderDetail.cancelReasonPlaceholder")}'),
    ('<Button variant="outline" onClick={() => setShowCancelDialog(false)}>保留訂單</Button>',
     '<Button variant="outline" onClick={() => setShowCancelDialog(false)}>{t("orderDetail.keepOrder")}</Button>'),
    (': <><Loader2 className="w-4 h-4 mr-2 animate-spin" />處理中...</>',
     ': <><Loader2 className="w-4 h-4 mr-2 animate-spin" />{t("common.processing")}</>'),
    (': <><XCircle className="w-4 h-4 mr-2" />確認取消</>}',
     ': <><XCircle className="w-4 h-4 mr-2" />{t("orderDetail.confirmCancel")}</>}'),
    # Confirm delivery dialog
    ('<p className="text-sm text-muted-foreground">確認已收到商品後，款項將立即轉帳給賣家。此操作不可撤銷。</p>',
     '<p className="text-sm text-muted-foreground">{t("orderDetail.confirmDeliveryNote")}</p>'),
    ('請確認商品狀態與描述相符後再確認收貨。如有問題，請先申請爭議。',
     '{t("orderDetail.confirmDeliveryWarning")}'),
    # Dispute dialog
    ('<p className="text-sm text-muted-foreground">請詳細描述問題，管理員將在 1-3 個工作天內處理。</p>',
     '<p className="text-sm text-muted-foreground">{t("orderDetail.disputeNote")}</p>'),
    ('placeholder="請描述問題，例如：商品與描述不符、未收到商品、商品損壞等（至少 10 字）"',
     'placeholder={t("orderDetail.disputePlaceholder")}'),
    ('<p className="text-xs text-red-500">還需輸入 {10 - disputeReason.trim().length} 個字</p>',
     '<p className="text-xs text-red-500">{t("orderDetail.disputeNeedMore", { count: 10 - disputeReason.trim().length })}</p>'),
    ('<p className="text-xs text-green-600">✓ 內容已符合要求</p>',
     '<p className="text-xs text-green-600">{t("orderDetail.disputeOk")}</p>'),
    ('<p className="text-xs text-muted-foreground">至少輸入 10 個字</p>',
     '<p className="text-xs text-muted-foreground">{t("orderDetail.disputeMinChars")}</p>'),
    ('<p className="text-sm font-medium">證據截圖（選項，最多 3 張）</p>',
     '<p className="text-sm font-medium">{t("orderDetail.evidenceScreenshots")}</p>'),
    ('alt={`證據 ${i + 1}`}', 'alt={`${t("orderDetail.evidence")} ${i + 1}`}'),
    (': <><span className="text-2xl text-muted-foreground">+</span><span className="text-[10px] text-mut',
     ': <><span className="text-2xl text-muted-foreground">+</span><span className="text-[10px] text-mut'),
    ('<p className="text-xs text-muted-foreground">支援 JPG、PNG，單張不超過 5MB</p>',
     '<p className="text-xs text-muted-foreground">{t("orderDetail.screenshotHint")}</p>'),
    (': <><Flag className="w-4 h-4 mr-2" />提交爭議</>}',
     ': <><Flag className="w-4 h-4 mr-2" />{t("orderDetail.submitDispute")}</>}'),
    # Review dialog
    ('<p className="text-sm font-medium">評分</p>', '<p className="text-sm font-medium">{t("orderDetail.rating")}</p>'),
    ('{reviewRating === 1 && "非常不滿意"}', '{reviewRating === 1 && t("orderDetail.rating1")}'),
    ('{reviewRating === 2 && "不滿意"}', '{reviewRating === 2 && t("orderDetail.rating2")}'),
    ('{reviewRating === 3 && "一般"}', '{reviewRating === 3 && t("orderDetail.rating3")}'),
    ('{reviewRating === 4 && "滿意"}', '{reviewRating === 4 && t("orderDetail.rating4")}'),
    ('{reviewRating === 5 && "非常滿意"}', '{reviewRating === 5 && t("orderDetail.rating5")}'),
    ('<p className="text-sm font-medium">評語（選填）</p>',
     '<p className="text-sm font-medium">{t("orderDetail.reviewComment")}</p>'),
    ('placeholder="分享你的購物體驗..."', 'placeholder={t("orderDetail.reviewPlaceholder")}'),
    ('<span className="text-sm">匿名評價</span>', '<span className="text-sm">{t("orderDetail.anonymousReview")}</span>'),
    ('<span className="text-xs text-muted-foreground">（賣家將不會看到你的名字）</span>',
     '<span className="text-xs text-muted-foreground">{t("orderDetail.anonymousNote")}</span>'),
    # Seller ship dialog
    ('<Truck className="w-5 h-5" style={{ color: \'#06038d\' }} />填寫出貨資料',
     '<Truck className="w-5 h-5" style={{ color: \'#06038d\' }} />{t("orderDetail.enterShippingInfo")}'),
    ('<p className="font-semibold text-sm text-blue-900">📦 買家收貨資訊</p>',
     '<p className="font-semibold text-sm text-blue-900">{t("orderDetail.buyerShippingInfo")}</p>'),
    ('<p>收件人：{shippingAddr.name} {shippingAddr.phone}</p>',
     '<p>{t("orderDetail.recipient")}：{shippingAddr.name} {shippingAddr.phone}</p>'),
    ('<p>地址：{shippingAddr.address}{shippingAddr.district ? `，${shippingAddr.district}` : \'\'}，{shippingAddr.reg',
     '<p>{t("orderDetail.address")}：{shippingAddr.address}{shippingAddr.district ? `，${shippingAddr.district}` : \'\'}，{shippingAddr.reg'),
    ('<Label className="text-gray-800 font-medium">物流公司 <span className="text-red-500">*</span></Label>',
     '<Label className="text-gray-800 font-medium">{t("orderDetail.courierCompany")} <span className="text-red-500">*</span></Label>'),
    ('<option value="sf_express">順豐速運 (SF Express)</option>',
     '<option value="sf_express">{t("orderDetail.sfExpress")}</option>'),
    ('<option value="hkpost">香港郵政 (HK Post)</option>',
     '<option value="hkpost">{t("orderDetail.hkPost")}</option>'),
    ('<option value="chunghwa_post">中華郵政</option>',
     '<option value="chunghwa_post">{t("orderDetail.chunghwaPost")}</option>'),
    ('<option value="black_cat">黑貓宅急</option>',
     '<option value="black_cat">{t("orderDetail.blackCat")}</option>'),
    ('<option value="other">其他</option>',
     '<option value="other">{t("orderDetail.other")}</option>'),
    ('<Label className="text-gray-800 font-medium">追蹤號碼 <span className="text-red-500">*</span></Label>',
     '<Label className="text-gray-800 font-medium">{t("orderDetail.trackingNo")} <span className="text-red-500">*</span></Label>'),
    ('<Label className="text-gray-800 font-medium">出貨憑證圖片 <span className="text-red-500">*</span></Label>',
     '<Label className="text-gray-800 font-medium">{t("orderDetail.shippingProofImage")} <span className="text-red-500">*</span></Label>'),
    ('<p className="text-xs text-amber-600 bg-amber-50 border border-amber-200 rounded-md px-2 py-1.5">⚠️ 必須上傳出貨',
     '<p className="text-xs text-amber-600 bg-amber-50 border border-amber-200 rounded-md px-2 py-1.5">⚠️ {t("seller.shipping.proofRequired")}'),
    ('<span className="text-xs">上傳中...</span>', '<span className="text-xs">{t("common.uploading")}</span>'),
    ('<span className="text-xs font-medium">點擊上傳出貨照片</span>',
     '<span className="text-xs font-medium">{t("seller.shipping.uploadPhoto")}</span>'),
    ('<span className="text-xs text-gray-400">支援 JPG、PNG（最大 10MB）</span>',
     '<span className="text-xs text-gray-400">{t("seller.shipping.uploadHint")}</span>'),
    (': <><Truck className="w-4 h-4 mr-2" />確認出貨</>}',
     ': <><Truck className="w-4 h-4 mr-2" />{t("orderDetail.confirmShipment")}</>}'),
    # Auction payment notice
    ('此訂單為拍賣競標得標，請於 {paymentTimeoutMinutes >= 60 ? `${Math.floor(paymentTimeoutMinutes / 60)} 小時` : `${payme',
     '{t("orderDetail.auctionWonNotice", { time: paymentTimeoutMinutes >= 60 ? `${Math.floor(paymentTimeoutMinutes / 60)} ${t("common.hours")}` : `${payme'),
]

count = 0
not_found = []
for old, new in replacements:
    if old in content:
        content = content.replace(old, new, 1)
        count += 1
    else:
        not_found.append(old[:80])

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Done! {count}/{len(replacements)} replacements made")
if not_found:
    print(f"\nNot found ({len(not_found)}):")
    for s in not_found[:10]:
        print(f"  ✗ {s}")
