import re

with open('client/src/pages/GradingSubmit.tsx', encoding='utf-8') as f:
    content = f.read()

replacements = [
    # Terms array
    ('  "本人確認所提交的卡牌為本人合法擁有，並非贓物或侵權物品。如日後發現卡牌來源有問題，本人須承擔一切法律責任。"',
     '  t("gradingSubmit.terms.0")'),
    ('  "本人明白 PSA 鑑定結果為最終結果，BOXIUM 無法干預評分，亦不保證任何特定評分。對評分結果有任何異議，須直接向 PSA 提出，BOXIUM 不負責跟進。"',
     '  t("gradingSubmit.terms.1")'),
    ('  "本人明白卡片一經提交 PSA 後，申請不可取消，費用亦不予退還。如需在 BOXIUM 收件後取消，須於 48 小時內書面通知並支付 HK$50 行政費。"',
     '  t("gradingSubmit.terms.2")'),
    ('  "本人明白客人自費寄件至 BOXIUM 的過程由客人自行承擔風險，BOXIUM 不負責寄件途中的遺失或損壞。強烈建議客人購買運輸保險。"',
     '  t("gradingSubmit.terms.3")'),
    ('  "本人明白鑑定完成後須於 30 天內完成付款。逾期未付款，BOXIUM 保留對相關卡片自行處理之權利，包括但不限於出售、捐贈或銷毀，客人將不獲任何賠償。"',
     '  t("gradingSubmit.terms.4")'),
    ('  "本人明白 BOXIUM 對 PSA 之任何服務中斷、政策變更、價格調整或其他不可抗力因素概不負責。"',
     '  t("gradingSubmit.terms.5")'),
    ('  "本人明白價格或會因應官方調整而更改，恕不另行通知。鑑定期以工作天計算，實際時間會根據官方實際情況而定，不包括運輸時間。"',
     '  t("gradingSubmit.terms.6")'),
    ('  "本人明白 BOXIUM 只作代理服務，卡牌鑑定期間由 PSA 負責保管，BOXIUM 不對 PSA 保管期間的任何損失負責。"',
     '  t("gradingSubmit.terms.7")'),
    ('  "本人明白提交申請即代表同意 BOXIUM 收集及使用本人的個人資料（包括姓名、聯絡方式及卡牌資料）用於處理本次申請。"',
     '  t("gradingSubmit.terms.8")'),
    ('  "本人確認所填寫的資料屬實，如有虛假陳述，BOXIUM 保留拒絕服務及追究責任的權利。"',
     '  t("gradingSubmit.terms.9")'),
    # formatDraftAge function
    ('  if (diffMins < 1) return "剛才";',
     '  if (diffMins < 1) return t("gradingSubmit.draft.justNow");'),
    ('  if (diffMins < 60) return `${diffMins} 分鐘前`;',
     '  if (diffMins < 60) return t("gradingSubmit.draft.minutesAgo", { count: diffMins });'),
    ('  if (diffHours < 24) return `${diffHours} 小時前`;',
     '  if (diffHours < 24) return t("gradingSubmit.draft.hoursAgo", { count: diffHours });'),
    ('  if (diffDays === 1) return "昨天";',
     '  if (diffDays === 1) return t("gradingSubmit.draft.yesterday");'),
    ('  return `${diffDays} 天前`;',
     '  return t("gradingSubmit.draft.daysAgo", { count: diffDays });'),
    # region default
    ("    region: '香港',", "    region: t(\"gradingSubmit.address.regionDefault\"),"),
    # toast messages
    ("      toast.error(`提交失敗：${err.message}`);",
     '      toast.error(t("gradingSubmit.toast.submitFailed", { msg: err.message }));'),
    ('      toast.success("地址已儲存到個人中心");',
     '      toast.success(t("gradingSubmit.toast.addressSaved"));'),
    ('      toast.error("至少需要一張卡牌");',
     '      toast.error(t("gradingSubmit.toast.needOneCard"));'),
    ('      toast.error("請選擇服務層級");',
     '      toast.error(t("gradingSubmit.toast.selectTier"));'),
    ('        toast.error("請為每張卡牌選擇卡牌資料");',
     '        toast.error(t("gradingSubmit.toast.selectCardData"));'),
    ('        toast.error("請填寫卡牌名稱");',
     '        toast.error(t("gradingSubmit.toast.fillCardName"));'),
    ('      toast.error("請先閱讀並同意服務條款");',
     '      toast.error(t("gradingSubmit.toast.agreeTerms"));'),
    ("          region: saved.region || '香港',",
     "          region: saved.region || t(\"gradingSubmit.address.regionDefault\"),"),
    ('      toast.error("請填寫收件人姓名和電話");',
     '      toast.error(t("gradingSubmit.toast.fillNamePhone"));'),
    ("           toast.error(\"請選擇順豐自提站\");",
     '           toast.error(t("gradingSubmit.toast.selectSFStation"));'),
    ('          toast.error("請填寫詳細地址");',
     '          toast.error(t("gradingSubmit.toast.fillAddress"));'),
    ("          region: manualReturnAddress.region || '香港',",
     "          region: manualReturnAddress.region || t(\"gradingSubmit.address.regionDefault\"),"),
    ("            region: manualReturnAddress.region || '香港',",
     "            region: manualReturnAddress.region || t(\"gradingSubmit.address.regionDefault\"),"),
    # UI text
    ('          <h2 className="text-xl font-bold text-gray-900 mb-2">請先登入</h2>',
     '          <h2 className="text-xl font-bold text-gray-900 mb-2">{t("gradingSubmit.loginRequired.title")}</h2>'),
    ('          <p className="text-gray-500 mb-6">提交 PSA 鑑定申請需要登入帳號</p>',
     '          <p className="text-gray-500 mb-6">{t("gradingSubmit.loginRequired.desc")}</p>'),
    ('              登入 / 註冊',
     '              {t("gradingSubmit.loginRequired.btn")}'),
    ('          <h1 className="text-2xl font-bold text-gray-900">PSA 代客鑑定申請</h1>',
     '          <h1 className="text-2xl font-bold text-gray-900">{t("gradingSubmit.pageTitle")}</h1>'),
    ('          <p className="text-gray-500 text-sm mt-1">填寫卡牌資料，提交後請打印申請單連同卡牌寄出</p>',
     '          <p className="text-gray-500 text-sm mt-1">{t("gradingSubmit.pageDesc")}</p>'),
    ("                       <span>草稿將於{draftAgeDays >= 6.5 ? '明天' : '1 天內'}自動刪除，請盡快繼續申請</span>",
     "                       <span>{t(\"gradingSubmit.draft.expiresWarning\", { when: draftAgeDays >= 6.5 ? t(\"gradingSubmit.draft.tomorrow\") : t(\"gradingSubmit.draft.withinOneDay\") })}</span>"),
    ('                       <p className={`font-bold mb-0.5 ${isExpiringSoon ? \'text-orange-900\' : \'text-blue-900\'}`}>發現上次未完成的',
     '                       <p className={`font-bold mb-0.5 ${isExpiringSoon ? \'text-orange-900\' : \'text-blue-900\'}`}>{t("gradingSubmit.draft.foundDraft")}'),
    ('                         {draftItemCount > 0 ? `共 ${draftItemCount} 種卡牌（${draftTotalQty} 張）` : \'已選層級\'}',
     '                         {draftItemCount > 0 ? t("gradingSubmit.draft.cardCount", { types: draftItemCount, qty: draftTotalQty }) : t("gradingSubmit.draft.tierSelected")}'),
    ('                           <span className="ml-1">· 已選層級：<strong>{draftTierName}</strong></span>',
     '                           <span className="ml-1">· {t("gradingSubmit.draft.selectedTier")}<strong>{draftTierName}</strong></span>'),
    ('                       繼續上次的申請',
     '                       {t("gradingSubmit.draft.continueDraft")}'),
    ('                       刪除草稿，開新申請',
     '                       {t("gradingSubmit.draft.deleteDraft")}'),
    ('              <h2 className="font-bold text-gray-900 mb-1">選擇服務層級</h2>',
     '              <h2 className="font-bold text-gray-900 mb-1">{t("gradingSubmit.selectTier.title")}</h2>'),
    ('              <p className="text-xs text-gray-500 mb-4">此次申請的所有卡牌將使用相同服務層級</p>',
     '              <p className="text-xs text-gray-500 mb-4">{t("gradingSubmit.selectTier.desc")}</p>'),
    ('                下一步：填寫卡牌資料',
     '                {t("gradingSubmit.selectTier.nextStep")}'),
    ('                  <span className="text-xs text-blue-600 font-semibold">已選服務層級</span>',
     '                  <span className="text-xs text-blue-600 font-semibold">{t("gradingSubmit.selectTier.selected")}</span>'),
    ('                    更改',
     '                    {t("gradingSubmit.selectTier.change")}'),
    ('              新增卡牌',
     '              {t("gradingSubmit.addCard")}'),
    ('                  {totalQuantity} 張 × HK${parseFloat(selectedTier.feeHkd).toLocaleString()}',
     '                  {t("gradingSubmit.feeCalc", { qty: totalQuantity, fee: parseFloat(selectedTier.feeHkd).toLocaleString() })}'),
    ('                <span className="font-bold text-[#06038d]">合計 HK${totalFee.toLocaleString()}</span>',
     '                <span className="font-bold text-[#06038d]">{t("gradingSubmit.totalFee", { fee: totalFee.toLocaleString() })}</span>'),
    ('                返回',
     '                {t("common.back")}'),
    ('                下一步：確認提交',
     '                {t("gradingSubmit.nextConfirm")}'),
    ('                <span className="font-bold">費用明細</span>',
     '                <span className="font-bold">{t("gradingSubmit.feeBreakdown")}</span>'),
    ('                    : (item.card?.name ?? "未知卡牌");',
     '                    : (item.card?.name ?? t("gradingSubmit.unknownCard"));'),
    ('                    <p className="font-bold text-gray-900">代送 PSA 費用合計</p>',
     '                    <p className="font-bold text-gray-900">{t("gradingSubmit.totalPSAFee")}</p>'),
    ('                       共 {items.reduce((sum, i) => sum + ((i as any).quantity ?? 1), 0)} 張卡牌 · 費用已包含 BOXIUM 代辦服務費',
     '                       {t("gradingSubmit.cardCountFeeNote", { count: items.reduce((sum, i) => sum + ((i as any).quantity ?? 1), 0) })}'),
    ('                <span className="font-bold">客戶收貨地址</span>',
     '                <span className="font-bold">{t("gradingSubmit.returnAddress.title")}</span>'),
    ('                <span className="text-blue-200 text-xs ml-1 hidden sm:inline">（鑑定完成後回寄）</span>',
     '                <span className="text-blue-200 text-xs ml-1 hidden sm:inline">{t("gradingSubmit.returnAddress.subtitle")}</span>'),
    ('                  <Truck className="h-3 w-3" />順豐到付',
     '                  <Truck className="h-3 w-3" />{t("gradingSubmit.sfCOD")}'),
    ('                  <span className="font-bold">順豐到付：</span>所有回寄貨物均以順豐到付方式寄出，達付時預計進行收貨。如選擇順豐自提站，請確保站點已開放接件。',
     '                  <span className="font-bold">{t("gradingSubmit.sfCOD")}：</span>{t("gradingSubmit.sfCODDesc")}'),
    ('                       <p className="font-bold mb-0.5">您尚未儲存任何收貨地址</p>',
     '                       <p className="font-bold mb-0.5">{t("gradingSubmit.noSavedAddress")}</p>'),
    ('                        <p>請在下方填寫收貨地址，或先前往',
     '                        <p>{t("gradingSubmit.fillAddressOr")}'),
    ('                        儲存常用地址。',
     '                        {t("gradingSubmit.saveCommonAddress")}'),
    ('                       已儲存地址',
     '                       {t("gradingSubmit.savedAddresses")}'),
    ('                       輸入新地址',
     '                       {t("gradingSubmit.enterNewAddress")}'),
    ('                              <span className="text-xs bg-[#06038d] text-white px-1.5 py-0.5 rounded">預設</span>',
     '                              <span className="text-xs bg-[#06038d] text-white px-1.5 py-0.5 rounded">{t("gradingSubmit.defaultLabel")}</span>'),
    ('                              <span className="text-xs bg-orange-100 text-orange-700 px-1.5 py-0.5 rounded">順豐站</span>',
     '                              <span className="text-xs bg-orange-100 text-orange-700 px-1.5 py-0.5 rounded">{t("gradingSubmit.sfStation")}</span>'),
    ('                             <p className="text-xs text-gray-600 mt-0.5 truncate">順豐站 {addr.sfStationCode} · {addr.sfStat',
     '                             <p className="text-xs text-gray-600 mt-0.5 truncate">{t("gradingSubmit.sfStationCode")} {addr.sfStationCode} · {addr.sfStat'),
    ('                       使用其他地址',
     '                       {t("gradingSubmit.useOtherAddress")}'),
    ('                         <label className="block text-xs font-semibold text-gray-700 mb-1">收件人姓名 <span className="text-re',
     '                         <label className="block text-xs font-semibold text-gray-700 mb-1">{t("gradingSubmit.recipientName")} <span className="text-re'),
    ('                          placeholder="例：陳大文"',
     '                          placeholder={t("gradingSubmit.recipientNamePlaceholder")}'),
    ('                         <label className="block text-xs font-semibold text-gray-700 mb-1">聯絡電話 <span className="text-red',
     '                         <label className="block text-xs font-semibold text-gray-700 mb-1">{t("gradingSubmit.phone")} <span className="text-red'),
    ('                          placeholder="例：9123 4567"',
     '                          placeholder={t("gradingSubmit.phonePlaceholder")}'),
    ('                         <MapPin className="h-3.5 w-3.5" />一般地址',
     '                         <MapPin className="h-3.5 w-3.5" />{t("gradingSubmit.regularAddress")}'),
    ('                         <Truck className="h-3.5 w-3.5" />順豐自提站',
     '                         <Truck className="h-3.5 w-3.5" />{t("gradingSubmit.sfPickupStation")}'),
    ('                           <label className="block text-xs font-semibold text-gray-700 mb-1">詳細地址 <span className="text-r',
     '                           <label className="block text-xs font-semibold text-gray-700 mb-1">{t("gradingSubmit.detailedAddress")} <span className="text-r'),
    ('                             placeholder="例：九龍旺角彌敦道 123 號 XX 大廈 5 樓 A 室"',
     '                             placeholder={t("gradingSubmit.addressPlaceholder")}'),
    ('                             <label className="block text-xs font-semibold text-gray-700 mb-1">地區</label>',
     '                             <label className="block text-xs font-semibold text-gray-700 mb-1">{t("gradingSubmit.district")}</label>'),
    ('                               placeholder="例：旺角"',
     '                               placeholder={t("gradingSubmit.districtPlaceholder")}'),
    ('                             <label className="block text-xs font-semibold text-gray-700 mb-1">城市</label>',
     '                             <label className="block text-xs font-semibold text-gray-700 mb-1">{t("gradingSubmit.city")}</label>'),
    ('                               placeholder="香港"',
     '                               placeholder={t("gradingSubmit.cityPlaceholder")}'),
    ('                         <label className="block text-xs font-semibold text-gray-700">搜尋順豐自提站 <span className="text-red-5',
     '                         <label className="block text-xs font-semibold text-gray-700">{t("gradingSubmit.searchSFStation")} <span className="text-red-5'),
    ('                             placeholder="輸入站點名稱或地區，如：旺角、屬山、852FTL"',
     '                             placeholder={t("gradingSubmit.sfStationPlaceholder")}'),
    ('                                 <p className="text-xs text-gray-500 text-center py-4">找不到符合的站點</p>',
     '                                 <p className="text-xs text-gray-500 text-center py-4">{t("gradingSubmit.noStationFound")}</p>'),
    ('                         儲存此地址到個人中心，方便下次使用',
     '                         {t("gradingSubmit.saveAddressToProfile")}'),
    ('                         ← 返回選擇已儲存地址',
     '                         {t("gradingSubmit.backToSavedAddresses")}'),
    ('                <span className="font-bold text-gray-900">服務條款</span>',
     '                <span className="font-bold text-gray-900">{t("gradingSubmit.termsTitle")}</span>'),
    ('                  我已閱讀並同意以上所有服務條款，並確認所提交資料屬實。',
     '                  {t("gradingSubmit.agreeTermsLabel")}'),
    ('                返回修改',
     '                {t("gradingSubmit.backToEdit")}'),
    ('                    處理中...',
     '                    {t("common.processing")}'),
    ('                    提交申請',
     '                    {t("gradingSubmit.submitApplication")}'),
    ('              <h2 className="text-xl font-bold text-green-800 mb-1">申請已成功提交！</h2>',
     '              <h2 className="text-xl font-bold text-green-800 mb-1">{t("gradingSubmit.success.title")}</h2>'),
    ('                   <p className="font-bold text-amber-800 text-sm">請立即完成付款，否則申請將無法進入處理流程</p>',
     '                   <p className="font-bold text-amber-800 text-sm">{t("gradingSubmit.success.payNow")}</p>'),
    ('                     共 {submittedData.cardCount} 張卡牌 · 費用合計 <span className="font-bold text-[#06038d]">HK${submittedData.',
     '                     {t("gradingSubmit.success.cardCountFee", { count: submittedData.cardCount })} <span className="font-bold text-[#06038d]">HK${submittedData.'),
    ('                前往申請詳情頁完成付款',
     '                {t("gradingSubmit.success.goToDetail")}'),
    ('              <p className="font-semibold text-gray-800 text-sm">付款後的下一步</p>',
     '              <p className="font-semibold text-gray-800 text-sm">{t("gradingSubmit.success.nextStepsTitle")}</p>'),
    ('                { icon: Package, text: "付款確認後，系統將自動發送確認通知（站內訊息 + Email），包含 BOXIUM 送件地址" },',
     '                { icon: Package, text: t("gradingSubmit.success.step1") },'),
    ('                { icon: FileText, text: "請打印申請單，連同卡牌自費寄至 BOXIUM 指定地址（順豐站 852Z351）" },',
     '                { icon: FileText, text: t("gradingSubmit.success.step2") },'),
    ('                { icon: CheckCircle2, text: "BOXIUM 確認收件後，代辦 PSA 申報及專業包裝，每月 2 次出團直送美國 PSA" },',
     '                { icon: CheckCircle2, text: t("gradingSubmit.success.step3") },'),
    ('                查看所有申請記錄',
     '                {t("gradingSubmit.success.viewAllApplications")}'),
    # 更換 button
    ('                       更換',
     '                       {t("gradingSubmit.changeCard")}'),
]

count = 0
for old, new in replacements:
    if old in content:
        content = content.replace(old, new, 1)
        count += 1
    else:
        print(f"NOT FOUND: {old[:80]}")

with open('client/src/pages/GradingSubmit.tsx', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Done! Applied {count}/{len(replacements)} replacements")
